-- Auto-generated by scripts/build_coppelia_scene.py
-- Scenario: comm_r3_smith
local scene = {
scenario = "comm_r3_smith",
seed = 2027,
warehouse = {
width_m = 36.0,
depth_m = 24.0,
floor_thickness_m = 0.08,
style = "industrial fulfillment center without proprietary branding",
safety_markings = true
},
controller = {
policy = "smith_full",
playback_csv = "",
closed_loop_topic = "python_policy_cmd_vel"
},
communication = {
radius_m = 3.0,
packet_loss = 0.0,
show_links = true
},
robots = {{
name = "Pioneer_01",
model = "Pioneer 3-DX",
position = {-15.0, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_02",
model = "Pioneer 3-DX",
position = {-12.9, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_03",
model = "Pioneer 3-DX",
position = {-10.8, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_04",
model = "Pioneer 3-DX",
position = {-8.7, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_05",
model = "Pioneer 3-DX",
position = {-6.6, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_06",
model = "Pioneer 3-DX",
position = {-4.5, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_07",
model = "Pioneer 3-DX",
position = {-2.4, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_08",
model = "Pioneer 3-DX",
position = {-0.3, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_09",
model = "Pioneer 3-DX",
position = {1.8, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_10",
model = "Pioneer 3-DX",
position = {3.9, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_11",
model = "Pioneer 3-DX",
position = {6.0, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_12",
model = "Pioneer 3-DX",
position = {8.1, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_13",
model = "Pioneer 3-DX",
position = {10.2, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_14",
model = "Pioneer 3-DX",
position = {12.3, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}, {
name = "Pioneer_15",
model = "Pioneer 3-DX",
position = {14.4, -10.8, 0.18},
heading_rad = 0.0,
sensors = {"front_proximity", "lidar_2d", "load_detector", "local_comm"}
}},
racks = {{
name = "Rack_01",
position = {-13.0, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_02",
position = {-7.8, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_03",
position = {-2.6, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_04",
position = {2.6, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_05",
position = {7.8, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_06",
position = {13.0, -7.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 0
}, {
name = "Rack_07",
position = {-13.0, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_08",
position = {-7.8, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_09",
position = {-2.6, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_10",
position = {2.6, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_11",
position = {7.8, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_12",
position = {13.0, -1.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 1
}, {
name = "Rack_13",
position = {-13.0, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}, {
name = "Rack_14",
position = {-7.8, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}, {
name = "Rack_15",
position = {-2.6, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}, {
name = "Rack_16",
position = {2.6, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}, {
name = "Rack_17",
position = {7.8, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}, {
name = "Rack_18",
position = {13.0, 4.5, 1.5},
size = {3.8, 0.9, 3.0},
aisle = 2
}},
loads = {{
name = "Load_heavy_01",
position = {-15.5, -5.0, 0.35},
size = {1.0, 0.8, 0.5},
weight = 10
}, {
name = "Load_medium_01",
position = {15.0, -4.0, 0.35},
size = {0.8, 0.7, 0.45},
weight = 6
}, {
name = "Load_light_01",
position = {-14.0, 8.0, 0.25},
size = {0.55, 0.45, 0.35},
weight = 2
}},
humans = {{
name = "Operator_01",
position = {-17.3, -5.0, 0.9},
route = {{-17.3, -5.0, 0.9}, {16.5, -4.0, 0.9}},
speed_mps = 0.75
}, {
name = "Operator_02",
position = {-17.3, -0.8, 0.9},
route = {{-17.3, -0.7999999999999998, 0.9}, {16.5, 0.20000000000000018, 0.9}},
speed_mps = 0.75
}},
sensors = {
lidar_range_m = 6.0,
proximity_range_m = 2.0,
load_detection_range_m = 1.4,
blind_zones = {}
},
events = {
robot_failure = {
enabled = false,
robot = "Pioneer_03",
time_s = 90.0
},
forklift_crossing = {
enabled = false,
time_s = 120.0
}
}
}

local function setName(handle, name)
    if handle and handle >= 0 then sim.setObjectAlias(handle, name, 1) end
    return handle
end

local function cuboid(name, size, pos, color)
    local h = sim.createPureShape(0, 8, size, 0.1, nil)
    setName(h, name)
    sim.setObjectPosition(h, -1, pos)
    if color then sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color) end
    return h
end

local function cylinder(name, radius, height, pos, color)
    local h = sim.createPureShape(2, 8, {radius * 2.0, radius * 2.0, height}, 0.1, nil)
    setName(h, name)
    sim.setObjectPosition(h, -1, pos)
    if color then sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color) end
    return h
end

local function tryLoadPioneer(robot)
    local candidates = {
        sim.getStringParam(sim.stringparam_systemdir) .. '/models/robots/mobile/Pioneer p3dx.ttm',
        sim.getStringParam(sim.stringparam_systemdir) .. '/models/robots/mobile/Pioneer P3-DX.ttm',
        sim.getStringParam(sim.stringparam_systemdir) .. '/models/robots/mobile/Pioneer 3-DX.ttm'
    }
    for _, path in ipairs(candidates) do
        local ok, handle = pcall(sim.loadModel, path)
        if ok and handle and handle >= 0 then
            setName(handle, robot.name)
            sim.setObjectPosition(handle, -1, robot.position)
            sim.setObjectOrientation(handle, -1, {0, 0, robot.heading_rad})
            return handle
        end
    end
    local base = cylinder(robot.name .. '_Pioneer3DX_fallback', 0.28, 0.32, robot.position, {0.10, 0.22, 0.34})
    cuboid(robot.name .. '_sensor_bar', {0.48, 0.06, 0.06}, {robot.position[1], robot.position[2] + 0.22, robot.position[3] + 0.23}, {0.03, 0.10, 0.16})
    return base
end

local function addDummy(name, pos)
    local h = sim.createDummy(0.08)
    setName(h, name)
    sim.setObjectPosition(h, -1, pos)
    return h
end

sim.setNamedStringParam('mrbo_scene_json', [==[{
  "scenario": "comm_r3_smith",
  "seed": 2027,
  "warehouse": {
    "width_m": 36.0,
    "depth_m": 24.0,
    "floor_thickness_m": 0.08,
    "style": "industrial fulfillment center without proprietary branding",
    "safety_markings": true
  },
  "controller": {
    "policy": "smith_full",
    "playback_csv": "",
    "closed_loop_topic": "python_policy_cmd_vel"
  },
  "communication": {
    "radius_m": 3.0,
    "packet_loss": 0.0,
    "show_links": true
  },
  "robots": [
    {
      "name": "Pioneer_01",
      "model": "Pioneer 3-DX",
      "position": [
        -15.0,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_02",
      "model": "Pioneer 3-DX",
      "position": [
        -12.9,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_03",
      "model": "Pioneer 3-DX",
      "position": [
        -10.8,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_04",
      "model": "Pioneer 3-DX",
      "position": [
        -8.7,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_05",
      "model": "Pioneer 3-DX",
      "position": [
        -6.6,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_06",
      "model": "Pioneer 3-DX",
      "position": [
        -4.5,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_07",
      "model": "Pioneer 3-DX",
      "position": [
        -2.4,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_08",
      "model": "Pioneer 3-DX",
      "position": [
        -0.3,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_09",
      "model": "Pioneer 3-DX",
      "position": [
        1.8,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_10",
      "model": "Pioneer 3-DX",
      "position": [
        3.9,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_11",
      "model": "Pioneer 3-DX",
      "position": [
        6.0,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_12",
      "model": "Pioneer 3-DX",
      "position": [
        8.1,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_13",
      "model": "Pioneer 3-DX",
      "position": [
        10.2,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_14",
      "model": "Pioneer 3-DX",
      "position": [
        12.3,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    },
    {
      "name": "Pioneer_15",
      "model": "Pioneer 3-DX",
      "position": [
        14.4,
        -10.8,
        0.18
      ],
      "heading_rad": 0.0,
      "sensors": [
        "front_proximity",
        "lidar_2d",
        "load_detector",
        "local_comm"
      ]
    }
  ],
  "racks": [
    {
      "name": "Rack_01",
      "position": [
        -13.0,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_02",
      "position": [
        -7.8,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_03",
      "position": [
        -2.6,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_04",
      "position": [
        2.6,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_05",
      "position": [
        7.8,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_06",
      "position": [
        13.0,
        -7.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 0
    },
    {
      "name": "Rack_07",
      "position": [
        -13.0,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_08",
      "position": [
        -7.8,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_09",
      "position": [
        -2.6,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_10",
      "position": [
        2.6,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_11",
      "position": [
        7.8,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_12",
      "position": [
        13.0,
        -1.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 1
    },
    {
      "name": "Rack_13",
      "position": [
        -13.0,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    },
    {
      "name": "Rack_14",
      "position": [
        -7.8,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    },
    {
      "name": "Rack_15",
      "position": [
        -2.6,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    },
    {
      "name": "Rack_16",
      "position": [
        2.6,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    },
    {
      "name": "Rack_17",
      "position": [
        7.8,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    },
    {
      "name": "Rack_18",
      "position": [
        13.0,
        4.5,
        1.5
      ],
      "size": [
        3.8,
        0.9,
        3.0
      ],
      "aisle": 2
    }
  ],
  "loads": [
    {
      "name": "Load_heavy_01",
      "position": [
        -15.5,
        -5.0,
        0.35
      ],
      "size": [
        1.0,
        0.8,
        0.5
      ],
      "weight": 10
    },
    {
      "name": "Load_medium_01",
      "position": [
        15.0,
        -4.0,
        0.35
      ],
      "size": [
        0.8,
        0.7,
        0.45
      ],
      "weight": 6
    },
    {
      "name": "Load_light_01",
      "position": [
        -14.0,
        8.0,
        0.25
      ],
      "size": [
        0.55,
        0.45,
        0.35
      ],
      "weight": 2
    }
  ],
  "humans": [
    {
      "name": "Operator_01",
      "position": [
        -17.3,
        -5.0,
        0.9
      ],
      "route": [
        [
          -17.3,
          -5.0,
          0.9
        ],
        [
          16.5,
          -4.0,
          0.9
        ]
      ],
      "speed_mps": 0.75
    },
    {
      "name": "Operator_02",
      "position": [
        -17.3,
        -0.8,
        0.9
      ],
      "route": [
        [
          -17.3,
          -0.7999999999999998,
          0.9
        ],
        [
          16.5,
          0.20000000000000018,
          0.9
        ]
      ],
      "speed_mps": 0.75
    }
  ],
  "sensors": {
    "lidar_range_m": 6.0,
    "proximity_range_m": 2.0,
    "load_detection_range_m": 1.4,
    "blind_zones": []
  },
  "events": {
    "robot_failure": {
      "enabled": false,
      "robot": "Pioneer_03",
      "time_s": 90.0
    },
    "forklift_crossing": {
      "enabled": false,
      "time_s": 120.0
    }
  }
}]==])

cuboid('Warehouse_floor', {scene.warehouse.width_m, scene.warehouse.depth_m, scene.warehouse.floor_thickness_m}, {0, 0, -scene.warehouse.floor_thickness_m / 2}, {0.46, 0.48, 0.49})
cuboid('Inbound_station', {3.0, 2.0, 0.08}, {-scene.warehouse.width_m / 2 + 2.0, -scene.warehouse.depth_m / 2 + 2.0, 0.03}, {0.10, 0.40, 0.70})
cuboid('Outbound_station', {3.0, 2.0, 0.08}, {scene.warehouse.width_m / 2 - 2.0, scene.warehouse.depth_m / 2 - 2.0, 0.03}, {0.10, 0.55, 0.25})

for _, rack in ipairs(scene.racks) do
    cuboid(rack.name, rack.size, rack.position, {0.42, 0.44, 0.46})
end

for _, load in ipairs(scene.loads) do
    cuboid(load.name .. '_w' .. tostring(load.weight), load.size, load.position, {0.85, 0.58, 0.20})
end

for _, robot in ipairs(scene.robots) do
    local handle = tryLoadPioneer(robot)
    addDummy(robot.name .. '_lidar_2d_range_' .. tostring(scene.sensors.lidar_range_m), {robot.position[1], robot.position[2], robot.position[3] + 0.35})
    addDummy(robot.name .. '_local_comm_R' .. tostring(scene.communication.radius_m), {robot.position[1], robot.position[2], robot.position[3] + 0.55})
end

for _, human in ipairs(scene.humans) do
    cylinder(human.name, 0.22, 1.8, human.position, {0.78, 0.20, 0.18})
    addDummy(human.name .. '_route_start', human.route[1])
    addDummy(human.name .. '_route_end', human.route[2])
end

for _, zone in ipairs(scene.sensors.blind_zones) do
    cuboid(zone.name, zone.size, zone.center, {0.80, 0.10, 0.10})
end

if scene.events.robot_failure.enabled then
    addDummy('Robot_failure_event_' .. scene.events.robot_failure.robot .. '_t' .. tostring(scene.events.robot_failure.time_s), {0, 0, 1.2})
end

sim.addLog(sim.verbosity_scriptinfos, 'MRBO warehouse scene generated: ' .. scene.scenario .. ' policy=' .. scene.controller.policy)
