"""Derive V4 denominator tables and provenance from the frozen V3 corpus.

The generator intentionally does not create scientific capability labels.  It
only reports what the recorded V3 inputs support and gates changes to the
declared corpus freeze.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
from datetime import UTC, datetime
from pathlib import Path


EXPECTED_COUNTS = {
    "discovery_identities": 3014,
    "analytic_documents": 244,
    "dated_analytic_documents": 243,
    "eligible_fulltext_documents": 168,
    "canonical_priority_documents": 59,
    "passage_localized_cards": 20,
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def derive_metrics(v3_root: Path) -> tuple[dict[str, int], dict[str, str]]:
    data_dir = v3_root / "data"
    discovery = data_dir / "discovery_registry_v3.csv"
    analytic = data_dir / "analytic_corpus_v3.csv"
    close_read_dir = v3_root / "close-read"
    discovery_rows = read_csv(discovery)
    analytic_rows = read_csv(analytic)
    close_cards = sorted(path for path in close_read_dir.glob("*.md") if path.name != "README.md")
    metrics = {
        "discovery_identities": len(discovery_rows),
        "analytic_documents": len(analytic_rows),
        "dated_analytic_documents": sum(bool(row["year"].strip()) for row in analytic_rows),
        "eligible_fulltext_documents": sum(row["close_reading_eligibility"] == "eligible" for row in analytic_rows),
        "canonical_priority_documents": sum(row["priority_tier"] == "P0" for row in analytic_rows),
        "passage_localized_cards": len(close_cards),
    }
    cards_digest = hashlib.sha256(
        "".join(f"{path.name}:{sha256(path)}\n" for path in close_cards).encode("utf-8")
    ).hexdigest()
    return metrics, {
        "discovery_registry": sha256(discovery),
        "analytic_corpus": sha256(analytic),
        "close_read_cards": cards_digest,
    }


def assert_expected(metrics: dict[str, int]) -> None:
    mismatches = {
        name: {"expected": expected, "observed": metrics[name]}
        for name, expected in EXPECTED_COUNTS.items()
        if metrics[name] != expected
    }
    if mismatches:
        raise ValueError(
            "V4 corpus freeze mismatch. Create a new documented version instead "
            f"of silently reusing its figures: {mismatches}"
        )


def write_layers(path: Path, metrics: dict[str, int]) -> None:
    rows = [
        ("discovery", metrics["discovery_identities"], "n/a", "coverage, provenance and candidate screening only"),
        ("analytic_mapping", metrics["analytic_documents"], metrics["discovery_identities"], "patterns in the recovered corpus; not technical implementation"),
        ("dated_mapping", metrics["dated_analytic_documents"], metrics["analytic_documents"], "temporal patterns with 2026 explicitly incomplete"),
        ("fulltext_eligible", metrics["eligible_fulltext_documents"], metrics["analytic_documents"], "candidates available for close reading"),
        ("canonical_priority", metrics["canonical_priority_documents"], metrics["analytic_documents"], "priority technical comparison; field coding still required"),
        ("passage_localized", metrics["passage_localized_cards"], metrics["eligible_fulltext_documents"], "located passages, scoped by individual evidence cards"),
    ]
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["layer", "n", "denominator", "allowed_claim"])
        writer.writerows(rows)


def write_tex(path: Path, metrics: dict[str, int], inputs: dict[str, str], reference_hash: str) -> None:
    values = {
        "VFourDiscovery": f"{metrics['discovery_identities']:,}".replace(",", "\\,"),
        "VFourAnalytic": str(metrics["analytic_documents"]),
        "VFourDated": str(metrics["dated_analytic_documents"]),
        "VFourEligible": str(metrics["eligible_fulltext_documents"]),
        "VFourCanonical": str(metrics["canonical_priority_documents"]),
        "VFourCards": str(metrics["passage_localized_cards"]),
        "VFourCorpusHash": inputs["analytic_corpus"][:12],
        "VFourReferenceHash": reference_hash[:12],
    }
    with path.open("w", encoding="utf-8") as stream:
        stream.write("% Generated by build_v4_literature_audit.py; do not edit.\n")
        for name, value in values.items():
            stream.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")


def write_qa(path: Path, metrics: dict[str, int], inputs: dict[str, str], reference: Path) -> None:
    lines = [
        "# QA V4 - denominadores y trazabilidad",
        "",
        "Los invariantes de este corte coinciden con los datos de entrada. Esto "
        "verifica denominadores y procedencia, no una clasificación científica por celda.",
        "",
        "## Denominadores derivados",
        "",
        *[f"- `{name}`: {value}" for name, value in metrics.items()],
        "",
        "## Hashes de entrada",
        "",
        *[f"- `{name}`: `{value}`" for name, value in inputs.items()],
        f"- `reference_pdf`: `{sha256(reference)}`",
        "",
        "## Límites vigentes",
        "",
        "- Web of Science F01/F02 y la cartera arXiv siguen parciales.",
        "- No hay acuerdo interrevisor ni sensibilidad V4 ejecutada.",
        "- La matriz de capacidades debe recodificarse desde pasajes localizados antes de usarla para afirmaciones de ausencia.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference-pdf", type=Path, required=True)
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.repository_root.resolve()
    reference = args.reference_pdf.resolve()
    if not reference.is_file():
        raise FileNotFoundError(reference)
    v3_root = root / "academic-review" / "literature-review-v3"
    v4_root = root / "academic-review" / "literature-review-v4"
    metrics, inputs = derive_metrics(v3_root)
    assert_expected(metrics)

    data_dir = v4_root / "data"
    generated_dir = v4_root / "generated"
    source_dir = v4_root / "source"
    for directory in (data_dir, generated_dir, source_dir):
        directory.mkdir(parents=True, exist_ok=True)
    copied_reference = source_dir / "MROB_literature_review_reworked_2.pdf"
    shutil.copy2(reference, copied_reference)
    reference_hash = sha256(copied_reference)
    if reference_hash != sha256(reference):
        raise ValueError("Copied visual reference hash differs from the supplied PDF.")

    write_layers(data_dir / "corpus_layers_v4.csv", metrics)
    write_tex(generated_dir / "v4_metrics.tex", metrics, inputs, reference_hash)
    write_qa(v4_root / "QA_V4.md", metrics, inputs, copied_reference)
    manifest = {
        "version": "V4.0",
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "generator": "academic-review/scripts/build_v4_literature_audit.py",
        "expected_counts": EXPECTED_COUNTS,
        "observed_counts": metrics,
        "input_sha256": inputs,
        "reference_pdf": str(copied_reference.relative_to(root)).replace("\\\\", "/"),
        "reference_pdf_sha256": reference_hash,
        "pending_controls": [
            "gold-set recall validation",
            "independent double coding and agreement analysis",
            "field-level recoding of the nearest-prior matrix",
            "sensitivity scenarios S1-S8",
        ],
    }
    (v4_root / "reproducibility_manifest_v4.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps({"status": "ok", "observed_counts": metrics}, ensure_ascii=False))


if __name__ == "__main__":
    main()
