#!/usr/bin/env python3
"""Render the exhaustive formal-result audit as a compact LaTeX atlas."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[3]
AUDIT_DIR = REPO_ROOT / "pre-thesis" / "evidence" / "integrity" / "formal-audit"
AUDIT_PATH = AUDIT_DIR / "semantic-all.csv"
SUMMARY_PATH = AUDIT_DIR / "semantic-all-summary.json"
OUTPUT_PATH = (
    REPO_ROOT
    / "pre-thesis"
    / "monograph"
    / "sections"
    / "formal-candidate-atlas.tex"
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def breakable_digest(value: str) -> str:
    chunks = [value[index : index + 8] for index in range(0, len(value), 8)]
    return r"\texttt{" + r"\allowbreak{}".join(chunks) + "}"


def read_inputs() -> tuple[list[dict[str, str]], dict[str, object]]:
    if not AUDIT_PATH.is_file() or not SUMMARY_PATH.is_file():
        raise FileNotFoundError("the merged semantic audit has not been generated")
    with AUDIT_PATH.open("r", encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))
    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    if not summary.get("complete"):
        raise ValueError("the formal audit is partial; the atlas requires complete coverage")
    if len(rows) != summary.get("inventory_count"):
        raise ValueError("audit row count does not match the complete inventory")
    ids = [row["result_id"] for row in rows]
    if len(ids) != len(set(ids)):
        raise ValueError("the merged formal audit contains duplicate result IDs")
    required = {
        "result_id",
        "type",
        "title",
        "normalized_verdict",
        "recommended_destination",
        "promotion_decision",
    }
    missing = required - set(rows[0] if rows else {})
    if missing:
        raise ValueError(f"missing audit columns: {sorted(missing)}")
    return rows, summary


def render(rows: list[dict[str, str]], summary: dict[str, object]) -> str:
    counts = Counter(row["normalized_verdict"] for row in rows)
    digest = sha256_file(AUDIT_PATH)
    count_text = "; ".join(
        f"{latex_escape(key)}: {value}" for key, value in sorted(counts.items())
    )
    lines = [
        "% Generated by pre-thesis/evidence/tools/build_formal_candidate_atlas.py.",
        "% Do not edit by hand.",
        r"\section{Atlas de resultados formales candidatos}",
        r"\label{sec:formal-candidate-atlas}",
        "",
        (
            "Este atlas registra los "
            f"{len(rows)} resultados formales detectados en el corpus candidato. "
            "El veredicto evalúa el enunciado y la prueba en su fuente; no incorpora "
            "el resultado a la columna activa ni sustituye el cruce con una afirmación "
            "y evidencia independiente. Los textos completos, supuestos, dominios, "
            "unidades, contraejemplos y razones de decisión permanecen en "
            r"\texttt{semantic-all.csv}."
        ),
        "",
        (
            r"La distribución normalizada es "
            f"{count_text}. Ningún registro se promovió automáticamente. "
            "La tabla se generó a partir de una auditoría completa marcada como "
            rf"\texttt{{complete=true}} y ligada al SHA-256 {breakable_digest(digest)}."
        ),
        "",
        r"\begingroup",
        r"\scriptsize",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\setlength{\tabcolsep}{2.4pt}",
        r"\begin{longtable}{@{}p{3.05cm}p{1.15cm}p{1.45cm}p{2.55cm}p{5.35cm}@{}}",
        r"\caption{Inventario exhaustivo de resultados formales candidatos y decisión conservadora de destino.}\label{tab:formal-candidate-atlas}\\",
        r"\toprule",
        r"ID & Tipo & Veredicto & Destino & Título \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{5}{c}{\tablename\ \thetable\ (continuación)}\\",
        r"\toprule",
        r"ID & Tipo & Veredicto & Destino & Título \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{5}{r}{Continúa en la página siguiente}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for row in rows:
        values = (
            row["result_id"],
            row["type"],
            row["normalized_verdict"],
            row["recommended_destination"],
            row["title"],
        )
        lines.append(" & ".join(latex_escape(value) for value in values) + r" \\")
    lines.extend(
        [
            r"\end{longtable}",
            r"\endgroup",
            "",
            (
                r"La decisión de destino es documental: los registros \texttt{PASS} "
                r"aún requieren enlace exacto con el ledger de claims; \texttt{LIMITED} "
                r"y \texttt{CONJECTURE} solo se conservan con su frontera explícita; "
                r"\texttt{FAIL} no respalda conclusiones; y \texttt{DUPLICATE} remite "
                "al resultado canónico."
            ),
            "",
        ]
    )
    if summary.get("automatic_promotions") != 0:
        raise ValueError("automatic promotions are forbidden")
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rows, summary = read_inputs()
    payload = render(rows, summary).encode("utf-8")
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_bytes() != payload:
            print(f"FORMAL CANDIDATE ATLAS CHECK FAILED: stale-or-missing:{OUTPUT_PATH}")
            return 1
        print(f"FORMAL CANDIDATE ATLAS CHECK PASSED rows={len(rows)}")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_bytes(payload)
    print(f"FORMAL CANDIDATE ATLAS BUILT rows={len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
