"""Planar load geometry and unilateral wrench helpers."""

from __future__ import annotations

import math
from collections.abc import Iterable

import numpy as np

from .models import ContactSlot


def planar_wrench_column(
    slot: ContactSlot,
    *,
    com_offset_xy_m: np.ndarray | None = None,
) -> np.ndarray:
    """Return ``[Fx, Fy, tau_z]`` generated by one newton at a slot."""

    com = np.zeros(2, dtype=float) if com_offset_xy_m is None else np.asarray(
        com_offset_xy_m, dtype=float
    )
    arm = np.asarray(slot.offset_xy_m, dtype=float) - com
    direction = np.asarray(slot.direction_xy, dtype=float)
    torque = float(arm[0] * direction[1] - arm[1] * direction[0])
    return np.array([direction[0], direction[1], torque], dtype=float)


def aligned_wrench_resources(column: np.ndarray, demand: np.ndarray) -> np.ndarray:
    """Map a signed wrench column to nonnegative demand-aligned resources.

    The returned order is force-x, force-y, positive torque, negative torque.
    The signed column is retained separately for physical certification.
    """

    vector = np.asarray(column, dtype=float)
    required = np.asarray(demand, dtype=float)
    aligned_x = max(float(np.sign(required[0]) * vector[0]), 0.0) if abs(
        required[0]
    ) > 1e-12 else abs(float(vector[0]))
    aligned_y = max(float(np.sign(required[1]) * vector[1]), 0.0) if abs(
        required[1]
    ) > 1e-12 else abs(float(vector[1]))
    positive_torque = max(float(vector[2]), 0.0)
    negative_torque = max(float(-vector[2]), 0.0)
    return np.array(
        [aligned_x, aligned_y, positive_torque, negative_torque], dtype=float
    )


def demand_resource_vector(required_wrench: np.ndarray) -> np.ndarray:
    required = np.asarray(required_wrench, dtype=float)
    return np.array(
        [
            abs(float(required[0])),
            abs(float(required[1])),
            max(float(required[2]), 0.0),
            max(float(-required[2]), 0.0),
        ],
        dtype=float,
    )


def circle_slots(
    count: int,
    radius_m: float,
    *,
    force_limit_n: float,
    prefix: str = "radial",
) -> tuple[ContactSlot, ...]:
    """Create inward radial push slots around a circular footprint."""

    if count < 1 or radius_m <= 0.0:
        raise ValueError("count and radius_m must be positive.")
    slots: list[ContactSlot] = []
    for index in range(count):
        angle = 2.0 * math.pi * index / count
        offset = radius_m * np.array([math.cos(angle), math.sin(angle)])
        direction = -offset / radius_m
        slots.append(
            ContactSlot(
                identifier=f"{prefix}-{index:02d}",
                offset_xy_m=offset,
                direction_xy=direction,
                role="radial_support",
                max_force_n=float(force_limit_n),
            )
        )
    return tuple(slots)


def rectangular_slots(
    count: int,
    length_m: float,
    width_m: float,
    *,
    force_limit_n: float,
    mixed_directions: bool = True,
    prefix: str = "rect",
) -> tuple[ContactSlot, ...]:
    """Create deterministic perimeter slots for rectangular loads."""

    if count < 1 or min(length_m, width_m, force_limit_n) <= 0.0:
        raise ValueError("Invalid rectangular slot parameters.")
    templates = [
        (np.array([0.0, width_m / 2.0]), np.array([1.0, 0.0]), "top_x_pos"),
        (np.array([0.0, -width_m / 2.0]), np.array([-1.0, 0.0]), "bottom_x_neg"),
        (np.array([-length_m / 2.0, 0.0]), np.array([0.0, 1.0]), "left_y_pos"),
        (np.array([length_m / 2.0, 0.0]), np.array([0.0, -1.0]), "right_y_neg"),
        (np.array([0.0, width_m / 2.0]), np.array([-1.0, 0.0]), "top_x_neg"),
        (np.array([0.0, -width_m / 2.0]), np.array([1.0, 0.0]), "bottom_x_pos"),
        (np.array([-length_m / 2.0, 0.0]), np.array([0.0, -1.0]), "left_y_neg"),
        (np.array([length_m / 2.0, 0.0]), np.array([0.0, 1.0]), "right_y_pos"),
    ]
    if not mixed_directions:
        templates = [
            (
                np.array([-length_m / 2.0, 0.0]),
                np.array([1.0, 0.0]),
                "separable_push_x",
            )
            for _ in range(max(count, 1))
        ]
    slots = []
    for index in range(count):
        offset, direction, role = templates[index % len(templates)]
        slots.append(
            ContactSlot(
                identifier=f"{prefix}-{index:02d}",
                offset_xy_m=offset.copy(),
                direction_xy=direction.copy(),
                role=role,
                max_force_n=float(force_limit_n),
            )
        )
    return tuple(slots)


def superellipse_boundary(
    count: int,
    semi_axes_m: tuple[float, float],
    exponent: float,
) -> np.ndarray:
    """Sample a superellipse boundary for scenario/figure generation."""

    if count < 1 or min(semi_axes_m) <= 0.0 or exponent <= 0.0:
        raise ValueError("Invalid superellipse parameters.")
    angles = np.linspace(0.0, 2.0 * math.pi, count, endpoint=False)
    cosine, sine = np.cos(angles), np.sin(angles)
    x = semi_axes_m[0] * np.sign(cosine) * np.abs(cosine) ** (2.0 / exponent)
    y = semi_axes_m[1] * np.sign(sine) * np.abs(sine) ** (2.0 / exponent)
    return np.column_stack([x, y])


def slot_wrench_matrix(
    slots: Iterable[ContactSlot],
    *,
    com_offset_xy_m: np.ndarray | None = None,
) -> np.ndarray:
    columns = [
        planar_wrench_column(slot, com_offset_xy_m=com_offset_xy_m) for slot in slots
    ]
    return np.column_stack(columns) if columns else np.zeros((3, 0), dtype=float)


__all__ = [
    "aligned_wrench_resources",
    "circle_slots",
    "demand_resource_vector",
    "planar_wrench_column",
    "rectangular_slots",
    "slot_wrench_matrix",
    "superellipse_boundary",
]
