"""Build the reproducible SP0--SP8 literature-coverage fragment for Figure 2."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


PERIODS: tuple[tuple[int, int], ...] = (
    (1985, 1994),
    (1995, 2004),
    (2005, 2009),
    (2010, 2014),
    (2015, 2019),
    (2020, 2022),
    (2023, 2026),
)

SP_LABELS: tuple[str, ...] = (
    r"Asignaci\'on 1--1",
    "Cardinalidad",
    r"Capacidad heterog.",
    r"Factibilidad / \emph{wrench}",
    "Transporte de pose",
    r"Obst\'aculos / seguridad",
    "Fallo / re-reclut.",
    r"Tr\'afico multi-coalic.",
    "Escala / red",
)

# 0 = obligatorio, 1 = extension prioritaria, 2 = condicionado.
SP_SCOPE_CODES: tuple[int, ...] = (0, 0, 0, 0, 0, 1, 0, 2, 0)

_YEAR_RE = re.compile(r"\(((?:19|20)\d{2})\)")
_SP_RE = re.compile(r"SP(\d)(?:\s*(?:--|–|-)\s*(?:SP)?(\d))?")
_UNESCAPED_PIPE_RE = re.compile(r"(?<!\\)\|")


@dataclass(frozen=True)
class LedgerEntry:
    """Verified ledger entry with the fields required by the coverage audit."""

    key: str
    year: int
    subproblems: frozenset[int]


def _split_markdown_row(line: str) -> list[str]:
    content = line.strip().strip("|")
    return [cell.replace(r"\|", "|").strip() for cell in _UNESCAPED_PIPE_RE.split(content)]


def _parse_subproblems(topic: str) -> frozenset[int]:
    subproblems: set[int] = set()
    for start_text, end_text in _SP_RE.findall(topic):
        start = int(start_text)
        end = int(end_text) if end_text else start
        if not (0 <= start <= end <= 8):
            raise ValueError(f"Invalid SP range in ledger topic: {topic!r}")
        subproblems.update(range(start, end + 1))
    return frozenset(subproblems)


def parse_verified_entries(ledger_text: str) -> tuple[LedgerEntry, ...]:
    """Parse verified Markdown-table rows without inferring missing metadata."""

    entries: list[LedgerEntry] = []
    for line_number, line in enumerate(ledger_text.splitlines(), start=1):
        if not line.startswith("| `"):
            continue
        cells = _split_markdown_row(line)
        if len(cells) < 8:
            raise ValueError(f"Malformed ledger row at line {line_number}")
        key, state, reference, _, topic = cells[:5]
        if state != "VERIFICADA":
            continue
        year_match = _YEAR_RE.search(reference)
        if year_match is None:
            raise ValueError(f"Verified ledger row {key} has no publication year")
        entries.append(
            LedgerEntry(
                key=key.strip("`"),
                year=int(year_match.group(1)),
                subproblems=_parse_subproblems(topic),
            )
        )
    return tuple(entries)


def coverage_counts(
    entries: Iterable[LedgerEntry],
    periods: tuple[tuple[int, int], ...] = PERIODS,
) -> tuple[tuple[int, ...], ...]:
    """Count each verified source once per applicable SP and time period."""

    materialized = tuple(entries)
    return tuple(
        tuple(
            sum(
                1
                for entry in materialized
                if sp in entry.subproblems and start <= entry.year <= end
            )
            for start, end in periods
        )
        for sp in range(9)
    )


def render_latex_fragment(ledger_text: str) -> str:
    """Render deterministic calls consumed by the Figure 2 TikZ macro."""

    entries = parse_verified_entries(ledger_text)
    counts = coverage_counts(entries)
    digest = hashlib.sha256(ledger_text.encode("utf-8")).hexdigest()
    lines = [
        "% Generated by src/viu_mrob_tfm/literature_coverage.py; do not edit.",
        f"% Ledger SHA-256: {digest}",
    ]
    for sp, (label, values, scope_code) in enumerate(
        zip(SP_LABELS, counts, SP_SCOPE_CODES, strict=True)
    ):
        values_text = ",".join(str(value) for value in values)
        lines.append(
            rf"\coveragegeneratedrow{{SP{sp}}}{{{label}}}"
            rf"{{{values_text}}}{{{sum(values)}}}{{{scope_code}}}"
        )
    return "\n".join(lines) + "\n"


def write_latex_fragment(ledger_path: Path, output_path: Path) -> None:
    """Write the generated fragment only when its content changes."""

    ledger_text = ledger_path.read_text(encoding="utf-8")
    rendered = render_latex_fragment(ledger_text)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == rendered:
        return
    output_path.write_text(rendered, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    write_latex_fragment(args.ledger, args.output)


if __name__ == "__main__":
    main()
