-- Auto-generated by scripts/coppelia/build_aws_canonical_scene.py
-- Scenario: aws_canonical_coop_transport_pioneer_p3dx
-- Usage:
--   1. Open CoppeliaSim.
--   2. Open C:\Program Files\CoppeliaRobotics\CoppeliaSimEdu\scenes\awsRobomaker\aws_robomaker_warehouse.ttt
--   3. Run: dofile([[C:\Users\walla\Documents\Github\VIU-MRBO-TFM-2026\coppeliasim\real_scenes\aws_canonical_coop_transport_pioneer_p3dx.lua]])
-- The Python generator can also export a .ttt file directly through ZMQ.

local scene = {
scenario = "aws_canonical_coop_transport_pioneer_p3dx",
description = "Canonical 12x10 m cooperative multi-AGV transport overlay on AWS RoboMaker warehouse.",
base_scene = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\scenes\\awsRobomaker\\aws_robomaker_warehouse.ttt",
dimensions_m = {
width = 12.0,
depth = 10.0
},
model_paths = {
pioneer_p3dx = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\mobile\\pioneer p3dx.ttm",
conveyor = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\equipment\\conveyors\\generic conveyor (rollers).ttm",
table = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\furniture\\tables\\high table.ttm",
manipulator = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\non-mobile\\ABB IRB 140.ttm",
rack = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\furniture\\shelves-cupboards-racks\\rack.ttm"
},
zones = {{
name = "zona_inicial_agvs",
center = {-4.55, 3.85, 0.018},
size = {2.35, 1.55, 0.018},
color = {0.16, 0.34, 0.54},
kind = "initial"
}, {
name = "zona_recogida_a",
center = {-4.25, -1.55, 0.018},
size = {2.5, 1.7, 0.018},
color = {0.86, 0.62, 0.12},
kind = "pickup"
}, {
name = "zona_recogida_b",
center = {4.15, 1.45, 0.018},
size = {2.5, 1.7, 0.018},
color = {0.86, 0.62, 0.12},
kind = "pickup"
}, {
name = "zona_entrega_1",
center = {4.25, 3.75, 0.018},
size = {1.7, 1.2, 0.018},
color = {0.16, 0.46, 0.26},
kind = "delivery"
}, {
name = "zona_entrega_2",
center = {4.45, -3.55, 0.018},
size = {1.7, 1.25, 0.018},
color = {0.16, 0.46, 0.26},
kind = "delivery"
}, {
name = "zona_recarga",
center = {-4.55, -3.95, 0.018},
size = {2.35, 1.25, 0.018},
color = {0.58, 0.16, 0.13},
kind = "recharge"
}, {
name = "corredor_estrecho_oeste",
center = {-2.05, -0.55, 0.018},
size = {1.0, 1.25, 0.018},
color = {0.88, 0.68, 0.12},
kind = "narrow_corridor"
}, {
name = "corredor_estrecho_este",
center = {1.95, -0.55, 0.018},
size = {1.0, 1.25, 0.018},
color = {0.88, 0.68, 0.12},
kind = "narrow_corridor"
}},
racks = {{
name = "rack_norte_01",
position = {-2.7, 4.25, 0.06},
size = {1.15, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_norte_02",
position = {-1.3, 4.25, 0.06},
size = {1.15, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_norte_03",
position = {0.1, 4.25, 0.06},
size = {1.15, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_norte_04",
position = {1.5, 4.25, 0.06},
size = {1.15, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_muro_oeste_sup",
position = {-5.65, 2.25, 0.06},
size = {1.35, 0.46, 1.95},
yaw_rad = 1.5707963267948966
}, {
name = "rack_muro_oeste_med",
position = {-5.65, 0.35, 0.06},
size = {1.35, 0.46, 1.95},
yaw_rad = 1.5707963267948966
}, {
name = "rack_muro_este_sup",
position = {5.72, 2.75, 0.06},
size = {1.35, 0.46, 1.95},
yaw_rad = 1.5707963267948966
}, {
name = "rack_muro_este_med",
position = {5.72, 0.75, 0.06},
size = {1.35, 0.46, 1.95},
yaw_rad = 1.5707963267948966
}, {
name = "rack_oeste_centro",
position = {-4.05, 0.15, 0.06},
size = {1.1, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_este_superior",
position = {2.6, 2.8, 0.06},
size = {1.0, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_01",
position = {-1.75, -2.65, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_02",
position = {0.0, -2.65, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_03",
position = {1.75, -2.65, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_04",
position = {-1.75, -3.75, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_05",
position = {0.0, -3.75, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_sur_centro_06",
position = {1.75, -3.75, 0.06},
size = {1.25, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_este_bajo",
position = {3.0, -3.2, 0.06},
size = {1.0, 0.46, 1.95},
yaw_rad = 0.0
}, {
name = "rack_oeste_bajo",
position = {-2.9, -3.65, 0.06},
size = {0.9, 0.46, 1.95},
yaw_rad = 0.0
}},
robots = {{
name = "Pioneer_01_ligero",
position = {-5.15, 4.08, 0.18},
heading_rad = -1.5707963267948966,
class = "ligero"
}, {
name = "Pioneer_02_medio",
position = {-4.55, 4.08, 0.18},
heading_rad = -1.5707963267948966,
class = "medio"
}, {
name = "Pioneer_03_alta_capacidad",
position = {-3.95, 4.08, 0.18},
heading_rad = -1.5707963267948966,
class = "alta_capacidad"
}, {
name = "Pioneer_04_ligero",
position = {-5.15, 3.48, 0.18},
heading_rad = -1.5707963267948966,
class = "ligero"
}, {
name = "Pioneer_05_medio",
position = {-4.55, 3.48, 0.18},
heading_rad = -1.5707963267948966,
class = "medio"
}, {
name = "Pioneer_06_alta_capacidad",
position = {-3.95, 3.48, 0.18},
heading_rad = -1.5707963267948966,
class = "alta_capacidad"
}},
loads = {{
name = "klt_a_01_3kg",
position = {-4.45, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 3.0,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_01_ligero",
phase_offset_s = 0.0,
workflow_load = true
}, {
name = "klt_a_02_5kg",
position = {-4.0, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 5.0,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_04_ligero",
phase_offset_s = 9.0,
workflow_load = true
}, {
name = "klt_a_03_2_5kg",
position = {-3.55, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 2.5,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_02_medio",
phase_offset_s = 18.0,
workflow_load = true
}, {
name = "klt_b_01_3kg",
position = {4.45, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 3.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_03_alta_capacidad",
phase_offset_s = 4.5,
workflow_load = true
}, {
name = "klt_b_02_4kg",
position = {4.0, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 4.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_05_medio",
phase_offset_s = 13.5,
workflow_load = true
}, {
name = "klt_b_03_5kg",
position = {3.55, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 5.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_06_alta_capacidad",
phase_offset_s = 22.5,
workflow_load = true
}},
central_obstacle = {
name = "obstaculo_central",
position = {0.0, 1.25, 0.35},
size = {2.4, 0.8, 0.7}
},
routes = {{
name = "ruta_inicial_a_recogida_a",
points = {{-3.35, 3.05}, {-3.0, 2.5}, {-3.0, -1.35}, {-3.95, -1.05}}
}, {
name = "ruta_inicial_a_recogida_b",
points = {{-3.35, 3.55}, {0.0, 3.55}, {2.5, 2.45}, {2.9, 1.45}}
}, {
name = "ruta_a_interseccion",
points = {{-3.95, -1.05}, {-2.05, -0.55}, {0.0, -0.55}, {1.95, -0.55}}
}, {
name = "ruta_b_entrega_1",
points = {{4.0, 2.35}, {4.0, 2.85}, {4.25, 3.25}}
}, {
name = "ruta_interseccion_entrega_2",
points = {{1.95, -0.55}, {3.0, -0.55}, {3.0, -2.3}, {4.45, -2.9}}
}, {
name = "ruta_retorno_recarga",
points = {{-2.05, -0.55}, {-3.0, -2.65}, {-3.4, -3.3}, {-4.55, -3.3}}
}},
stations = {
pickup_a = {
conveyor_position = {-4.05, -1.78, 0.0},
source_platform_position = {-4.55, -1.78, 0.0},
manipulator_position = {-4.65, -1.1, 0.2},
pick_position = {-4.2, -1.78, 0.84},
handoff_position = {-3.95, -1.05, 0.48}
},
pickup_b = {
conveyor_position = {4.05, 1.78, 0.0},
source_platform_position = {4.55, 1.78, 0.0},
manipulator_position = {4.65, 1.1, 0.2},
pick_position = {4.2, 1.78, 0.84},
handoff_position = {3.95, 1.05, 0.48}
},
delivery_1_marker = {4.25, 3.75, 0.04},
delivery_2_marker = {4.45, -3.55, 0.04},
recharge_marker = {-4.55, -3.95, 0.04},
footprints = {
conveyor = {1.55, 0.55},
manipulator = {0.65, 0.65}
}
},
metadata = {
communication = "local radio; heterogeneous transport requests by weight",
real_scale_assumptions = {
abb_irb_140 = {
payload_kg = 6.0,
reach_m = 0.81
},
pioneer_p3dx = {
length_m = 0.455,
width_m = 0.381,
height_m = 0.237,
payload_kg = 17.0
},
klt_box = {
length_m = 0.4,
width_m = 0.3,
height_m = 0.22,
max_pick_mass_kg = 5.0
}
},
robot_classes = {
ligero = {
capacity_kg = 17,
radius_m = 0.27,
max_speed_mps = 1.0
},
medio = {
capacity_kg = 17,
radius_m = 0.27,
max_speed_mps = 1.0
},
alta_capacidad = {
capacity_kg = 17,
radius_m = 0.27,
max_speed_mps = 0.8
}
},
narrow_corridor_width_m = 1.0,
standard_corridor_width_m = 1.5,
base_scene_policy = "AWS /warehouse is loaded as provenance but hidden and made non-collidable; the MRBO overlay provides the visible AWS-like warehouse finish on the canonical layout.",
visual_quality = "restrained industrial palette, procedural concrete panels, lane markings, detailed rack frames, KLT totes, real CoppeliaSim conveyor models, safety hardware and animated pick-handoff-transport demo script"
},
animation = {
cycle_s = 36.0,
box_cycle_s = 27.0,
manipulator_cycle_s = 9.0,
robots = {
Pioneer_01_ligero = {{-5.15, 4.08, 0.18}, {-3.35, 3.05, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-1.2, -0.55, 0.18}, {3.2, -0.55, 0.18}, {4.45, -3.0, 0.18}, {4.45, -3.55, 0.18}},
Pioneer_02_medio = {{-4.55, 4.08, 0.18}, {-3.0, 2.5, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-0.35, -0.55, 0.18}, {3.0, -0.55, 0.18}, {4.25, 3.25, 0.18}, {4.25, 3.75, 0.18}},
Pioneer_03_alta_capacidad = {{-3.95, 4.08, 0.18}, {0.0, 3.55, 0.18}, {2.5, 2.45, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {4.0, 2.35, 0.18}, {4.25, 3.75, 0.18}},
Pioneer_04_ligero = {{-5.15, 3.48, 0.18}, {-3.0, 2.2, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-3.0, -2.65, 0.18}, {-4.55, -3.3, 0.18}, {-4.55, -3.95, 0.18}},
Pioneer_05_medio = {{-4.55, 3.48, 0.18}, {-3.35, 3.55, 0.18}, {0.0, 3.55, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {4.15, 1.45, 0.18}},
Pioneer_06_alta_capacidad = {{-3.95, 3.48, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {0.0, -0.55, 0.18}, {1.95, -0.55, 0.18}, {4.45, -3.55, 0.18}}
},
manipulators = {"zona_recogida_a_manipulador_model", "zona_recogida_b_manipulador_model"}
}
}

local function setAlias(handle, name)
    if handle and handle >= 0 then pcall(sim.setObjectAlias, handle, name, 1) end
    return handle
end

local function setPhysics(handle, static, respondable, mass)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_static, static and 1 or 0)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_respondable, respondable and 1 or 0)
    pcall(sim.setObjectFloatParam, handle, sim.shapefloatparam_mass, mass or 0.001)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_edge_visibility, 1)
end

local function configureRendering()
    pcall(sim.setBoolParam, sim.boolparam_shape_textures_are_visible, true)
    pcall(sim.setArrayParam, sim.arrayparam_background_color1, {0.82, 0.86, 0.90})
    pcall(sim.setArrayParam, sim.arrayparam_background_color2, {0.72, 0.76, 0.82})
    pcall(sim.setArrayParam, sim.arrayparam_ambient_light, {0.55, 0.55, 0.55})
end

local function prepareAwsReference()
    local ok, warehouse = pcall(sim.getObject, '/warehouse')
    if not ok or not warehouse then return end
    for _, handle in ipairs(sim.getObjectsInTree(warehouse, sim.handle_all, 0)) do
        pcall(sim.setObjectInt32Param, handle, sim.objintparam_visibility_layer, 0)
        if sim.getObjectType(handle) == sim.object_shape_type then
            local props = sim.getObjectSpecialProperty(handle)
            local renderable = sim.objectspecialproperty_renderable or 0x0200
            pcall(sim.setObjectSpecialProperty, handle, bit32.band(bit32.bor(props, renderable), bit32.bnot(sim.objectspecialproperty_collidable)))
            pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_static, 1)
            pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_respondable, 0)
        end
    end
end

local function makeModelVisualOnly(handle)
    for _, child in ipairs(sim.getObjectsInTree(handle, sim.handle_all, 0)) do
        if sim.getObjectType(child) == sim.object_shape_type then
            local props = sim.getObjectSpecialProperty(child)
            local renderable = sim.objectspecialproperty_renderable or 0x0200
            pcall(sim.setObjectSpecialProperty, child, bit32.band(bit32.bor(props, renderable), bit32.bnot(sim.objectspecialproperty_collidable)))
            pcall(sim.setObjectInt32Param, child, sim.shapeintparam_static, 1)
            pcall(sim.setObjectInt32Param, child, sim.shapeintparam_respondable, 0)
        end
    end
end

local function disableModelScripts(handle)
    local scriptTypes = {sim.scripttype_simulation, sim.scripttype_customization, sim.scripttype_childscript, sim.scripttype_customizationscript}
    for _, obj in ipairs(sim.getObjectsInTree(handle, sim.handle_all, 0)) do
        for _, scriptType in ipairs(scriptTypes) do
            if scriptType then
                local ok, script = pcall(sim.getScript, scriptType, obj)
                if ok and script and script >= 0 then pcall(sim.removeObjects, {script}) end
            end
        end
    end
end

local function scaleModel(handle, scale)
    pcall(sim.scaleModelNonIsometrically, handle, scale[1], scale[2], scale[3])
end

local function box(name, size, pos, color, yaw, static, respondable, mass)
    local h = sim.createPrimitiveShape(sim.primitiveshape_cuboid, size, 0)
    setAlias(h, name)
    sim.setObjectPosition(h, -1, pos)
    sim.setObjectOrientation(h, -1, {0, 0, yaw or 0})
    sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color)
    setPhysics(h, static ~= false, respondable ~= false, mass or 0.001)
    return h
end

local function cylinder(name, radius, height, pos, color)
    local h = sim.createPrimitiveShape(sim.primitiveshape_cylinder, {radius * 2, radius * 2, height}, 0)
    setAlias(h, name)
    sim.setObjectPosition(h, -1, pos)
    sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color)
    setPhysics(h, true, false, 0.001)
    return h
end

local function modelOrFallback(path, name, pos, yaw, fallbackSize, fallbackColor, orientation, scale, keepScripts)
    local ok, handle = pcall(sim.loadModel, path)
    if ok and handle and handle >= 0 then
        setAlias(handle, name)
        if scale then scaleModel(handle, scale) end
        if not keepScripts then
            disableModelScripts(handle)
            makeModelVisualOnly(handle)
        end
        sim.setObjectPosition(handle, -1, pos)
        sim.setObjectOrientation(handle, -1, orientation or {0, 0, yaw or 0})
        return handle
    end
    return box(name .. '_fallback', fallbackSize, pos, fallbackColor, yaw or 0, true, true, 0.001)
end

local function zone(z)
    local sx, sy = z.size[1], z.size[2]
    local x, y = z.center[1], z.center[2]
    local z0 = 0.052
    local border = 0.045
    box(z.name .. '_north_line', {sx, border, 0.018}, {x, y + sy / 2, z0}, z.color, 0, true, false)
    box(z.name .. '_south_line', {sx, border, 0.018}, {x, y - sy / 2, z0}, z.color, 0, true, false)
    box(z.name .. '_east_line', {border, sy, 0.018}, {x + sx / 2, y, z0}, z.color, 0, true, false)
    box(z.name .. '_west_line', {border, sy, 0.018}, {x - sx / 2, y, z0}, z.color, 0, true, false)
    local corner = math.min(0.34, sx * 0.18, sy * 0.26)
    local corners = {
        {x - sx / 2 + corner / 2, y + sy / 2 - corner / 2, 0},
        {x + sx / 2 - corner / 2, y + sy / 2 - corner / 2, math.pi / 2},
        {x + sx / 2 - corner / 2, y - sy / 2 + corner / 2, math.pi},
        {x - sx / 2 + corner / 2, y - sy / 2 + corner / 2, -math.pi / 2},
    }
    for idx, c in ipairs(corners) do
        box(z.name .. '_corner_' .. idx .. '_a', {corner, border * 1.15, 0.018}, {c[1], c[2], z0 + 0.006}, z.color, c[3], true, false)
        box(z.name .. '_corner_' .. idx .. '_b', {border * 1.15, corner, 0.018}, {c[1], c[2], z0 + 0.007}, z.color, c[3], true, false)
    end
    if z.kind == 'delivery' or z.kind == 'recharge' then
        box(z.name .. '_subtle_pad', {sx * 0.64, sy * 0.50, 0.010}, {x, y, 0.035}, {z.color[1] * 0.78, z.color[2] * 0.78, z.color[3] * 0.78}, 0, true, false)
    end
end

local function route(name, pts)
    for i = 1, #pts - 1 do
        local ax, ay = pts[i][1], pts[i][2]
        local bx, by = pts[i + 1][1], pts[i + 1][2]
        local dx, dy = bx - ax, by - ay
        local len = math.sqrt(dx * dx + dy * dy)
        if len > 0.01 then
            local yaw = math.atan2(dy, dx)
            local ux, uy = dx / len, dy / len
            local count = math.max(1, math.floor(len / 0.70))
            for j = 1, count do
                local dist = math.min(len - 0.19, (j - 1) * 0.70 + 0.19)
                if dist > 0.18 then
                    box(name .. '_dash_' .. i .. '_' .. j, {0.38, 0.035, 0.025}, {ax + ux * dist, ay + uy * dist, 0.065}, {0.92, 0.92, 0.86}, yaw, true, false)
                end
            end
        end
    end
end

local function rotateOffset(x, y, yaw)
    return x * math.cos(yaw) - y * math.sin(yaw), x * math.sin(yaw) + y * math.cos(yaw)
end

local function conveyor(name, pos, yaw)
    modelOrFallback(scene.model_paths.conveyor, name, pos, yaw, {1.30, 0.45, 0.16}, {0.13, 0.14, 0.14})
end

local function bollard(name, x, y)
    cylinder(name, 0.055, 0.55, {x, y, 0.275}, {0.94, 0.67, 0.08})
    box(name .. '_black_band_1', {0.13, 0.018, 0.045}, {x, y, 0.23}, {0.04, 0.04, 0.04}, 0, true, false)
    box(name .. '_black_band_2', {0.13, 0.018, 0.045}, {x, y, 0.39}, {0.04, 0.04, 0.04}, 0, true, false)
end

local function guardrail(name, x, y, length, yaw)
    box(name .. '_rail_top', {length, 0.055, 0.070}, {x, y, 0.52}, {0.94, 0.67, 0.08}, yaw, true, false)
    box(name .. '_rail_mid', {length, 0.050, 0.060}, {x, y, 0.34}, {0.94, 0.67, 0.08}, yaw, true, false)
    for idx, offset in ipairs({-length / 2, 0.0, length / 2}) do
        local px, py = rotateOffset(offset, 0.0, yaw)
        box(name .. '_post_' .. idx, {0.065, 0.065, 0.50}, {x + px, y + py, 0.28}, {0.08, 0.08, 0.07}, yaw, true, false)
    end
end

local function safetyHardware()
    local o = scene.central_obstacle
    local x, y = o.position[1], o.position[2]
    local sx, sy = o.size[1], o.size[2]
    local points = {
        {x - sx / 2 - 0.18, y - sy / 2 - 0.18},
        {x + sx / 2 + 0.18, y - sy / 2 - 0.18},
        {x - sx / 2 - 0.18, y + sy / 2 + 0.18},
        {x + sx / 2 + 0.18, y + sy / 2 + 0.18},
    }
    for idx, p in ipairs(points) do bollard('obstaculo_central_bollard_' .. idx, p[1], p[2]) end
    for _, z in ipairs(scene.zones) do
        if z.kind == 'pickup' then
            guardrail(z.name .. '_rear_guardrail', z.center[1], z.center[2] - z.size[2] / 2 - 0.16, z.size[1] * 0.72, 0)
        end
    end
end

local function rackBlock(r)
    local x, y, yaw = r.position[1], r.position[2], r.yaw_rad
    local sx, sy, sz = r.size[1], r.size[2], r.size[3]
    box(r.name .. '_footprint', {sx, sy, 0.12}, {x, y, 0.14}, {0.08, 0.11, 0.13}, yaw, true, true)
    local uprightColor = {0.04, 0.17, 0.27}
    local beamColor = {0.94, 0.56, 0.10}
    local shelfColor = {0.27, 0.30, 0.32}
    local palletColor = {0.60, 0.40, 0.22}
    for idx, p in ipairs({{-sx / 2, -sy / 2}, {-sx / 2, sy / 2}, {sx / 2, -sy / 2}, {sx / 2, sy / 2}}) do
        local px, py = rotateOffset(p[1], p[2], yaw)
        box(r.name .. '_upright_' .. idx, {0.055, 0.055, sz}, {x + px, y + py, sz / 2}, uprightColor, yaw, true, false)
    end
    for levelIdx, levelZ in ipairs({0.42, 0.86, 1.30, 1.74}) do
        for sideIdx, oy in ipairs({-sy / 2, sy / 2}) do
            local px, py = rotateOffset(0, oy, yaw)
            box(r.name .. '_beam_L' .. levelIdx .. '_' .. sideIdx, {sx + 0.08, 0.05, 0.07}, {x + px, y + py, levelZ}, beamColor, yaw, true, false)
        end
        box(r.name .. '_shelf_deck_L' .. levelIdx, {sx * 0.96, sy * 0.82, 0.035}, {x, y, levelZ - 0.06}, shelfColor, yaw, true, false)
    end
    local cartonColors = {{0.72, 0.52, 0.30}, {0.62, 0.46, 0.28}, {0.80, 0.62, 0.38}}
    for levelSlot, cartonZ in ipairs({0.62, 1.06, 1.50}) do
        for idx, offset in ipairs({-0.30, 0.0, 0.30}) do
            local px, py = rotateOffset(offset * sx, 0, yaw)
            if levelSlot == 1 then
                box(r.name .. '_pallet_' .. idx, {math.min(0.36, sx / 3.5), sy * 0.70, 0.12}, {x + px, y + py, 0.49}, palletColor, yaw, true, false)
            end
            local c = cartonColors[((idx + levelSlot - 2) % #cartonColors) + 1]
            box(r.name .. '_carton_L' .. levelSlot .. '_' .. idx, {math.min(0.32, sx / 3.8), sy * 0.62, 0.24}, {x + px, y + py, cartonZ}, c, yaw, true, false)
        end
    end
    local lx, ly = rotateOffset(-sx / 2 + 0.12, -sy / 2 - 0.028, yaw)
    box(r.name .. '_barcode_label', {0.20, 0.012, 0.09}, {x + lx, y + ly, 1.88}, {0.92, 0.92, 0.86}, yaw, true, false)
end

local function installDemoScript()
    local scriptText = [==[-- Embedded deterministic motion preview for the MRBO AWS canonical scene.
local playback = {
cycle_s = 36.0,
box_cycle_s = 27.0,
manipulator_cycle_s = 9.0,
robots = {
Pioneer_01_ligero = {{-5.15, 4.08, 0.18}, {-3.35, 3.05, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-1.2, -0.55, 0.18}, {3.2, -0.55, 0.18}, {4.45, -3.0, 0.18}, {4.45, -3.55, 0.18}},
Pioneer_02_medio = {{-4.55, 4.08, 0.18}, {-3.0, 2.5, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-0.35, -0.55, 0.18}, {3.0, -0.55, 0.18}, {4.25, 3.25, 0.18}, {4.25, 3.75, 0.18}},
Pioneer_03_alta_capacidad = {{-3.95, 4.08, 0.18}, {0.0, 3.55, 0.18}, {2.5, 2.45, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {4.0, 2.35, 0.18}, {4.25, 3.75, 0.18}},
Pioneer_04_ligero = {{-5.15, 3.48, 0.18}, {-3.0, 2.2, 0.18}, {-3.95, -1.05, 0.18}, {-3.95, -1.05, 0.18}, {-3.0, -2.65, 0.18}, {-4.55, -3.3, 0.18}, {-4.55, -3.95, 0.18}},
Pioneer_05_medio = {{-4.55, 3.48, 0.18}, {-3.35, 3.55, 0.18}, {0.0, 3.55, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {4.15, 1.45, 0.18}},
Pioneer_06_alta_capacidad = {{-3.95, 3.48, 0.18}, {3.95, 1.05, 0.18}, {3.95, 1.05, 0.18}, {0.0, -0.55, 0.18}, {1.95, -0.55, 0.18}, {4.45, -3.55, 0.18}}
},
manipulators = {"zona_recogida_a_manipulador_model", "zona_recogida_b_manipulador_model"}
}
local stations = {
pickup_a = {
conveyor_position = {-4.05, -1.78, 0.0},
source_platform_position = {-4.55, -1.78, 0.0},
manipulator_position = {-4.65, -1.1, 0.2},
pick_position = {-4.2, -1.78, 0.84},
handoff_position = {-3.95, -1.05, 0.48}
},
pickup_b = {
conveyor_position = {4.05, 1.78, 0.0},
source_platform_position = {4.55, 1.78, 0.0},
manipulator_position = {4.65, 1.1, 0.2},
pick_position = {4.2, 1.78, 0.84},
handoff_position = {3.95, 1.05, 0.48}
},
delivery_1_marker = {4.25, 3.75, 0.04},
delivery_2_marker = {4.45, -3.55, 0.04},
recharge_marker = {-4.55, -3.95, 0.04},
footprints = {
conveyor = {1.55, 0.55},
manipulator = {0.65, 0.65}
}
}
local loads = {{
name = "klt_a_01_3kg",
position = {-4.45, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 3.0,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_01_ligero",
phase_offset_s = 0.0,
workflow_load = true
}, {
name = "klt_a_02_5kg",
position = {-4.0, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 5.0,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_04_ligero",
phase_offset_s = 9.0,
workflow_load = true
}, {
name = "klt_a_03_2_5kg",
position = {-3.55, -1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 2.5,
required_agvs = 1,
zone = "A",
station = "pickup_a",
assigned_amr = "Pioneer_02_medio",
phase_offset_s = 18.0,
workflow_load = true
}, {
name = "klt_b_01_3kg",
position = {4.45, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 3.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_03_alta_capacidad",
phase_offset_s = 4.5,
workflow_load = true
}, {
name = "klt_b_02_4kg",
position = {4.0, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 4.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_05_medio",
phase_offset_s = 13.5,
workflow_load = true
}, {
name = "klt_b_03_5kg",
position = {3.55, 1.78, 0.84},
size = {0.4, 0.3, 0.22},
weight_kg = 5.0,
required_agvs = 1,
zone = "B",
station = "pickup_b",
assigned_amr = "Pioneer_06_alta_capacidad",
phase_offset_s = 22.5,
workflow_load = true
}}
local robotHandles = {}
local robotPaths = {}
local robotByName = {}
local armStations = {}
local loadHandles = {}

local function getByAlias(alias)
    local ok, handle = pcall(sim.getObject, '/' .. alias)
    if ok and handle and handle >= 0 then return handle end
    return nil
end

local function clamp(v, lo, hi)
    return math.max(lo, math.min(hi, v))
end

local function lerp(a, b, u)
    return a + (b - a) * u
end

local function smooth(u)
    u = clamp(u, 0.0, 1.0)
    return u * u * (3.0 - 2.0 * u)
end

local function mix3(a, b, u)
    return {
        lerp(a[1], b[1], u),
        lerp(a[2], b[2], u),
        lerp(a[3], b[3], u)
    }
end

local function yawTo(a, b)
    return math.atan2(b[2] - a[2], b[1] - a[1])
end

local function samplePath(path, t, cycle)
    if #path < 2 then return path[1], 0 end
    local segCount = #path - 1
    local phase = (t % cycle) / cycle
    local scaled = phase * segCount
    local idx = math.min(segCount, math.floor(scaled) + 1)
    local u = scaled - (idx - 1)
    local a, b = path[idx], path[idx + 1]
    return {
        a[1] + (b[1] - a[1]) * u,
        a[2] + (b[2] - a[2]) * u,
        a[3] + (b[3] - a[3]) * u,
    }, yawTo(a, b)
end

function sysCall_init()
    local idx = 1
    for name, path in pairs(playback.robots) do
        local handle = getByAlias(name)
        if handle then
            robotHandles[idx] = handle
            robotPaths[idx] = path
            robotByName[name] = handle
            idx = idx + 1
        end
    end
    local stationArmAliases = {
        pickup_a = 'zona_recogida_a_manipulador_model',
        pickup_b = 'zona_recogida_b_manipulador_model'
    }
    for stationName, alias in pairs(stationArmAliases) do
        local handle = getByAlias(alias)
        if handle then
            local joints = sim.getObjectsInTree(handle, sim.object_joint_type, 0)
            if #joints > 0 then armStations[#armStations + 1] = {station = stationName, joints = joints} end
        end
    end
    for _, load in ipairs(loads) do
        local handle = getByAlias(load.name)
        if handle then loadHandles[load.name] = handle end
    end
end

local function setArmPose(stationName, joints, t)
    local offset = stationName == 'pickup_b' and 4.5 or 0.0
    local phase = ((t + offset) % playback.manipulator_cycle_s) / playback.manipulator_cycle_s
    local side = stationName == 'pickup_b' and -1.0 or 1.0
    local home = {0.0, -0.55, 0.95, 0.0, 0.72, 0.0}
    local pick = {side * 0.35, -0.82, 1.22, 0.0, 0.56, side * 0.18}
    local place = {side * -0.48, -0.70, 1.05, 0.0, 0.62, side * -0.18}
    local fromPose, toPose, u
    if phase < 0.22 then
        fromPose, toPose, u = home, pick, phase / 0.22
    elseif phase < 0.38 then
        fromPose, toPose, u = pick, pick, (phase - 0.22) / 0.16
    elseif phase < 0.68 then
        fromPose, toPose, u = pick, place, (phase - 0.38) / 0.30
    elseif phase < 0.82 then
        fromPose, toPose, u = place, place, (phase - 0.68) / 0.14
    else
        fromPose, toPose, u = place, home, (phase - 0.82) / 0.18
    end
    u = smooth(u)
    for jointIdx, joint in ipairs(joints) do
        local a = fromPose[((jointIdx - 1) % #fromPose) + 1]
        local b = toPose[((jointIdx - 1) % #toPose) + 1]
        local q = lerp(a, b, u)
        pcall(sim.setJointTargetPosition, joint, q)
        pcall(sim.setJointPosition, joint, q)
    end
end

local function setLoadPose(load, t)
    local handle = loadHandles[load.name]
    local station = stations[load.station]
    if not handle or not station then return end
    local cycle = playback.box_cycle_s or playback.cycle_s
    local phase = ((t + (load.phase_offset_s or 0.0)) % cycle) / cycle
    local halfHeight = load.size[3] / 2.0
    local spawn = load.position
    local pick = station.pick_position
    local handoff = {
        station.handoff_position[1],
        station.handoff_position[2],
        station.handoff_position[3] + halfHeight + 0.04
    }
    local pos = spawn
    local yaw = 0.0
    if phase < 0.18 then
        pos = mix3(spawn, pick, smooth(phase / 0.18))
    elseif phase < 0.44 then
        local u = smooth((phase - 0.18) / 0.26)
        pos = mix3(pick, handoff, u)
        pos[3] = pos[3] + 0.28 * math.sin(math.pi * u)
    elseif phase < 0.58 then
        pos = handoff
    else
        local robot = robotByName[load.assigned_amr]
        if robot then
            local ok, robotPos = pcall(sim.getObjectPosition, robot, -1)
            if ok and robotPos then
                pos = {robotPos[1], robotPos[2], robotPos[3] + 0.34}
                local okOri, robotOri = pcall(sim.getObjectOrientation, robot, -1)
                if okOri and robotOri then yaw = robotOri[3] end
            end
        end
    end
    pcall(sim.setObjectPosition, handle, -1, pos)
    pcall(sim.setObjectOrientation, handle, -1, {0, 0, yaw})
end

function sysCall_actuation()
    local t = sim.getSimulationTime()
    for i, handle in ipairs(robotHandles) do
        local pos, yaw = samplePath(robotPaths[i], t + (i - 1) * 1.7, playback.cycle_s)
        pcall(sim.setObjectPosition, handle, -1, pos)
        pcall(sim.setObjectOrientation, handle, -1, {0, 0, yaw})
    end
    for _, arm in ipairs(armStations) do
        setArmPose(arm.station, arm.joints, t)
    end
    for _, load in ipairs(loads) do setLoadPose(load, t) end
end
]==]
    local dummy = setAlias(sim.createDummy(0.03), 'MRBO_demo_controller')
    if sim.getBoolParam(sim.boolparam_usingscriptobjects) then
        local s = sim.createScript(sim.scripttype_simulation, scriptText, 0, 'lua')
        sim.setObjectParent(s, dummy)
    else
        local s = sim.addScript(sim.scripttype_simulation)
        sim.associateScriptWithObject(s, dummy)
        sim.setScriptText(s, scriptText)
    end
end

sim.setNamedStringParam('mrbo_aws_canonical_scene_json', [==[{
  "scenario": "aws_canonical_coop_transport_pioneer_p3dx",
  "description": "Canonical 12x10 m cooperative multi-AGV transport overlay on AWS RoboMaker warehouse.",
  "base_scene": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\scenes\\awsRobomaker\\aws_robomaker_warehouse.ttt",
  "dimensions_m": {
    "width": 12.0,
    "depth": 10.0
  },
  "model_paths": {
    "pioneer_p3dx": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\mobile\\pioneer p3dx.ttm",
    "conveyor": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\equipment\\conveyors\\generic conveyor (rollers).ttm",
    "table": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\furniture\\tables\\high table.ttm",
    "manipulator": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\non-mobile\\ABB IRB 140.ttm",
    "rack": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\furniture\\shelves-cupboards-racks\\rack.ttm"
  },
  "zones": [
    {
      "name": "zona_inicial_agvs",
      "center": [
        -4.55,
        3.85,
        0.018
      ],
      "size": [
        2.35,
        1.55,
        0.018
      ],
      "color": [
        0.16,
        0.34,
        0.54
      ],
      "kind": "initial"
    },
    {
      "name": "zona_recogida_a",
      "center": [
        -4.25,
        -1.55,
        0.018
      ],
      "size": [
        2.5,
        1.7,
        0.018
      ],
      "color": [
        0.86,
        0.62,
        0.12
      ],
      "kind": "pickup"
    },
    {
      "name": "zona_recogida_b",
      "center": [
        4.15,
        1.45,
        0.018
      ],
      "size": [
        2.5,
        1.7,
        0.018
      ],
      "color": [
        0.86,
        0.62,
        0.12
      ],
      "kind": "pickup"
    },
    {
      "name": "zona_entrega_1",
      "center": [
        4.25,
        3.75,
        0.018
      ],
      "size": [
        1.7,
        1.2,
        0.018
      ],
      "color": [
        0.16,
        0.46,
        0.26
      ],
      "kind": "delivery"
    },
    {
      "name": "zona_entrega_2",
      "center": [
        4.45,
        -3.55,
        0.018
      ],
      "size": [
        1.7,
        1.25,
        0.018
      ],
      "color": [
        0.16,
        0.46,
        0.26
      ],
      "kind": "delivery"
    },
    {
      "name": "zona_recarga",
      "center": [
        -4.55,
        -3.95,
        0.018
      ],
      "size": [
        2.35,
        1.25,
        0.018
      ],
      "color": [
        0.58,
        0.16,
        0.13
      ],
      "kind": "recharge"
    },
    {
      "name": "corredor_estrecho_oeste",
      "center": [
        -2.05,
        -0.55,
        0.018
      ],
      "size": [
        1.0,
        1.25,
        0.018
      ],
      "color": [
        0.88,
        0.68,
        0.12
      ],
      "kind": "narrow_corridor"
    },
    {
      "name": "corredor_estrecho_este",
      "center": [
        1.95,
        -0.55,
        0.018
      ],
      "size": [
        1.0,
        1.25,
        0.018
      ],
      "color": [
        0.88,
        0.68,
        0.12
      ],
      "kind": "narrow_corridor"
    }
  ],
  "racks": [
    {
      "name": "rack_norte_01",
      "position": [
        -2.7,
        4.25,
        0.06
      ],
      "size": [
        1.15,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_norte_02",
      "position": [
        -1.3,
        4.25,
        0.06
      ],
      "size": [
        1.15,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_norte_03",
      "position": [
        0.1,
        4.25,
        0.06
      ],
      "size": [
        1.15,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_norte_04",
      "position": [
        1.5,
        4.25,
        0.06
      ],
      "size": [
        1.15,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_muro_oeste_sup",
      "position": [
        -5.65,
        2.25,
        0.06
      ],
      "size": [
        1.35,
        0.46,
        1.95
      ],
      "yaw_rad": 1.5707963267948966
    },
    {
      "name": "rack_muro_oeste_med",
      "position": [
        -5.65,
        0.35,
        0.06
      ],
      "size": [
        1.35,
        0.46,
        1.95
      ],
      "yaw_rad": 1.5707963267948966
    },
    {
      "name": "rack_muro_este_sup",
      "position": [
        5.72,
        2.75,
        0.06
      ],
      "size": [
        1.35,
        0.46,
        1.95
      ],
      "yaw_rad": 1.5707963267948966
    },
    {
      "name": "rack_muro_este_med",
      "position": [
        5.72,
        0.75,
        0.06
      ],
      "size": [
        1.35,
        0.46,
        1.95
      ],
      "yaw_rad": 1.5707963267948966
    },
    {
      "name": "rack_oeste_centro",
      "position": [
        -4.05,
        0.15,
        0.06
      ],
      "size": [
        1.1,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_este_superior",
      "position": [
        2.6,
        2.8,
        0.06
      ],
      "size": [
        1.0,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_01",
      "position": [
        -1.75,
        -2.65,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_02",
      "position": [
        0.0,
        -2.65,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_03",
      "position": [
        1.75,
        -2.65,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_04",
      "position": [
        -1.75,
        -3.75,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_05",
      "position": [
        0.0,
        -3.75,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_sur_centro_06",
      "position": [
        1.75,
        -3.75,
        0.06
      ],
      "size": [
        1.25,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_este_bajo",
      "position": [
        3.0,
        -3.2,
        0.06
      ],
      "size": [
        1.0,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    },
    {
      "name": "rack_oeste_bajo",
      "position": [
        -2.9,
        -3.65,
        0.06
      ],
      "size": [
        0.9,
        0.46,
        1.95
      ],
      "yaw_rad": 0.0
    }
  ],
  "robots": [
    {
      "name": "Pioneer_01_ligero",
      "position": [
        -5.15,
        4.08,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "ligero"
    },
    {
      "name": "Pioneer_02_medio",
      "position": [
        -4.55,
        4.08,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "medio"
    },
    {
      "name": "Pioneer_03_alta_capacidad",
      "position": [
        -3.95,
        4.08,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "alta_capacidad"
    },
    {
      "name": "Pioneer_04_ligero",
      "position": [
        -5.15,
        3.48,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "ligero"
    },
    {
      "name": "Pioneer_05_medio",
      "position": [
        -4.55,
        3.48,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "medio"
    },
    {
      "name": "Pioneer_06_alta_capacidad",
      "position": [
        -3.95,
        3.48,
        0.18
      ],
      "heading_rad": -1.5707963267948966,
      "class": "alta_capacidad"
    }
  ],
  "loads": [
    {
      "name": "klt_a_01_3kg",
      "position": [
        -4.45,
        -1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 3.0,
      "required_agvs": 1,
      "zone": "A",
      "station": "pickup_a",
      "assigned_amr": "Pioneer_01_ligero",
      "phase_offset_s": 0.0,
      "workflow_load": true
    },
    {
      "name": "klt_a_02_5kg",
      "position": [
        -4.0,
        -1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 5.0,
      "required_agvs": 1,
      "zone": "A",
      "station": "pickup_a",
      "assigned_amr": "Pioneer_04_ligero",
      "phase_offset_s": 9.0,
      "workflow_load": true
    },
    {
      "name": "klt_a_03_2_5kg",
      "position": [
        -3.55,
        -1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 2.5,
      "required_agvs": 1,
      "zone": "A",
      "station": "pickup_a",
      "assigned_amr": "Pioneer_02_medio",
      "phase_offset_s": 18.0,
      "workflow_load": true
    },
    {
      "name": "klt_b_01_3kg",
      "position": [
        4.45,
        1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 3.0,
      "required_agvs": 1,
      "zone": "B",
      "station": "pickup_b",
      "assigned_amr": "Pioneer_03_alta_capacidad",
      "phase_offset_s": 4.5,
      "workflow_load": true
    },
    {
      "name": "klt_b_02_4kg",
      "position": [
        4.0,
        1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 4.0,
      "required_agvs": 1,
      "zone": "B",
      "station": "pickup_b",
      "assigned_amr": "Pioneer_05_medio",
      "phase_offset_s": 13.5,
      "workflow_load": true
    },
    {
      "name": "klt_b_03_5kg",
      "position": [
        3.55,
        1.78,
        0.84
      ],
      "size": [
        0.4,
        0.3,
        0.22
      ],
      "weight_kg": 5.0,
      "required_agvs": 1,
      "zone": "B",
      "station": "pickup_b",
      "assigned_amr": "Pioneer_06_alta_capacidad",
      "phase_offset_s": 22.5,
      "workflow_load": true
    }
  ],
  "central_obstacle": {
    "name": "obstaculo_central",
    "position": [
      0.0,
      1.25,
      0.35
    ],
    "size": [
      2.4,
      0.8,
      0.7
    ]
  },
  "routes": [
    {
      "name": "ruta_inicial_a_recogida_a",
      "points": [
        [
          -3.35,
          3.05
        ],
        [
          -3.0,
          2.5
        ],
        [
          -3.0,
          -1.35
        ],
        [
          -3.95,
          -1.05
        ]
      ]
    },
    {
      "name": "ruta_inicial_a_recogida_b",
      "points": [
        [
          -3.35,
          3.55
        ],
        [
          0.0,
          3.55
        ],
        [
          2.5,
          2.45
        ],
        [
          2.9,
          1.45
        ]
      ]
    },
    {
      "name": "ruta_a_interseccion",
      "points": [
        [
          -3.95,
          -1.05
        ],
        [
          -2.05,
          -0.55
        ],
        [
          0.0,
          -0.55
        ],
        [
          1.95,
          -0.55
        ]
      ]
    },
    {
      "name": "ruta_b_entrega_1",
      "points": [
        [
          4.0,
          2.35
        ],
        [
          4.0,
          2.85
        ],
        [
          4.25,
          3.25
        ]
      ]
    },
    {
      "name": "ruta_interseccion_entrega_2",
      "points": [
        [
          1.95,
          -0.55
        ],
        [
          3.0,
          -0.55
        ],
        [
          3.0,
          -2.3
        ],
        [
          4.45,
          -2.9
        ]
      ]
    },
    {
      "name": "ruta_retorno_recarga",
      "points": [
        [
          -2.05,
          -0.55
        ],
        [
          -3.0,
          -2.65
        ],
        [
          -3.4,
          -3.3
        ],
        [
          -4.55,
          -3.3
        ]
      ]
    }
  ],
  "stations": {
    "pickup_a": {
      "conveyor_position": [
        -4.05,
        -1.78,
        0.0
      ],
      "source_platform_position": [
        -4.55,
        -1.78,
        0.0
      ],
      "manipulator_position": [
        -4.65,
        -1.1,
        0.2
      ],
      "pick_position": [
        -4.2,
        -1.78,
        0.84
      ],
      "handoff_position": [
        -3.95,
        -1.05,
        0.48
      ]
    },
    "pickup_b": {
      "conveyor_position": [
        4.05,
        1.78,
        0.0
      ],
      "source_platform_position": [
        4.55,
        1.78,
        0.0
      ],
      "manipulator_position": [
        4.65,
        1.1,
        0.2
      ],
      "pick_position": [
        4.2,
        1.78,
        0.84
      ],
      "handoff_position": [
        3.95,
        1.05,
        0.48
      ]
    },
    "delivery_1_marker": [
      4.25,
      3.75,
      0.04
    ],
    "delivery_2_marker": [
      4.45,
      -3.55,
      0.04
    ],
    "recharge_marker": [
      -4.55,
      -3.95,
      0.04
    ],
    "footprints": {
      "conveyor": [
        1.55,
        0.55
      ],
      "manipulator": [
        0.65,
        0.65
      ]
    }
  },
  "metadata": {
    "communication": "local radio; heterogeneous transport requests by weight",
    "real_scale_assumptions": {
      "abb_irb_140": {
        "payload_kg": 6.0,
        "reach_m": 0.81
      },
      "pioneer_p3dx": {
        "length_m": 0.455,
        "width_m": 0.381,
        "height_m": 0.237,
        "payload_kg": 17.0
      },
      "klt_box": {
        "length_m": 0.4,
        "width_m": 0.3,
        "height_m": 0.22,
        "max_pick_mass_kg": 5.0
      }
    },
    "robot_classes": {
      "ligero": {
        "capacity_kg": 17,
        "radius_m": 0.27,
        "max_speed_mps": 1.0
      },
      "medio": {
        "capacity_kg": 17,
        "radius_m": 0.27,
        "max_speed_mps": 1.0
      },
      "alta_capacidad": {
        "capacity_kg": 17,
        "radius_m": 0.27,
        "max_speed_mps": 0.8
      }
    },
    "narrow_corridor_width_m": 1.0,
    "standard_corridor_width_m": 1.5,
    "base_scene_policy": "AWS /warehouse is loaded as provenance but hidden and made non-collidable; the MRBO overlay provides the visible AWS-like warehouse finish on the canonical layout.",
    "visual_quality": "restrained industrial palette, procedural concrete panels, lane markings, detailed rack frames, KLT totes, real CoppeliaSim conveyor models, safety hardware and animated pick-handoff-transport demo script"
  },
  "animation": {
    "cycle_s": 36.0,
    "box_cycle_s": 27.0,
    "manipulator_cycle_s": 9.0,
    "robots": {
      "Pioneer_01_ligero": [
        [
          -5.15,
          4.08,
          0.18
        ],
        [
          -3.35,
          3.05,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -1.2,
          -0.55,
          0.18
        ],
        [
          3.2,
          -0.55,
          0.18
        ],
        [
          4.45,
          -3.0,
          0.18
        ],
        [
          4.45,
          -3.55,
          0.18
        ]
      ],
      "Pioneer_02_medio": [
        [
          -4.55,
          4.08,
          0.18
        ],
        [
          -3.0,
          2.5,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -0.35,
          -0.55,
          0.18
        ],
        [
          3.0,
          -0.55,
          0.18
        ],
        [
          4.25,
          3.25,
          0.18
        ],
        [
          4.25,
          3.75,
          0.18
        ]
      ],
      "Pioneer_03_alta_capacidad": [
        [
          -3.95,
          4.08,
          0.18
        ],
        [
          0.0,
          3.55,
          0.18
        ],
        [
          2.5,
          2.45,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          4.0,
          2.35,
          0.18
        ],
        [
          4.25,
          3.75,
          0.18
        ]
      ],
      "Pioneer_04_ligero": [
        [
          -5.15,
          3.48,
          0.18
        ],
        [
          -3.0,
          2.2,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -3.95,
          -1.05,
          0.18
        ],
        [
          -3.0,
          -2.65,
          0.18
        ],
        [
          -4.55,
          -3.3,
          0.18
        ],
        [
          -4.55,
          -3.95,
          0.18
        ]
      ],
      "Pioneer_05_medio": [
        [
          -4.55,
          3.48,
          0.18
        ],
        [
          -3.35,
          3.55,
          0.18
        ],
        [
          0.0,
          3.55,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          4.15,
          1.45,
          0.18
        ]
      ],
      "Pioneer_06_alta_capacidad": [
        [
          -3.95,
          3.48,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          3.95,
          1.05,
          0.18
        ],
        [
          0.0,
          -0.55,
          0.18
        ],
        [
          1.95,
          -0.55,
          0.18
        ],
        [
          4.45,
          -3.55,
          0.18
        ]
      ]
    },
    "manipulators": [
      "zona_recogida_a_manipulador_model",
      "zona_recogida_b_manipulador_model"
    ]
  }
}]==])
configureRendering()
prepareAwsReference()
setAlias(sim.createDummy(0.05), 'MRBO_AWS_CANONICAL_OVERLAY')

box('canonical_concrete_floor_12x10', {12.0, 10.0, 0.05}, {0, 0, -0.025}, {0.42, 0.43, 0.42}, 0, true, true)
for ix = 0, 11 do
    for iy = 0, 9 do
        local shade = 0.44 + 0.018 * (((ix * 17 + iy * 11) % 5) - 2)
        box('floor_concrete_panel_' .. ix .. '_' .. iy, {0.96, 0.96, 0.010}, {-5.5 + ix, -4.5 + iy, 0.006}, {shade, shade + 0.008, shade + 0.010}, 0, true, false)
    end
end
for i = -5, 5 do box('floor_tile_seam_x_' .. i, {0.018, 10.0, 0.012}, {i, 0, 0.012}, {0.30, 0.31, 0.31}, 0, true, false) end
for i = -4, 4 do box('floor_tile_seam_y_' .. i, {12.0, 0.018, 0.012}, {0, i, 0.014}, {0.30, 0.31, 0.31}, 0, true, false) end
box('aisle_main_lane_yellow_left', {9.8, 0.045, 0.018}, {0, -0.95, 0.035}, {0.92, 0.78, 0.18}, 0, true, false)
box('aisle_main_lane_yellow_right', {9.8, 0.045, 0.018}, {0, 0.95, 0.035}, {0.92, 0.78, 0.18}, 0, true, false)
box('aisle_cross_lane_yellow_north', {0.045, 6.2, 0.018}, {-3.0, 1.55, 0.035}, {0.92, 0.78, 0.18}, 0, true, false)
box('aisle_cross_lane_yellow_south', {0.045, 6.2, 0.018}, {3.0, -1.55, 0.035}, {0.92, 0.78, 0.18}, 0, true, false)
box('canonical_wall_north', {12.25, 0.12, 1.24}, {0, 5.06, 0.62}, {0.62, 0.64, 0.64}, 0, true, true)
box('canonical_wall_south', {12.25, 0.12, 1.24}, {0, -5.06, 0.62}, {0.62, 0.64, 0.64}, 0, true, true)
box('canonical_wall_east', {0.12, 10.25, 1.24}, {6.06, 0, 0.62}, {0.62, 0.64, 0.64}, 0, true, true)
box('canonical_wall_west', {0.12, 10.25, 1.24}, {-6.06, 0, 0.62}, {0.62, 0.64, 0.64}, 0, true, true)
for idx, x in ipairs({-3.5, 0.0, 3.5}) do
    box('dock_door_north_' .. idx, {1.35, 0.035, 0.82}, {x, 4.988, 0.48}, {0.18, 0.22, 0.24}, 0, true, false)
    box('dock_header_north_' .. idx, {1.47, 0.045, 0.08}, {x, 4.970, 0.93}, {0.88, 0.55, 0.12}, 0, true, false)
end
for idx, y in ipairs({-3.0, 0.0, 3.0}) do
    box('east_service_panel_' .. idx, {0.035, 1.15, 0.70}, {5.988, y, 0.55}, {0.18, 0.22, 0.24}, 0, true, false)
end
for _, p in ipairs({{-3.6, -3.0}, {0, -3.0}, {3.6, -3.0}, {-3.6, 1.2}, {0, 1.2}, {3.6, 1.2}}) do
    box('overhead_light_panel_' .. tostring(_), {1.05, 0.26, 0.035}, {p[1], p[2], 2.85}, {0.96, 0.96, 0.82}, 0, true, false)
end
box('canonical_12m_frame_north', {12.0, 0.05, 0.08}, {0, 5.0, 0.08}, {0.08, 0.08, 0.08}, 0, true, true)
box('canonical_12m_frame_south', {12.0, 0.05, 0.08}, {0, -5.0, 0.08}, {0.08, 0.08, 0.08}, 0, true, true)
box('canonical_10m_frame_east', {0.05, 10.0, 0.08}, {6.0, 0, 0.08}, {0.08, 0.08, 0.08}, 0, true, true)
box('canonical_10m_frame_west', {0.05, 10.0, 0.08}, {-6.0, 0, 0.08}, {0.08, 0.08, 0.08}, 0, true, true)

for _, z in ipairs(scene.zones) do zone(z) end
for _, r in ipairs(scene.racks) do rackBlock(r) end
box(scene.central_obstacle.name, scene.central_obstacle.size, scene.central_obstacle.position, {0.44, 0.44, 0.44}, 0, true, true)
safetyHardware()

for label, station in pairs({a = scene.stations.pickup_a, b = scene.stations.pickup_b}) do
    local px, py = station.conveyor_position[1], station.conveyor_position[2]
    local sx, sy = station.source_platform_position[1], station.source_platform_position[2]
    local hx, hy, hz = station.handoff_position[1], station.handoff_position[2], station.handoff_position[3]
    box('zona_recogida_' .. label .. '_source_table', {0.72, 0.52, 0.78}, {sx, sy, 0.39}, {0.20, 0.22, 0.22}, 0, true, true)
    box('zona_recogida_' .. label .. '_source_table_top', {0.76, 0.56, 0.055}, {sx, sy, 0.79}, {0.66, 0.67, 0.64}, 0, true, true)
    box('zona_recogida_' .. label .. '_handoff_table', {0.62, 0.52, math.max(hz, 0.08)}, {hx, hy, hz / 2}, {0.18, 0.21, 0.23}, 0, true, true)
    box('zona_recogida_' .. label .. '_handoff_table_top', {0.66, 0.56, 0.05}, {hx, hy, hz + 0.025}, {0.62, 0.64, 0.62}, 0, true, true)
    box('zona_recogida_' .. label .. '_conveyor_guard_left', {1.48, 0.035, 0.26}, {px, py - 0.31, 0.50}, {0.92, 0.70, 0.10}, 0, true, false)
    box('zona_recogida_' .. label .. '_conveyor_guard_right', {1.48, 0.035, 0.26}, {px, py + 0.31, 0.50}, {0.92, 0.70, 0.10}, 0, true, false)
    local mx, my = station.manipulator_position[1], station.manipulator_position[2]
    box('zona_recogida_' .. label .. '_robot_pedestal', {0.68, 0.68, 0.20}, {mx, my, 0.10}, {0.18, 0.20, 0.22}, 0, true, true)
end
conveyor('zona_recogida_a_conveyor_model', scene.stations.pickup_a.conveyor_position, 0)
conveyor('zona_recogida_b_conveyor_model', scene.stations.pickup_b.conveyor_position, 0)
modelOrFallback(scene.model_paths.manipulator, 'zona_recogida_a_manipulador_model', scene.stations.pickup_a.manipulator_position, 0, {0.35, 0.35, 0.12}, {0.95, 0.65, 0.05})
modelOrFallback(scene.model_paths.manipulator, 'zona_recogida_b_manipulador_model', scene.stations.pickup_b.manipulator_position, math.pi, {0.35, 0.35, 0.12}, {0.95, 0.65, 0.05})
box('zona_entrega_1_plataforma_verde', {0.72, 0.52, 0.08}, scene.stations.delivery_1_marker, {0.08, 0.62, 0.28}, 0, true, true)
box('zona_entrega_2_plataforma_verde', {0.72, 0.52, 0.08}, scene.stations.delivery_2_marker, {0.08, 0.62, 0.28}, 0, true, true)
box('zona_recarga_pad_rojo', {0.80, 0.62, 0.08}, scene.stations.recharge_marker, {0.90, 0.12, 0.08}, 0, true, true)

for _, load in ipairs(scene.loads) do
    local color = {0.62, 0.64, 0.60}
    if load.station == 'pickup_a' then color = {0.55, 0.61, 0.64} end
    if load.station == 'pickup_b' then color = {0.60, 0.60, 0.54} end
    local h = box(load.name, load.size, load.position, color, 0, true, false, math.max(load.weight_kg, 0.001))
    local sx, sy, sz = load.size[1], load.size[2], load.size[3]
    for idx, dy in ipairs({-sy / 2 - 0.006, sy / 2 + 0.006}) do
        local detail = box(load.name .. '_handle_' .. idx, {sx * 0.42, 0.010, sz * 0.28}, {load.position[1], load.position[2] + dy, load.position[3] + 0.02}, {0.08, 0.09, 0.09}, 0, true, false)
        pcall(sim.setObjectParent, detail, h, true)
    end
    local label = box(load.name .. '_label', {0.010, sy * 0.46, sz * 0.34}, {load.position[1] + sx / 2 + 0.006, load.position[2], load.position[3] + 0.02}, {0.92, 0.92, 0.84}, 0, true, false)
    pcall(sim.setObjectParent, label, h, true)
    local marker = sim.createDummy(0.06)
    setAlias(marker, load.name .. '_requires_' .. load.required_agvs .. '_agv')
    sim.setObjectPosition(marker, -1, {load.position[1], load.position[2], load.position[3] + load.size[3] / 2 + 0.08})
    pcall(sim.setObjectParent, marker, h, true)
end
for _, r in ipairs(scene.routes) do route(r.name, r.points) end
for _, robot in ipairs(scene.robots) do
    local ok, handle = pcall(sim.loadModel, scene.model_paths.pioneer_p3dx)
    if ok and handle and handle >= 0 then
        disableModelScripts(handle)
        makeModelVisualOnly(handle)
    else
        handle = cylinder(robot.name .. '_fallback_base', 0.28, 0.30, robot.position, {0.12, 0.12, 0.12})
    end
    setAlias(handle, robot.name)
    sim.setObjectPosition(handle, -1, robot.position)
    sim.setObjectOrientation(handle, -1, {0, 0, robot.heading_rad})
    local marker = cylinder(robot.name .. '_tipo_' .. robot.class, 0.12, 0.035, {robot.position[1], robot.position[2], robot.position[3] + 0.22}, {0.92, 0.72, 0.05})
    pcall(sim.setObjectParent, marker, handle, true)
    local comm = sim.createDummy(0.08)
    setAlias(comm, robot.name .. '_radio_local_R')
    sim.setObjectPosition(comm, -1, {robot.position[1], robot.position[2], robot.position[3] + 0.34})
    pcall(sim.setObjectParent, comm, handle, true)
end

local top = sim.createVisionSensor(1 + 4, {1280, 960, 0, 0}, {0.05, 40.0, 11.2, 0.5, 0.0, 0.0, 0.88, 0.90, 0.93, 0.0, 0.0})
setAlias(top, 'MRBO_camera_top_canonical')
sim.setExplicitHandling(top, 1)
sim.setObjectInt32Param(top, sim.visionintparam_perspective_operation, 0)
sim.setObjectFloatParam(top, sim.visionfloatparam_ortho_size, 11.0)
sim.setObjectPosition(top, -1, {0.0, 0.0, 12.5})
sim.setObjectOrientation(top, -1, {0.0, math.pi, 0.0})
local oblique = sim.createVisionSensor(1 + 4, {1280, 960, 0, 0}, {0.05, 40.0, math.rad(86), 0.5, 0.0, 0.0, 0.88, 0.90, 0.93, 0.0, 0.0})
setAlias(oblique, 'MRBO_camera_oblique_canonical')
sim.setExplicitHandling(oblique, 1)
sim.setObjectPosition(oblique, -1, {0.0, 0.0, 12.4})
sim.setObjectOrientation(oblique, -1, {0.0, math.pi, 0.0})
installDemoScript()
sim.addLog(sim.verbosity_scriptinfos, 'MRBO AWS canonical cooperative transport scene generated with visible AWS reference, stable physics and embedded motion.')
