-- Auto-generated by scripts/coppelia/build_sp0_corners_scene.py
-- Scenario: sp0_corners_drop_suction_pioneer
-- Usage:
--   1. Open CoppeliaSim.
--   2. Run: dofile([[C:\Users\walla\Documents\Github\VIU-MRBO-TFM-2026\coppeliasim\real_scenes\sp0_corners_drop_suction_pioneer.lua]])

local scene = {
scenario = "sp0_corners_drop_suction_pioneer",
description = "SP0 CoppeliaSim scene: corner loads, eight Pioneer AMRs, three target unload zones and dispatch policy comparison.",
dimensions_m = {
width = 10.5,
depth = 10.5
},
model_paths = {
pioneer_p3dx = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\mobile\\pioneer p3dx.ttm"
},
zones = {{
name = "carga_robot_01",
kind = "charge",
center = {-4.35, -4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_02",
kind = "charge",
center = {-3.55, -4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_03",
kind = "charge",
center = {-4.35, -3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_04",
kind = "charge",
center = {-3.55, -3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_05",
kind = "charge",
center = {4.35, 4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_06",
kind = "charge",
center = {3.55, 4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_07",
kind = "charge",
center = {4.35, 3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_08",
kind = "charge",
center = {3.55, 3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "caida_cajas_nw",
kind = "drop",
center = {-4.05, 3.75, 0.02},
size = {1.38, 1.38, 0.02},
color = {0.88, 0.64, 0.12}
}, {
name = "caida_cajas_se",
kind = "drop",
center = {4.05, -3.75, 0.02},
size = {1.38, 1.38, 0.02},
color = {0.88, 0.64, 0.12}
}, {
name = "target_descarga_oeste",
kind = "unload",
center = {-1.8, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}, {
name = "target_descarga_centro",
kind = "unload",
center = {0.0, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}, {
name = "target_descarga_este",
kind = "unload",
center = {1.8, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}},
targets = {"target_descarga_oeste", "target_descarga_centro", "target_descarga_este"},
assignment_policy = "hungarian_centralized",
benchmark_policies = {"hungarian_centralized", "distributed_greedy", "replicator_distributed"},
robots = {{
name = "SP0_Pioneer_01",
base = "carga_robot_01",
drop = "caida_cajas_nw",
release_delay_s = 0.0,
position = {-4.35, -4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 100.0
}, {
name = "SP0_Pioneer_02",
base = "carga_robot_02",
drop = "caida_cajas_se",
release_delay_s = 0.4,
position = {-3.55, -4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 92.0
}, {
name = "SP0_Pioneer_03",
base = "carga_robot_03",
drop = "caida_cajas_nw",
release_delay_s = 0.8,
position = {-4.35, -3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 84.0
}, {
name = "SP0_Pioneer_04",
base = "carga_robot_04",
drop = "caida_cajas_se",
release_delay_s = 1.2,
position = {-3.55, -3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 76.0
}, {
name = "SP0_Pioneer_05",
base = "carga_robot_05",
drop = "caida_cajas_se",
release_delay_s = 0.0,
position = {4.35, 4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 88.0
}, {
name = "SP0_Pioneer_06",
base = "carga_robot_06",
drop = "caida_cajas_nw",
release_delay_s = 0.4,
position = {3.55, 4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 80.0
}, {
name = "SP0_Pioneer_07",
base = "carga_robot_07",
drop = "caida_cajas_se",
release_delay_s = 0.8,
position = {4.35, 3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 68.0
}, {
name = "SP0_Pioneer_08",
base = "carga_robot_08",
drop = "caida_cajas_nw",
release_delay_s = 1.2,
position = {3.55, 3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 60.0
}},
boxes = {{
name = "SP0_box_NW_01",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {-0.32, -0.28},
target = "target_descarga_oeste"
}, {
name = "SP0_box_NW_02",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {0.32, -0.28},
target = "target_descarga_centro"
}, {
name = "SP0_box_NW_03",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {0.0, 0.3},
target = "target_descarga_este"
}, {
name = "SP0_box_SE_01",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {-0.32, -0.28},
target = "target_descarga_centro"
}, {
name = "SP0_box_SE_02",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {0.32, -0.28},
target = "target_descarga_este"
}, {
name = "SP0_box_SE_03",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {0.0, 0.3},
target = "target_descarga_oeste"
}},
box_size_m = {0.36, 0.28, 0.18},
drop_height_m = 1.55,
carry_height_m = 0.42,
suction_height_m = 3.2,
amr = {
max_speed_mps = 0.55,
sim_speed_multiplier = 2.0,
arrival_radius_m = 0.2,
drop_alignment_radius_m = 0.07,
avoidance_radius_m = 1.05,
hard_clearance_m = 0.62,
footprint_radius_m = 0.46,
sensor_radius_m = 0.95,
comm_radius_m = 1.65,
sensor_fill_alpha = 0.7,
battery_low_pct = 28.0,
battery_resume_pct = 86.0,
battery_move_drain_pct_per_m = 2.2,
battery_load_extra_pct_per_m = 0.9,
battery_idle_drain_pct_per_s = 0.015,
battery_charge_pct_per_s = 7.5,
box_respawn_s = 2.0
},
metadata = {
purpose = "SP0 physical smoke scene for spawn/drop, carry, unload count.",
corner_policy = "Individual charge pads in SW/NE; crossed drop zones in NW/SE; three central target unload zones.",
physics_policy = "AMRs are kinematic with collidable safety footprints and local reactive collision avoidance."
}
}

local function setAlias(handle, name)
    if handle and handle >= 0 then pcall(sim.setObjectAlias, handle, name, 1) end
    return handle
end

local function setPhysics(handle, static, respondable, mass)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_static, static and 1 or 0)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_respondable, respondable and 1 or 0)
    pcall(sim.setObjectFloatParam, handle, sim.shapefloatparam_mass, mass or 0.001)
    pcall(sim.setObjectInt32Param, handle, sim.shapeintparam_edge_visibility, 1)
end

local function setAlpha(handle, alpha)
    local transparency = 1.0 - math.max(0.0, math.min(1.0, alpha or 1.0))
    if sim.colorcomponent_transparency then
        pcall(sim.setShapeColor, handle, nil, sim.colorcomponent_transparency, {transparency})
    end
    if sim.shapefloatparam_transparency then
        pcall(sim.setObjectFloatParam, handle, sim.shapefloatparam_transparency, transparency)
    end
end

local function box(name, size, pos, color, yaw, static, respondable, mass)
    local h = sim.createPrimitiveShape(sim.primitiveshape_cuboid, size, 0)
    setAlias(h, name)
    sim.setObjectPosition(h, -1, pos)
    sim.setObjectOrientation(h, -1, {0, 0, yaw or 0})
    sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color)
    setPhysics(h, static ~= false, respondable ~= false, mass or 0.001)
    return h
end

local function cylinder(name, radius, height, pos, color, static, respondable, mass, alpha)
    local h = sim.createPrimitiveShape(sim.primitiveshape_cylinder, {radius * 2, radius * 2, height}, 0)
    setAlias(h, name)
    sim.setObjectPosition(h, -1, pos)
    sim.setShapeColor(h, nil, sim.colorcomponent_ambient_diffuse, color)
    setAlpha(h, alpha or 1.0)
    setPhysics(h, static ~= false, respondable == true, mass or 0.001)
    return h
end

local function clamp(value, low, high)
    if value < low then return low end
    if value > high then return high end
    return value
end

local function batteryColor(batteryPct)
    local step = math.floor(clamp(batteryPct, 0.0, 100.0) / 100.0 * 9.0 + 0.5) + 1
    local t = (step - 1) / 9.0
    return {
        0.90 * (1.0 - t) + 0.12 * t,
        0.10 * (1.0 - t) + 0.88 * t,
        0.08 * (1.0 - t) + 0.16 * t
    }
end

local function addRingSegments(prefix, center, radius, segmentCount, color)
    local handles = {}
    local arc = math.max(0.16, (2.0 * math.pi * radius / segmentCount) * 0.58)
    for i = 1, segmentCount do
        local theta = (2.0 * math.pi * (i - 1)) / segmentCount
        local x = center[1] + math.cos(theta) * radius
        local y = center[2] + math.sin(theta) * radius
        handles[#handles + 1] = box(string.format('%s_%02d', prefix, i), {arc, 0.025, 0.018}, {x, y, center[3]}, color, theta + math.pi / 2.0, true, false)
    end
    return handles
end

local function disableModelScripts(handle)
    local scriptTypes = {sim.scripttype_simulation, sim.scripttype_customization, sim.scripttype_childscript, sim.scripttype_customizationscript}
    for _, obj in ipairs(sim.getObjectsInTree(handle, sim.handle_all, 0)) do
        for _, scriptType in ipairs(scriptTypes) do
            if scriptType then
                local ok, script = pcall(sim.getScript, scriptType, obj)
                if ok and script and script >= 0 then pcall(sim.removeObjects, {script}) end
            end
        end
    end
end

local function makeModelVisualOnly(handle)
    for _, child in ipairs(sim.getObjectsInTree(handle, sim.handle_all, 0)) do
        if sim.getObjectType(child) == sim.object_shape_type then
            pcall(sim.setObjectInt32Param, child, sim.shapeintparam_static, 1)
            pcall(sim.setObjectInt32Param, child, sim.shapeintparam_respondable, 0)
        end
    end
end

local function addPioneer(spec)
    local ok, handle = pcall(sim.loadModel, scene.model_paths.pioneer_p3dx)
    if ok and handle and handle >= 0 then
        disableModelScripts(handle)
        makeModelVisualOnly(handle)
    else
        handle = cylinder(spec.name .. '_fallback', 0.26, 0.25, spec.position, {0.12, 0.12, 0.12})
    end
    setAlias(handle, spec.name)
    sim.setObjectPosition(handle, -1, spec.position)
    sim.setObjectOrientation(handle, -1, {0, 0, spec.heading_rad})
    local plate = box(spec.name .. '_cargo_plate', {0.40, 0.32, 0.035}, {spec.position[1], spec.position[2], spec.position[3] + 0.30}, {0.08, 0.12, 0.16}, 0, true, false)
    pcall(sim.setObjectParent, plate, handle, true)
    local footprint = cylinder(spec.name .. '_safety_footprint', 0.46, 0.012, {spec.position[1], spec.position[2], 0.035}, {0.08, 0.50, 0.88}, true, true, 0.1)
    pcall(sim.setObjectParent, footprint, handle, true)
    local ringColor = batteryColor(spec.battery_initial_pct or 100.0)
    local sensorFill = cylinder(spec.name .. '_sensor_fill', scene.amr.sensor_radius_m, 0.006, {spec.position[1], spec.position[2], 0.044}, ringColor, true, false, 0.001, scene.amr.sensor_fill_alpha or 0.70)
    pcall(sim.setObjectParent, sensorFill, handle, true)
    local sensorRing = addRingSegments(spec.name .. '_sensor_radius', {spec.position[1], spec.position[2], 0.052}, scene.amr.sensor_radius_m, 24, ringColor)
    for _, ring in ipairs(sensorRing) do pcall(sim.setObjectParent, ring, handle, true) end
    local commRing = addRingSegments(spec.name .. '_comm_radius', {spec.position[1], spec.position[2], 0.072}, scene.amr.comm_radius_m, 24, ringColor)
    for _, ring in ipairs(commRing) do pcall(sim.setObjectParent, ring, handle, true) end
end

local function clearScene()
    local ok, didCreateNew = pcall(function()
        if sim.newScene then
            sim.newScene()
            return true
        end
        if sim.createNewScene then
            sim.createNewScene()
            return true
        end
        return false
    end)
    if ok and didCreateNew then return end
    local objects = sim.getObjectsInTree(sim.handle_scene, sim.handle_all, 0)
    local removable = {}
    for _, object in ipairs(objects) do
        local okType, objectType = pcall(sim.getObjectType, object)
        if not (okType and (objectType == sim.object_camera_type or objectType == sim.object_light_type)) then
            removable[#removable + 1] = object
        end
    end
    if #removable > 0 then sim.removeObjects(removable) end
end

clearScene()
setAlias(sim.createDummy(0.04), 'SP0_CORNERS_DROP_SUCTION_ROOT')
local floorW = scene.dimensions_m.width
local floorD = scene.dimensions_m.depth
box('SP0_floor', {floorW, floorD, 0.05}, {0, 0, -0.025}, {0.46, 0.47, 0.46}, 0, true, true)
box('SP0_boundary_north', {floorW, 0.045, 0.08}, {0, floorD / 2, 0.04}, {0.08, 0.08, 0.08}, 0, true, true)
box('SP0_boundary_south', {floorW, 0.045, 0.08}, {0, -floorD / 2, 0.04}, {0.08, 0.08, 0.08}, 0, true, true)
box('SP0_boundary_east', {0.045, floorD, 0.08}, {floorW / 2, 0, 0.04}, {0.08, 0.08, 0.08}, 0, true, true)
box('SP0_boundary_west', {0.045, floorD, 0.08}, {-floorW / 2, 0, 0.04}, {0.08, 0.08, 0.08}, 0, true, true)

for _, z in ipairs(scene.zones) do
    local x, y, zz = z.center[1], z.center[2], z.center[3]
    local sx, sy, sz = z.size[1], z.size[2], z.size[3]
    box(z.name .. '_pad', z.size, z.center, z.color, 0, true, false)
    box(z.name .. '_north', {sx, 0.035, 0.035}, {x, y + sy / 2, zz + 0.012}, z.color, 0, true, false)
    box(z.name .. '_south', {sx, 0.035, 0.035}, {x, y - sy / 2, zz + 0.012}, z.color, 0, true, false)
    box(z.name .. '_east', {0.035, sy, 0.035}, {x + sx / 2, y, zz + 0.012}, z.color, 0, true, false)
    box(z.name .. '_west', {0.035, sy, 0.035}, {x - sx / 2, y, zz + 0.012}, z.color, 0, true, false)
    if z.kind == 'drop' then
        for idx, p in ipairs({{-0.35, -0.35}, {-0.35, 0.35}, {0.35, -0.35}, {0.35, 0.35}}) do
            box(z.name .. '_chute_post_' .. idx, {0.055, 0.055, scene.drop_height_m}, {x + p[1], y + p[2], scene.drop_height_m / 2}, {0.12, 0.12, 0.11}, 0, true, false)
        end
        box(z.name .. '_chute_top', {0.82, 0.82, 0.12}, {x, y, scene.drop_height_m + 0.08}, {0.90, 0.63, 0.08}, 0, true, false)
    elseif z.kind == 'unload' then
        cylinder(z.name .. '_suction_pipe', 0.16, 1.55, {x, y, 2.50}, {0.20, 0.62, 0.88}, true, false)
        cylinder(z.name .. '_suction_beacon', 0.28, 0.16, {x, y, 3.36}, {0.32, 0.80, 1.00}, true, false)
        for idx, radius in ipairs({0.38, 0.52, 0.66}) do
            cylinder(string.format('%s_suction_ring_%d', z.name, idx), radius, 0.025, {x, y, 0.16 + idx * 0.16}, {0.16, 0.68, 0.36}, true, false)
        end
    end
end

box('SP0_counter_panel', {3.0, 0.10, 1.0}, {0.0, -4.35, 0.55}, {0.12, 0.13, 0.14}, 0, true, false)
for i = 1, 48 do
    local col = (i - 1) % 12
    local row = math.floor((i - 1) / 12)
    box(string.format('SP0_count_tick_%02d', i), {0.16, 0.035, 0.16}, {-1.32 + col * 0.24, -4.42, 0.25 + row * 0.26}, {0.22, 0.24, 0.25}, 0, true, false)
end

for _, r in ipairs(scene.robots) do addPioneer(r) end
local zoneMap = {}
for _, z in ipairs(scene.zones) do zoneMap[z.name] = z end
for _, b in ipairs(scene.boxes) do
    local z = zoneMap[b.drop]
    local offset = b.slot_offset or {0.0, 0.0}
    local px = z.center[1] + offset[1]
    local py = z.center[2] + offset[2]
    local h = box(b.name, b.size, {px, py, scene.drop_height_m + b.size[3]}, {0.68, 0.50, 0.28}, 0, true, false, b.mass_kg)
    local label = box(b.name .. '_label', {0.18, 0.012, 0.08}, {px, py, scene.drop_height_m + b.size[3] + 0.02}, {0.90, 0.90, 0.80}, 0, true, false)
    pcall(sim.setObjectParent, label, h, true)
end

local ortho = math.max(scene.dimensions_m.width, scene.dimensions_m.depth) + 1.8
local top = sim.createVisionSensor(1 + 4, {1280, 960, 0, 0}, {0.05, 40.0, ortho, 0.5, 0.0, 0.0, 0.88, 0.90, 0.93, 0.0, 0.0})
setAlias(top, 'SP0_camera_top')
sim.setExplicitHandling(top, 1)
pcall(sim.setObjectInt32Param, top, sim.visionintparam_perspective_operation, 0)
pcall(sim.setObjectFloatParam, top, sim.visionfloatparam_ortho_size, ortho)
sim.setObjectPosition(top, -1, {0, 0, 12.5})
sim.setObjectOrientation(top, -1, {0, math.pi, 0})
pcall(function()
    local cameras = sim.getObjectsInTree(sim.handle_scene, sim.object_camera_type, 0)
    local camera = cameras[1]
    setAlias(camera, 'DefaultCamera')
    pcall(sim.cameraFitToView, camera + sim.handleflag_camera, nil, 0, 1.20)
    pcall(sim.adjustView, 0, camera, 0, 'SP0 default view')
    pcall(sim.cameraFitToView, 0, nil, 0, 1.20)
end)
pcall(function()
    local lights = sim.getObjectsInTree(sim.handle_scene, sim.object_light_type, 0)
    local light = lights[1]
    setAlias(light, 'DefaultLight')
    sim.setObjectPosition(light, -1, {1.5, -2.5, 7.0})
end)

local scriptText = [==[-- SP0 AMR controller: dispatch policies, battery return and local avoidance.
local sim = require('sim')
local scene = {
scenario = "sp0_corners_drop_suction_pioneer",
description = "SP0 CoppeliaSim scene: corner loads, eight Pioneer AMRs, three target unload zones and dispatch policy comparison.",
dimensions_m = {
width = 10.5,
depth = 10.5
},
model_paths = {
pioneer_p3dx = "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\mobile\\pioneer p3dx.ttm"
},
zones = {{
name = "carga_robot_01",
kind = "charge",
center = {-4.35, -4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_02",
kind = "charge",
center = {-3.55, -4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_03",
kind = "charge",
center = {-4.35, -3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_04",
kind = "charge",
center = {-3.55, -3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_05",
kind = "charge",
center = {4.35, 4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_06",
kind = "charge",
center = {3.55, 4.2, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_07",
kind = "charge",
center = {4.35, 3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "carga_robot_08",
kind = "charge",
center = {3.55, 3.4, 0.02},
size = {0.62, 0.62, 0.02},
color = {0.16, 0.34, 0.58}
}, {
name = "caida_cajas_nw",
kind = "drop",
center = {-4.05, 3.75, 0.02},
size = {1.38, 1.38, 0.02},
color = {0.88, 0.64, 0.12}
}, {
name = "caida_cajas_se",
kind = "drop",
center = {4.05, -3.75, 0.02},
size = {1.38, 1.38, 0.02},
color = {0.88, 0.64, 0.12}
}, {
name = "target_descarga_oeste",
kind = "unload",
center = {-1.8, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}, {
name = "target_descarga_centro",
kind = "unload",
center = {0.0, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}, {
name = "target_descarga_este",
kind = "unload",
center = {1.8, 0.0, 0.02},
size = {1.05, 1.05, 0.02},
color = {0.14, 0.55, 0.32}
}},
targets = {"target_descarga_oeste", "target_descarga_centro", "target_descarga_este"},
assignment_policy = "hungarian_centralized",
benchmark_policies = {"hungarian_centralized", "distributed_greedy", "replicator_distributed"},
robots = {{
name = "SP0_Pioneer_01",
base = "carga_robot_01",
drop = "caida_cajas_nw",
release_delay_s = 0.0,
position = {-4.35, -4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 100.0
}, {
name = "SP0_Pioneer_02",
base = "carga_robot_02",
drop = "caida_cajas_se",
release_delay_s = 0.4,
position = {-3.55, -4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 92.0
}, {
name = "SP0_Pioneer_03",
base = "carga_robot_03",
drop = "caida_cajas_nw",
release_delay_s = 0.8,
position = {-4.35, -3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 84.0
}, {
name = "SP0_Pioneer_04",
base = "carga_robot_04",
drop = "caida_cajas_se",
release_delay_s = 1.2,
position = {-3.55, -3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 76.0
}, {
name = "SP0_Pioneer_05",
base = "carga_robot_05",
drop = "caida_cajas_se",
release_delay_s = 0.0,
position = {4.35, 4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 88.0
}, {
name = "SP0_Pioneer_06",
base = "carga_robot_06",
drop = "caida_cajas_nw",
release_delay_s = 0.4,
position = {3.55, 4.2, 0.18},
heading_rad = 0.0,
battery_initial_pct = 80.0
}, {
name = "SP0_Pioneer_07",
base = "carga_robot_07",
drop = "caida_cajas_se",
release_delay_s = 0.8,
position = {4.35, 3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 68.0
}, {
name = "SP0_Pioneer_08",
base = "carga_robot_08",
drop = "caida_cajas_nw",
release_delay_s = 1.2,
position = {3.55, 3.4, 0.18},
heading_rad = 0.0,
battery_initial_pct = 60.0
}},
boxes = {{
name = "SP0_box_NW_01",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {-0.32, -0.28},
target = "target_descarga_oeste"
}, {
name = "SP0_box_NW_02",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {0.32, -0.28},
target = "target_descarga_centro"
}, {
name = "SP0_box_NW_03",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_nw",
slot_offset = {0.0, 0.3},
target = "target_descarga_este"
}, {
name = "SP0_box_SE_01",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {-0.32, -0.28},
target = "target_descarga_centro"
}, {
name = "SP0_box_SE_02",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {0.32, -0.28},
target = "target_descarga_este"
}, {
name = "SP0_box_SE_03",
size = {0.36, 0.28, 0.18},
mass_kg = 2.0,
drop = "caida_cajas_se",
slot_offset = {0.0, 0.3},
target = "target_descarga_oeste"
}},
box_size_m = {0.36, 0.28, 0.18},
drop_height_m = 1.55,
carry_height_m = 0.42,
suction_height_m = 3.2,
amr = {
max_speed_mps = 0.55,
sim_speed_multiplier = 2.0,
arrival_radius_m = 0.2,
drop_alignment_radius_m = 0.07,
avoidance_radius_m = 1.05,
hard_clearance_m = 0.62,
footprint_radius_m = 0.46,
sensor_radius_m = 0.95,
comm_radius_m = 1.65,
sensor_fill_alpha = 0.7,
battery_low_pct = 28.0,
battery_resume_pct = 86.0,
battery_move_drain_pct_per_m = 2.2,
battery_load_extra_pct_per_m = 0.9,
battery_idle_drain_pct_per_s = 0.015,
battery_charge_pct_per_s = 7.5,
box_respawn_s = 2.0
},
metadata = {
purpose = "SP0 physical smoke scene for spawn/drop, carry, unload count.",
corner_policy = "Individual charge pads in SW/NE; crossed drop zones in NW/SE; three central target unload zones.",
physics_policy = "AMRs are kinematic with collidable safety footprints and local reactive collision avoidance."
}
}
local zones = {}
local robots = {}
local robotOrder = {}
local boxes = {}
local boxOrder = {}
local ticks = {}
local deliveredCount = 0
local lastT = 0.0
local lastAssignmentT = -99.0
local globalMinDistance = 99.0
local currentPolicy = scene.assignment_policy or 'hungarian_centralized'
local amrConfig

local function getByAlias(alias)
    local ok, handle = pcall(sim.getObject, '/' .. alias)
    if ok and handle and handle >= 0 then return handle end
    return nil
end

local function clamp(v, lo, hi)
    return math.max(lo, math.min(hi, v))
end

local function atan2(y, x)
    if math.atan2 then return math.atan2(y, x) end
    return math.atan(y, x)
end

local function dist2(a, b)
    local dx = b[1] - a[1]
    local dy = b[2] - a[2]
    return math.sqrt(dx * dx + dy * dy)
end

local function yawTo(a, b)
    return atan2(b[2] - a[2], b[1] - a[1])
end

local function zoneCenter(name, z)
    local c = zones[name] and zones[name].center or {0.0, 0.0, 0.02}
    return {c[1], c[2], z or 0.18}
end

local function targetIndex(name)
    for i, targetName in ipairs(scene.targets or {}) do
        if targetName == name then return i end
    end
    return 1
end

local function targetNameFromIndex(index)
    local targets = scene.targets or {}
    if #targets == 0 then return 'target_descarga_centro' end
    return targets[((index - 1) % #targets) + 1]
end

local function pickupCenter(boxEntry, z)
    local base = zoneCenter(boxEntry.spec.drop, z or 0.18)
    local offset = boxEntry.spec.slot_offset or {0.0, 0.0}
    return {base[1] + (offset[1] or 0.0), base[2] + (offset[2] or 0.0), z or 0.18}
end

local function targetCenter(boxEntry, z)
    return zoneCenter(boxEntry.target or boxEntry.spec.target or targetNameFromIndex(1), z or 0.18)
end

local function simScale()
    return math.max(0.1, amrConfig('sim_speed_multiplier', 1.0))
end

local function scaledDuration(seconds)
    return seconds / simScale()
end

local function setBoxVisible(handle, visible)
    local layer = visible and 1 or 0
    pcall(sim.setObjectInt32Param, handle, sim.objintparam_visibility_layer, layer)
    local ok, children = pcall(sim.getObjectsInTree, handle, sim.handle_all, 0)
    if ok and children then
        for _, child in ipairs(children) do
            pcall(sim.setObjectInt32Param, child, sim.objintparam_visibility_layer, layer)
        end
    end
end

function amrConfig(name, fallback)
    if scene.amr and scene.amr[name] then return scene.amr[name] end
    return fallback
end

local function collectRing(prefix)
    local handles = {}
    for i = 1, 24 do
        local h = getByAlias(string.format('%s_%02d', prefix, i))
        if h then handles[#handles + 1] = h end
    end
    return handles
end

local function batteryColor(batteryPct)
    local step = math.floor(clamp(batteryPct, 0.0, 100.0) / 100.0 * 9.0 + 0.5) + 1
    local t = (step - 1) / 9.0
    return {
        0.90 * (1.0 - t) + 0.12 * t,
        0.10 * (1.0 - t) + 0.88 * t,
        0.08 * (1.0 - t) + 0.16 * t
    }, step
end

local function setManyColor(handles, color)
    for _, h in ipairs(handles or {}) do
        pcall(sim.setShapeColor, h, nil, sim.colorcomponent_ambient_diffuse, color)
    end
end

local function setAlpha(handle, alpha)
    if not handle then return end
    local transparency = 1.0 - clamp(alpha or 1.0, 0.0, 1.0)
    if sim.colorcomponent_transparency then
        pcall(sim.setShapeColor, handle, nil, sim.colorcomponent_transparency, {transparency})
    end
    if sim.shapefloatparam_transparency then
        pcall(sim.setObjectFloatParam, handle, sim.shapefloatparam_transparency, transparency)
    end
end

local function targetColor(targetName)
    local palette = {
        {0.30, 0.85, 1.00},
        {0.24, 0.82, 0.34},
        {0.96, 0.66, 0.16},
        {0.90, 0.22, 0.18}
    }
    return palette[((targetIndex(targetName) - 1) % #palette) + 1]
end

local function updateBoxTargetVisual(boxEntry)
    if boxEntry.label then
        pcall(sim.setShapeColor, boxEntry.label, nil, sim.colorcomponent_ambient_diffuse, targetColor(boxEntry.target))
    end
    pcall(sim.setNamedStringParam, 'sp0_target_' .. boxEntry.spec.name, boxEntry.target or '')
end

local function advanceBoxTarget(boxEntry)
    boxEntry.targetIndex = (boxEntry.targetIndex or targetIndex(boxEntry.spec.target)) + 1
    boxEntry.target = targetNameFromIndex(boxEntry.targetIndex)
    updateBoxTargetVisual(boxEntry)
end

local function readPolicy()
    local ok, value = pcall(sim.getNamedStringParam, 'sp0_assignment_policy')
    if ok and value and value ~= '' then
        currentPolicy = value
    end
    pcall(sim.setNamedStringParam, 'sp0_assignment_policy_active', currentPolicy)
    return currentPolicy
end

local function updateCounter()
    for i, tick in ipairs(ticks) do
        if tick then
            if i <= deliveredCount then
                pcall(sim.setShapeColor, tick, nil, sim.colorcomponent_ambient_diffuse, {0.18, 0.78, 0.30})
            else
                pcall(sim.setShapeColor, tick, nil, sim.colorcomponent_ambient_diffuse, {0.22, 0.24, 0.25})
            end
        end
    end
    pcall(sim.setNamedInt32Param, 'sp0_delivered_count', deliveredCount)
end

local function updateBatteryVisual(entry)
    local color, step = batteryColor(entry.battery)
    if entry.sensorFill then
        pcall(sim.setShapeColor, entry.sensorFill, nil, sim.colorcomponent_ambient_diffuse, color)
        setAlpha(entry.sensorFill, amrConfig('sensor_fill_alpha', 0.70))
    end
    setManyColor(entry.sensorRing, color)
    setManyColor(entry.commRing, color)
    pcall(sim.setNamedFloatParam, 'sp0_battery_' .. entry.spec.name, entry.battery)
    pcall(sim.setNamedInt32Param, 'sp0_battery_step_' .. entry.spec.name, step)
end

function sysCall_init()
    for _, z in ipairs(scene.zones) do zones[z.name] = z end
    for index, r in ipairs(scene.robots) do
        local handle = getByAlias(r.name)
        if handle then
            local p = sim.getObjectPosition(handle, -1)
            robots[r.name] = {
                handle = handle,
                spec = r,
                index = index,
                pos = {p[1], p[2], 0.18},
                yaw = r.heading_rad or 0.0,
                state = 'idle',
                stateStart = 0.0,
                waitUntil = 0.0,
                carrying = false,
                assignedBox = nil,
                releaseDelay = r.release_delay_s or 0.0,
                battery = r.battery_initial_pct or 100.0,
                footprint = getByAlias(r.name .. '_safety_footprint'),
                sensorFill = getByAlias(r.name .. '_sensor_fill'),
                sensorRing = collectRing(r.name .. '_sensor_radius'),
                commRing = collectRing(r.name .. '_comm_radius'),
                minDistance = 99.0
            }
            robotOrder[#robotOrder + 1] = r.name
            updateBatteryVisual(robots[r.name])
        end
    end
    for _, b in ipairs(scene.boxes) do
        local handle = getByAlias(b.name)
        if handle then
            local index = targetIndex(b.target)
            boxes[b.name] = {
                handle = handle,
                label = getByAlias(b.name .. '_label'),
                spec = b,
                state = 'waiting',
                assignedRobot = nil,
                carrier = nil,
                target = b.target,
                targetIndex = index,
                stateStart = 0.0,
                waitUntil = 0.0,
                respawnAt = 0.0
            }
            boxOrder[#boxOrder + 1] = b.name
            updateBoxTargetVisual(boxes[b.name])
        end
    end
    for i = 1, 48 do
        ticks[i] = getByAlias(string.format('SP0_count_tick_%02d', i))
    end
    pcall(sim.setNamedStringParam, 'sp0_assignment_policy', currentPolicy)
    updateCounter()
end

local function targetFor(entry)
    local assigned = entry.assignedBox and boxes[entry.assignedBox]
    if (entry.state == 'to_box' or entry.state == 'pickup_wait') and assigned then
        return pickupCenter(assigned, 0.18)
    elseif entry.state == 'to_unload' or entry.state == 'unload_wait' then
        if assigned then return targetCenter(assigned, 0.18) end
        return zoneCenter(targetNameFromIndex(1), 0.18)
    elseif entry.state == 'to_charge' or entry.state == 'charging' then
        return zoneCenter(entry.spec.base, 0.18)
    end
    return entry.pos
end

local function progress(entry, t)
    local duration = math.max(0.001, entry.waitUntil - entry.stateStart)
    return clamp((t - entry.stateStart) / duration, 0.0, 1.0)
end

local function releaseAssignedBox(entry)
    if entry.assignedBox and boxes[entry.assignedBox] then
        local b = boxes[entry.assignedBox]
        if b.state == 'assigned' then
            b.state = 'waiting'
            b.assignedRobot = nil
        end
    end
    entry.assignedBox = nil
end

local function updateMission(entry, t)
    local low = amrConfig('battery_low_pct', 28.0)
    local resume = amrConfig('battery_resume_pct', 86.0)
    local arrival = amrConfig('arrival_radius_m', 0.24)
    local dropArrival = amrConfig('drop_alignment_radius_m', 0.12)
    if entry.state == 'charging' then
        if entry.battery >= resume then
            entry.state = 'idle'
            entry.stateStart = t
        end
        return
    end
    if entry.state == 'to_charge' then
        if dist2(entry.pos, zoneCenter(entry.spec.base, 0.18)) <= arrival then
            entry.state = 'charging'
            entry.stateStart = t
        end
        return
    end
    if entry.battery <= low and not entry.carrying then
        releaseAssignedBox(entry)
        entry.state = 'to_charge'
        entry.stateStart = t
        return
    end
    if entry.state == 'idle' or t < entry.releaseDelay then return end
    local target = targetFor(entry)
    local d = dist2(entry.pos, target)
    if entry.state == 'to_box' and d <= dropArrival then
        local b = boxes[entry.assignedBox]
        if b then
            local pickup = pickupCenter(b, 0.18)
            entry.pos[1] = pickup[1]
            entry.pos[2] = pickup[2]
            entry.yaw = yawTo(entry.pos, targetCenter(b, 0.18))
            pcall(sim.setObjectPosition, entry.handle, -1, {entry.pos[1], entry.pos[2], entry.pos[3]})
            pcall(sim.setObjectOrientation, entry.handle, -1, {0, 0, entry.yaw})
            b.state = 'pickup_wait'
            b.carrier = entry.spec.name
            b.stateStart = t
            b.waitUntil = t + scaledDuration(1.20)
        end
        entry.state = 'pickup_wait'
        entry.stateStart = t
        entry.waitUntil = t + scaledDuration(1.20)
        entry.carrying = false
    elseif entry.state == 'pickup_wait' and t >= entry.waitUntil then
        local b = boxes[entry.assignedBox]
        if b then b.state = 'carrying' end
        entry.state = 'to_unload'
        entry.stateStart = t
        entry.carrying = true
    elseif entry.state == 'to_unload' and d <= arrival then
        local b = boxes[entry.assignedBox]
        if b then
            b.state = 'unload_wait'
            b.stateStart = t
            b.waitUntil = t + scaledDuration(1.25)
        end
        entry.state = 'unload_wait'
        entry.stateStart = t
        entry.waitUntil = t + scaledDuration(1.25)
    elseif entry.state == 'unload_wait' and t >= entry.waitUntil then
        if entry.carrying then
            deliveredCount = deliveredCount + 1
            updateCounter()
        end
        local b = boxes[entry.assignedBox]
        if b then
            b.state = 'cooldown'
            b.assignedRobot = nil
            b.carrier = nil
            b.respawnAt = t + scaledDuration(amrConfig('box_respawn_s', 2.0))
        end
        entry.assignedBox = nil
        entry.stateStart = t
        entry.carrying = false
        if entry.battery <= resume then
            entry.state = 'to_charge'
        else
            entry.state = 'idle'
        end
    end
end

local function assignmentEnergy(entry, boxEntry)
    local drop = pickupCenter(boxEntry, 0.18)
    local unload = targetCenter(boxEntry, 0.18)
    local base = zoneCenter(entry.spec.base, 0.18)
    local unloaded = dist2(entry.pos, drop)
    local loaded = dist2(drop, unload)
    local returnHome = dist2(unload, base)
    local moveDrain = amrConfig('battery_move_drain_pct_per_m', 2.2)
    local loadDrain = amrConfig('battery_load_extra_pct_per_m', 0.9)
    return (unloaded + loaded + returnHome) * moveDrain + loaded * loadDrain
end

local function assignmentCost(entry, boxEntry)
    local low = amrConfig('battery_low_pct', 28.0)
    local drop = pickupCenter(boxEntry, 0.18)
    local unload = targetCenter(boxEntry, 0.18)
    local base = zoneCenter(entry.spec.base, 0.18)
    local travel = dist2(entry.pos, drop) + dist2(drop, unload)
    local home = dist2(unload, base)
    local energy = assignmentEnergy(entry, boxEntry)
    if entry.battery - energy < low then return 1.0e9 end
    return travel + home * 0.35 + (100.0 - entry.battery) * 0.035
end

local function publishAssignmentStats(assignments, policy)
    local totalCost = 0.0
    for _, item in ipairs(assignments or {}) do
        local entry = robots[item[1]]
        local boxEntry = boxes[item[2]]
        if entry and boxEntry then totalCost = totalCost + assignmentCost(entry, boxEntry) end
    end
    pcall(sim.setNamedStringParam, 'sp0_dispatch_policy', policy)
    pcall(sim.setNamedFloatParam, 'sp0_dispatch_cost', totalCost)
    pcall(sim.setNamedInt32Param, 'sp0_dispatch_assignments', #(assignments or {}))
end

local function hungarianAssign(candidateNames, jobNames)
    local best = {}
    local bestCount = -1
    local bestCost = 1.0e18
    local used = {}
    local current = {}
    local function copyCurrent()
        local out = {}
        for i, item in ipairs(current) do out[i] = {item[1], item[2]} end
        return out
    end
    local function rec(jobIndex, assignedCount, cost)
        if jobIndex > #jobNames or assignedCount == #candidateNames then
            if assignedCount > bestCount or (assignedCount == bestCount and cost < bestCost) then
                bestCount = assignedCount
                bestCost = cost
                best = copyCurrent()
            end
            return
        end
        rec(jobIndex + 1, assignedCount, cost)
        local boxEntry = boxes[jobNames[jobIndex]]
        for _, robotName in ipairs(candidateNames) do
            if not used[robotName] then
                local entry = robots[robotName]
                local c = assignmentCost(entry, boxEntry)
                if c < 1.0e8 then
                    used[robotName] = true
                    current[#current + 1] = {robotName, jobNames[jobIndex]}
                    rec(jobIndex + 1, assignedCount + 1, cost + c)
                    current[#current] = nil
                    used[robotName] = false
                end
            end
        end
    end
    rec(1, 0, 0.0)
    pcall(sim.setNamedFloatParam, 'sp0_hungarian_cost', bestCost < 1.0e17 and bestCost or -1.0)
    pcall(sim.setNamedInt32Param, 'sp0_hungarian_assignments', bestCount)
    return best
end

local function greedyAssign(candidateNames, jobNames)
    local pairs = {}
    for _, robotName in ipairs(candidateNames) do
        for _, boxName in ipairs(jobNames) do
            local c = assignmentCost(robots[robotName], boxes[boxName])
            if c < 1.0e8 then
                pairs[#pairs + 1] = {robotName, boxName, c}
            end
        end
    end
    table.sort(pairs, function(a, b) return a[3] < b[3] end)
    local usedRobots = {}
    local usedJobs = {}
    local out = {}
    for _, item in ipairs(pairs) do
        if not usedRobots[item[1]] and not usedJobs[item[2]] then
            usedRobots[item[1]] = true
            usedJobs[item[2]] = true
            out[#out + 1] = {item[1], item[2]}
        end
    end
    return out
end

local function replicatorAssign(candidateNames, jobNames)
    local weights = {}
    local utilities = {}
    for _, robotName in ipairs(candidateNames) do
        weights[robotName] = {}
        utilities[robotName] = {}
        local feasible = 0
        for _, boxName in ipairs(jobNames) do
            local c = assignmentCost(robots[robotName], boxes[boxName])
            local u = c < 1.0e8 and 1.0 / (1.0 + c) or 0.0
            utilities[robotName][boxName] = u
            if u > 0.0 then feasible = feasible + 1 end
        end
        for _, boxName in ipairs(jobNames) do
            weights[robotName][boxName] = feasible > 0 and utilities[robotName][boxName] > 0.0 and 1.0 / feasible or 0.0
        end
    end
    for _ = 1, 18 do
        local demand = {}
        for _, boxName in ipairs(jobNames) do demand[boxName] = 0.0 end
        for _, robotName in ipairs(candidateNames) do
            for _, boxName in ipairs(jobNames) do
                demand[boxName] = demand[boxName] + (weights[robotName][boxName] or 0.0)
            end
        end
        for _, robotName in ipairs(candidateNames) do
            local avg = 0.0
            for _, boxName in ipairs(jobNames) do
                local pressure = 1.0 / (1.0 + math.max(0.0, demand[boxName] - 1.0))
                avg = avg + (weights[robotName][boxName] or 0.0) * (utilities[robotName][boxName] or 0.0) * pressure
            end
            local denom = 0.0
            local nextWeights = {}
            for _, boxName in ipairs(jobNames) do
                local pressure = 1.0 / (1.0 + math.max(0.0, demand[boxName] - 1.0))
                local fitness = (utilities[robotName][boxName] or 0.0) * pressure
                local w = math.max(0.0, (weights[robotName][boxName] or 0.0) * (1.0 + 1.15 * (fitness - avg)))
                nextWeights[boxName] = w
                denom = denom + w
            end
            if denom > 0.0 then
                for _, boxName in ipairs(jobNames) do weights[robotName][boxName] = nextWeights[boxName] / denom end
            end
        end
    end
    local pairs = {}
    for _, robotName in ipairs(candidateNames) do
        for _, boxName in ipairs(jobNames) do
            local score = (weights[robotName][boxName] or 0.0) * (utilities[robotName][boxName] or 0.0)
            if score > 0.0 then pairs[#pairs + 1] = {robotName, boxName, score} end
        end
    end
    table.sort(pairs, function(a, b) return a[3] > b[3] end)
    local usedRobots = {}
    local usedJobs = {}
    local out = {}
    for _, item in ipairs(pairs) do
        if not usedRobots[item[1]] and not usedJobs[item[2]] then
            usedRobots[item[1]] = true
            usedJobs[item[2]] = true
            out[#out + 1] = {item[1], item[2]}
        end
    end
    return out
end

local function assignJobs(t)
    if t - lastAssignmentT < scaledDuration(0.75) then return end
    lastAssignmentT = t
    local candidateNames = {}
    local low = amrConfig('battery_low_pct', 28.0)
    for _, name in ipairs(robotOrder) do
        local entry = robots[name]
        if entry and entry.state == 'idle' and t >= entry.releaseDelay and entry.battery > low then
            candidateNames[#candidateNames + 1] = name
        end
    end
    local jobNames = {}
    for _, boxName in ipairs(boxOrder) do
        local b = boxes[boxName]
        if b and b.state == 'cooldown' and t >= b.respawnAt then
            b.state = 'waiting'
            advanceBoxTarget(b)
        end
        if b and b.state == 'waiting' and not b.assignedRobot and t >= b.respawnAt then
            jobNames[#jobNames + 1] = boxName
        end
    end
    local policy = readPolicy()
    local assignments = {}
    if policy == 'distributed_greedy' then
        assignments = greedyAssign(candidateNames, jobNames)
    elseif policy == 'replicator_distributed' then
        assignments = replicatorAssign(candidateNames, jobNames)
    else
        policy = 'hungarian_centralized'
        assignments = hungarianAssign(candidateNames, jobNames)
    end
    publishAssignmentStats(assignments, policy)
    for _, item in ipairs(assignments) do
        local robotName, boxName = item[1], item[2]
        local entry = robots[robotName]
        local b = boxes[boxName]
        if entry and b and entry.state == 'idle' and b.state == 'waiting' then
            entry.assignedBox = boxName
            entry.state = 'to_box'
            entry.stateStart = t
            b.state = 'assigned'
            b.assignedRobot = robotName
        end
    end
end

local function updateSafetyFootprint(entry)
    if not entry.footprint then return end
    local hard = amrConfig('hard_clearance_m', 0.62)
    local avoid = amrConfig('avoidance_radius_m', 1.05)
    local color = {0.08, 0.50, 0.88}
    if entry.minDistance < hard then
        color = {0.90, 0.12, 0.10}
    elseif entry.minDistance < avoid then
        color = {0.95, 0.70, 0.12}
    end
    pcall(sim.setShapeColor, entry.footprint, nil, sim.colorcomponent_ambient_diffuse, color)
end

local function computeVelocity(name, entry)
    local maxSpeed = amrConfig('max_speed_mps', 0.55) * simScale()
    local avoid = amrConfig('avoidance_radius_m', 1.05)
    local hard = amrConfig('hard_clearance_m', 0.62)
    entry.minDistance = 99.0
    if entry.state == 'idle' or entry.state == 'pickup_wait' or entry.state == 'unload_wait' or entry.state == 'charging' then
        return 0.0, 0.0
    end
    local t = sim.getSimulationTime()
    if t < entry.releaseDelay then return 0.0, 0.0 end
    local target = targetFor(entry)
    local dx = target[1] - entry.pos[1]
    local dy = target[2] - entry.pos[2]
    local d = math.sqrt(dx * dx + dy * dy)
    local vx = 0.0
    local vy = 0.0
    if d > 0.001 then
        local speed = maxSpeed * clamp(d / 0.90, 0.20, 1.0)
        vx = dx / d * speed
        vy = dy / d * speed
    end
    for _, otherName in ipairs(robotOrder) do
        if otherName ~= name then
            local other = robots[otherName]
            if other then
                local ox = entry.pos[1] - other.pos[1]
                local oy = entry.pos[2] - other.pos[2]
                local od = math.sqrt(ox * ox + oy * oy)
                if od > 0.001 then
                    entry.minDistance = math.min(entry.minDistance, od)
                    if od < avoid then
                        local strength = ((avoid - od) / avoid) ^ 2 * maxSpeed * 1.65
                        vx = vx + ox / od * strength
                        vy = vy + oy / od * strength
                    end
                    if od < hard and name > otherName then
                        vx = vx * 0.10
                        vy = vy * 0.10
                    end
                end
            end
        end
    end
    local speed = math.sqrt(vx * vx + vy * vy)
    if speed > maxSpeed then
        vx = vx / speed * maxSpeed
        vy = vy / speed * maxSpeed
    end
    return vx, vy
end

local function moveEntry(entry, vx, vy, dt)
    local oldX, oldY = entry.pos[1], entry.pos[2]
    local hx = scene.dimensions_m.width / 2.0 - 0.55
    local hy = scene.dimensions_m.depth / 2.0 - 0.55
    entry.pos[1] = clamp(entry.pos[1] + vx * dt, -hx, hx)
    entry.pos[2] = clamp(entry.pos[2] + vy * dt, -hy, hy)
    local speed = math.sqrt(vx * vx + vy * vy)
    if speed > 0.015 then
        entry.yaw = atan2(vy, vx)
    else
        local target = targetFor(entry)
        if dist2(entry.pos, target) > 0.05 then
            entry.yaw = yawTo(entry.pos, target)
        end
    end
    pcall(sim.setObjectPosition, entry.handle, -1, {entry.pos[1], entry.pos[2], entry.pos[3]})
    pcall(sim.setObjectOrientation, entry.handle, -1, {0, 0, entry.yaw})
    return math.sqrt((entry.pos[1] - oldX) * (entry.pos[1] - oldX) + (entry.pos[2] - oldY) * (entry.pos[2] - oldY))
end

local function updateBattery(entry, distance, dt)
    if entry.state == 'charging' then
        entry.battery = clamp(entry.battery + amrConfig('battery_charge_pct_per_s', 7.5) * dt, 0.0, 100.0)
    else
        local drain = amrConfig('battery_idle_drain_pct_per_s', 0.015) * dt
        drain = drain + distance * amrConfig('battery_move_drain_pct_per_m', 2.2)
        if entry.carrying then
            drain = drain + distance * amrConfig('battery_load_extra_pct_per_m', 0.9)
        end
        entry.battery = clamp(entry.battery - drain, 0.0, 100.0)
    end
    updateBatteryVisual(entry)
end

local function updateBox(boxEntry, t)
    local box = boxEntry.handle
    local boxHeight = boxEntry.spec.size[3]
    local drop = pickupCenter(boxEntry, 0.18)
    local unload = targetCenter(boxEntry, 0.18)
    local pos = {drop[1], drop[2], scene.drop_height_m + boxHeight}
    local yaw = 0.0
    local visible = boxEntry.state ~= 'cooldown'
    if boxEntry.state == 'pickup_wait' then
        visible = true
        local u = progress(boxEntry, t)
        pos = {drop[1], drop[2], scene.drop_height_m + (scene.carry_height_m - scene.drop_height_m) * u}
    elseif boxEntry.state == 'carrying' and boxEntry.carrier and robots[boxEntry.carrier] then
        visible = true
        local carrier = robots[boxEntry.carrier]
        pos = {carrier.pos[1], carrier.pos[2], scene.carry_height_m}
        yaw = carrier.yaw
    elseif boxEntry.state == 'unload_wait' then
        visible = true
        local u = progress(boxEntry, t)
        pos = {unload[1], unload[2], scene.carry_height_m + (scene.suction_height_m - scene.carry_height_m) * u}
    end
    setBoxVisible(box, visible)
    pcall(sim.setObjectPosition, box, -1, pos)
    pcall(sim.setObjectOrientation, box, -1, {0, 0, yaw})
    updateBoxTargetVisual(boxEntry)
end

function sysCall_actuation()
    local t = sim.getSimulationTime()
    local dt = t - lastT
    if dt <= 0.0 then dt = 0.05 end
    dt = clamp(dt, 0.01, 0.12)
    lastT = t
    for _, name in ipairs(robotOrder) do
        local entry = robots[name]
        if entry then updateMission(entry, t) end
    end
    assignJobs(t)
    local velocities = {}
    globalMinDistance = 99.0
    for _, name in ipairs(robotOrder) do
        local entry = robots[name]
        if entry then
            local vx, vy = computeVelocity(name, entry)
            velocities[name] = {vx, vy}
            globalMinDistance = math.min(globalMinDistance, entry.minDistance)
        end
    end
    for _, name in ipairs(robotOrder) do
        local entry = robots[name]
        if entry then
            local v = velocities[name] or {0.0, 0.0}
            local distance = moveEntry(entry, v[1], v[2], dt)
            updateBattery(entry, distance, dt)
            updateSafetyFootprint(entry)
        end
    end
    for _, boxName in ipairs(boxOrder) do
        local boxEntry = boxes[boxName]
        if boxEntry then updateBox(boxEntry, t) end
    end
    pcall(sim.setNamedFloatParam, 'sp0_min_robot_distance_m', globalMinDistance)
    pcall(sim.setNamedInt32Param, 'sp0_collision_warning', globalMinDistance < amrConfig('hard_clearance_m', 0.62) and 1 or 0)
end
]==]
local dummy = setAlias(sim.createDummy(0.035), 'SP0_demo_controller')
if sim.getBoolParam(sim.boolparam_usingscriptobjects) then
    local s = sim.createScript(sim.scripttype_simulation, scriptText, 0, 'lua')
    sim.setObjectParent(s, dummy)
else
    local s = sim.addScript(sim.scripttype_simulation)
    sim.associateScriptWithObject(s, dummy)
    sim.setScriptText(s, scriptText)
end
sim.setNamedStringParam('sp0_corners_scene_json', [==[{
  "scenario": "sp0_corners_drop_suction_pioneer",
  "description": "SP0 CoppeliaSim scene: corner loads, eight Pioneer AMRs, three target unload zones and dispatch policy comparison.",
  "dimensions_m": {
    "width": 10.5,
    "depth": 10.5
  },
  "model_paths": {
    "pioneer_p3dx": "C:\\Program Files\\CoppeliaRobotics\\CoppeliaSimEdu\\models\\robots\\mobile\\pioneer p3dx.ttm"
  },
  "zones": [
    {
      "name": "carga_robot_01",
      "kind": "charge",
      "center": [
        -4.35,
        -4.2,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_02",
      "kind": "charge",
      "center": [
        -3.55,
        -4.2,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_03",
      "kind": "charge",
      "center": [
        -4.35,
        -3.4,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_04",
      "kind": "charge",
      "center": [
        -3.55,
        -3.4,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_05",
      "kind": "charge",
      "center": [
        4.35,
        4.2,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_06",
      "kind": "charge",
      "center": [
        3.55,
        4.2,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_07",
      "kind": "charge",
      "center": [
        4.35,
        3.4,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "carga_robot_08",
      "kind": "charge",
      "center": [
        3.55,
        3.4,
        0.02
      ],
      "size": [
        0.62,
        0.62,
        0.02
      ],
      "color": [
        0.16,
        0.34,
        0.58
      ]
    },
    {
      "name": "caida_cajas_nw",
      "kind": "drop",
      "center": [
        -4.05,
        3.75,
        0.02
      ],
      "size": [
        1.38,
        1.38,
        0.02
      ],
      "color": [
        0.88,
        0.64,
        0.12
      ]
    },
    {
      "name": "caida_cajas_se",
      "kind": "drop",
      "center": [
        4.05,
        -3.75,
        0.02
      ],
      "size": [
        1.38,
        1.38,
        0.02
      ],
      "color": [
        0.88,
        0.64,
        0.12
      ]
    },
    {
      "name": "target_descarga_oeste",
      "kind": "unload",
      "center": [
        -1.8,
        0.0,
        0.02
      ],
      "size": [
        1.05,
        1.05,
        0.02
      ],
      "color": [
        0.14,
        0.55,
        0.32
      ]
    },
    {
      "name": "target_descarga_centro",
      "kind": "unload",
      "center": [
        0.0,
        0.0,
        0.02
      ],
      "size": [
        1.05,
        1.05,
        0.02
      ],
      "color": [
        0.14,
        0.55,
        0.32
      ]
    },
    {
      "name": "target_descarga_este",
      "kind": "unload",
      "center": [
        1.8,
        0.0,
        0.02
      ],
      "size": [
        1.05,
        1.05,
        0.02
      ],
      "color": [
        0.14,
        0.55,
        0.32
      ]
    }
  ],
  "targets": [
    "target_descarga_oeste",
    "target_descarga_centro",
    "target_descarga_este"
  ],
  "assignment_policy": "hungarian_centralized",
  "benchmark_policies": [
    "hungarian_centralized",
    "distributed_greedy",
    "replicator_distributed"
  ],
  "robots": [
    {
      "name": "SP0_Pioneer_01",
      "base": "carga_robot_01",
      "drop": "caida_cajas_nw",
      "release_delay_s": 0.0,
      "position": [
        -4.35,
        -4.2,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 100.0
    },
    {
      "name": "SP0_Pioneer_02",
      "base": "carga_robot_02",
      "drop": "caida_cajas_se",
      "release_delay_s": 0.4,
      "position": [
        -3.55,
        -4.2,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 92.0
    },
    {
      "name": "SP0_Pioneer_03",
      "base": "carga_robot_03",
      "drop": "caida_cajas_nw",
      "release_delay_s": 0.8,
      "position": [
        -4.35,
        -3.4,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 84.0
    },
    {
      "name": "SP0_Pioneer_04",
      "base": "carga_robot_04",
      "drop": "caida_cajas_se",
      "release_delay_s": 1.2,
      "position": [
        -3.55,
        -3.4,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 76.0
    },
    {
      "name": "SP0_Pioneer_05",
      "base": "carga_robot_05",
      "drop": "caida_cajas_se",
      "release_delay_s": 0.0,
      "position": [
        4.35,
        4.2,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 88.0
    },
    {
      "name": "SP0_Pioneer_06",
      "base": "carga_robot_06",
      "drop": "caida_cajas_nw",
      "release_delay_s": 0.4,
      "position": [
        3.55,
        4.2,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 80.0
    },
    {
      "name": "SP0_Pioneer_07",
      "base": "carga_robot_07",
      "drop": "caida_cajas_se",
      "release_delay_s": 0.8,
      "position": [
        4.35,
        3.4,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 68.0
    },
    {
      "name": "SP0_Pioneer_08",
      "base": "carga_robot_08",
      "drop": "caida_cajas_nw",
      "release_delay_s": 1.2,
      "position": [
        3.55,
        3.4,
        0.18
      ],
      "heading_rad": 0.0,
      "battery_initial_pct": 60.0
    }
  ],
  "boxes": [
    {
      "name": "SP0_box_NW_01",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_nw",
      "slot_offset": [
        -0.32,
        -0.28
      ],
      "target": "target_descarga_oeste"
    },
    {
      "name": "SP0_box_NW_02",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_nw",
      "slot_offset": [
        0.32,
        -0.28
      ],
      "target": "target_descarga_centro"
    },
    {
      "name": "SP0_box_NW_03",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_nw",
      "slot_offset": [
        0.0,
        0.3
      ],
      "target": "target_descarga_este"
    },
    {
      "name": "SP0_box_SE_01",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_se",
      "slot_offset": [
        -0.32,
        -0.28
      ],
      "target": "target_descarga_centro"
    },
    {
      "name": "SP0_box_SE_02",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_se",
      "slot_offset": [
        0.32,
        -0.28
      ],
      "target": "target_descarga_este"
    },
    {
      "name": "SP0_box_SE_03",
      "size": [
        0.36,
        0.28,
        0.18
      ],
      "mass_kg": 2.0,
      "drop": "caida_cajas_se",
      "slot_offset": [
        0.0,
        0.3
      ],
      "target": "target_descarga_oeste"
    }
  ],
  "box_size_m": [
    0.36,
    0.28,
    0.18
  ],
  "drop_height_m": 1.55,
  "carry_height_m": 0.42,
  "suction_height_m": 3.2,
  "amr": {
    "max_speed_mps": 0.55,
    "sim_speed_multiplier": 2.0,
    "arrival_radius_m": 0.2,
    "drop_alignment_radius_m": 0.07,
    "avoidance_radius_m": 1.05,
    "hard_clearance_m": 0.62,
    "footprint_radius_m": 0.46,
    "sensor_radius_m": 0.95,
    "comm_radius_m": 1.65,
    "sensor_fill_alpha": 0.7,
    "battery_low_pct": 28.0,
    "battery_resume_pct": 86.0,
    "battery_move_drain_pct_per_m": 2.2,
    "battery_load_extra_pct_per_m": 0.9,
    "battery_idle_drain_pct_per_s": 0.015,
    "battery_charge_pct_per_s": 7.5,
    "box_respawn_s": 2.0
  },
  "metadata": {
    "purpose": "SP0 physical smoke scene for spawn/drop, carry, unload count.",
    "corner_policy": "Individual charge pads in SW/NE; crossed drop zones in NW/SE; three central target unload zones.",
    "physics_policy": "AMRs are kinematic with collidable safety footprints and local reactive collision avoidance."
  }
}]==])
