"""Rigid formation and vectorial wrench-game helpers."""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from numpy.typing import NDArray

from viu_mrob_tfm.domain.load import LoadSpec, WrenchDemand

try:  # pragma: no cover - fallback only used in minimal environments.
    from scipy.optimize import lsq_linear
except ImportError:  # pragma: no cover
    lsq_linear = None


Array = NDArray[np.float64]


@dataclass(frozen=True, slots=True)
class RigidFormationSlot:
    """Contact slot fixed in the transported load frame."""

    offset: Array
    normal: Array
    label: str = "contact"

    def __post_init__(self) -> None:
        offset = np.asarray(self.offset, dtype=float)
        normal = np.asarray(self.normal, dtype=float)
        if offset.shape != (2,) or normal.shape != (2,):
            raise ValueError("RigidFormationSlot offset and normal must be 2D vectors.")
        norm = float(np.linalg.norm(normal))
        if norm <= 1e-12:
            raise ValueError("RigidFormationSlot normal must be nonzero.")
        object.__setattr__(self, "offset", offset)
        object.__setattr__(self, "normal", normal / norm)

    def wrench_column(self) -> Array:
        """Return the planar wrench generated by one unit contact force."""
        rx, ry = self.offset
        fx, fy = self.normal
        return np.array([fx, fy, rx * fy - ry * fx], dtype=float)


@dataclass(frozen=True, slots=True)
class RigidFormation:
    """Ordered rigid contact formation around a rectangular load."""

    slots: tuple[RigidFormationSlot, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if not self.slots:
            raise ValueError("RigidFormation requires at least one contact slot.")

    @classmethod
    def rectangular(cls, length_m: float, width_m: float) -> "RigidFormation":
        """Build contact slots around a rectangular load footprint."""
        if length_m <= 0.0 or width_m <= 0.0:
            raise ValueError("RigidFormation dimensions must be positive.")
        hx = 0.5 * float(length_m)
        hy = 0.5 * float(width_m)
        return cls(
            slots=(
                RigidFormationSlot(np.array([hx, -hy]), np.array([1.0, 0.0]), "right-rear-push"),
                RigidFormationSlot(np.array([-hx, hy]), np.array([-1.0, 0.0]), "left-front-push"),
                RigidFormationSlot(np.array([hx, hy]), np.array([0.0, 1.0]), "front-right-push"),
                RigidFormationSlot(np.array([-hx, -hy]), np.array([0.0, -1.0]), "rear-left-push"),
                RigidFormationSlot(np.array([hx, hy]), np.array([1.0, 0.0]), "right-front-push"),
                RigidFormationSlot(np.array([-hx, -hy]), np.array([-1.0, 0.0]), "left-rear-push"),
                RigidFormationSlot(np.array([-hx, hy]), np.array([0.0, 1.0]), "front-left-push"),
                RigidFormationSlot(np.array([hx, -hy]), np.array([0.0, -1.0]), "rear-right-push"),
            )
        )

    @classmethod
    def from_load(cls, load: LoadSpec) -> "RigidFormation":
        """Build the canonical rigid formation for a load specification."""
        return cls.rectangular(length_m=load.length_m, width_m=load.width_m)

    def slot_for_rank(self, rank: int) -> RigidFormationSlot:
        """Return the slot assigned to a coalition member rank."""
        if rank < 0:
            raise ValueError("Formation rank must be non-negative.")
        return self.slots[rank % len(self.slots)]

    def slots_for_count(self, count: int | None = None) -> tuple[RigidFormationSlot, ...]:
        """Return the ordered slots used by a coalition of the requested size."""
        if count is None:
            return self.slots
        if count < 0:
            raise ValueError("Formation slot count must be non-negative.")
        return tuple(self.slot_for_rank(rank) for rank in range(count))

    def contact_matrix(self, count: int | None = None) -> Array:
        """Return G where G @ lambda approximates [Fx, Fy, tau_z]."""
        slots = self.slots_for_count(count)
        if not slots:
            return np.zeros((3, 0), dtype=float)
        return np.column_stack([slot.wrench_column() for slot in slots])


@dataclass(frozen=True, slots=True)
class WrenchSolution:
    """Result of the vectorial contact-force game."""

    contact_forces: Array
    provided_wrench: Array
    residual: Array
    residual_norm: float
    feasible: bool
    marginal_utilities: Array


@dataclass(slots=True)
class VectorialWrenchGame:
    """Allocate contact-force magnitudes to reduce force-torque residual."""

    residual_tolerance: float = 1e-6

    def solve(
        self,
        demand: WrenchDemand | Array,
        formation: RigidFormation,
        force_limits: Array | list[float] | tuple[float, ...] | None = None,
        contact_count: int | None = None,
    ) -> WrenchSolution:
        """Solve a bounded least-squares game in wrench space.

        Each robot chooses a non-negative scalar effort along its assigned contact
        normal. The collective payoff is the reduction of the planar wrench residual
        under individual force limits.
        """
        demand_vec = demand.as_vector() if isinstance(demand, WrenchDemand) else np.asarray(demand, dtype=float)
        if demand_vec.shape != (3,):
            raise ValueError("Wrench demand must be a 3D [Fx, Fy, tau_z] vector.")

        count = len(formation.slots) if contact_count is None else int(contact_count)
        matrix = formation.contact_matrix(count)
        limits = self._force_limits(force_limits, count)
        forces = np.zeros(count, dtype=float)

        active = limits > 0.0
        if count > 0 and np.any(active):
            active_matrix = matrix[:, active]
            active_limits = limits[active]
            if lsq_linear is not None:
                result = lsq_linear(
                    active_matrix,
                    demand_vec,
                    bounds=(np.zeros(active_limits.size, dtype=float), active_limits),
                    tol=1e-12,
                    max_iter=200,
                )
                forces[active] = result.x
            else:  # pragma: no cover
                raw, *_ = np.linalg.lstsq(active_matrix, demand_vec, rcond=None)
                forces[active] = np.clip(raw, 0.0, active_limits)

        provided = matrix @ forces if count > 0 else np.zeros(3, dtype=float)
        residual = demand_vec - provided
        residual_norm = float(np.linalg.norm(residual))
        utilities = self._marginal_utilities(matrix, forces, demand_vec)
        return WrenchSolution(
            contact_forces=forces,
            provided_wrench=provided,
            residual=residual,
            residual_norm=residual_norm,
            feasible=residual_norm <= self.residual_tolerance,
            marginal_utilities=utilities,
        )

    def _force_limits(
        self,
        force_limits: Array | list[float] | tuple[float, ...] | None,
        count: int,
    ) -> Array:
        if count < 0:
            raise ValueError("contact_count must be non-negative.")
        if count == 0:
            return np.zeros(0, dtype=float)
        if force_limits is None:
            return np.ones(count, dtype=float)
        limits = np.asarray(force_limits, dtype=float).reshape(-1)
        if limits.size == 0:
            return np.ones(count, dtype=float)
        if limits.size < count:
            limits = np.pad(limits, (0, count - limits.size), mode="edge")
        return np.maximum(limits[:count], 0.0)

    def _marginal_utilities(self, matrix: Array, forces: Array, demand_vec: Array) -> Array:
        if forces.size == 0:
            return np.zeros(0, dtype=float)
        demand_norm = float(np.linalg.norm(demand_vec))
        if demand_norm <= 1e-12:
            return np.zeros_like(forces)
        demand_axis = demand_vec / demand_norm
        return np.maximum(0.0, forces * (matrix.T @ demand_axis))