"""Reproducible Stage 2.5 originality and AI-writing audit.

The selected document is scoped to the active input graph rooted at either
``pre-thesis/main.tex`` or ``pre-thesis/monograph/main.tex``.  It resolves
literal ``\\iffalse``/``\\iftrue``
branches and entry-point ``\\ifdefined`` switches, excludes
non-prose display environments, inventories prose paragraphs, selects a
deterministic stratified sample, detects style patterns, and compares the
active prose with the author's local draft corpora.

It does not decide whether text was generated by AI and it is not a substitute
for Turnitin or iThenticate.  Outputs are heuristic audit evidence only.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import html
import hashlib
import io
import json
import math
import re
import subprocess
import sys
import unicodedata
import urllib.request
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Iterator

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[4]
PRE_THESIS = ROOT / "pre-thesis"
OUTPUT = Path(__file__).resolve().parent
ENTRYPOINT = PRE_THESIS / "main.tex"
DOCUMENT_SCOPE = "thesis"
PDF_PATH = PRE_THESIS / "build" / "main.pdf"
SAMPLE_SEED = "VIU-MROB-stage-2.5-originality-2026-09-08-v1"
INPUT_RE = re.compile(r"\\(?:input|include)\{([^}]+)\}")
WORD_RE = re.compile(r"[0-9A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+", re.UNICODE)
CORPUS_BASES = {
    "paper": [ROOT / "paper"],
    "work": [ROOT / "material" / "compendios"],
    "thesis": [ROOT / "thesis"],
    "snapshot": [PRE_THESIS / "sections" / "source-snapshot"],
    "legacy_snapshot": [ROOT / "legacy" / "_thesis_coppelia_snapshot_20260717"],
}
CORPUS_TEXT_SUFFIXES = {".tex", ".md", ".txt", ".pdf"}
AUTHOR_WORKS = [
    {
        "work_id": "mayorga-2014-population-traffic",
        "title": "Dinámicas poblacionales distribuidas aplicadas al control de tráfico urbano",
        "year": 2014,
        "type": "undergraduate-thesis",
        "metadata_url": "https://redcol.minciencias.gov.co/Record/UNIANDES2_ede6d116115d0685612317329c2b338a",
        "comparison_url": "https://repositorio.uniandes.edu.co/server/api/core/bitstreams/f2d97b2c-2dab-4a00-be25-798636ee21c6/content",
        "comparison_mode": "full_text_pdf",
    },
    {
        "work_id": "mayorga-2015-hiles-fpga",
        "title": "Development of real-time control emulator in FPGA using HiLeS methodology",
        "year": 2015,
        "type": "conference-paper",
        "metadata_url": "https://doi.org/10.1109/IECON.2015.7392735",
        "comparison_url": "https://api.crossref.org/works/10.1109/IECON.2015.7392735",
        "comparison_mode": "crossref_metadata_abstract",
    },
]


@dataclass(frozen=True)
class Paragraph:
    paragraph_id: str
    chapter: str
    section: str
    path: str
    line_start: int
    line_end: int
    words: int
    sentences: int
    text: str
    normalized_sha256: str
    query_fragment: str
    sample_rank: str
    sampled: bool


def configure_document(document: str) -> None:
    """Select one frozen document graph and its independent evidence files."""

    global DOCUMENT_SCOPE, ENTRYPOINT, PDF_PATH
    DOCUMENT_SCOPE = document
    if document == "thesis":
        ENTRYPOINT = PRE_THESIS / "main.tex"
        PDF_PATH = PRE_THESIS / "build" / "main.pdf"
    elif document == "monograph":
        ENTRYPOINT = PRE_THESIS / "monograph" / "main.tex"
        PDF_PATH = PRE_THESIS / "monograph" / "build" / "monograph.pdf"
    else:
        raise ValueError(f"Unsupported document scope: {document}")


def artifact(name: str) -> Path:
    """Return the document-scoped audit artifact path."""

    return OUTPUT / (name if DOCUMENT_SCOPE == "thesis" else f"monograph-{name}")


def document_pdf_metadata() -> dict[str, object]:
    if not PDF_PATH.is_file():
        return {
            "path": PDF_PATH.relative_to(ROOT).as_posix(),
            "exists": False,
            "bytes": 0,
            "pages": 0,
            "sha256": "",
        }
    return {
        "path": PDF_PATH.relative_to(ROOT).as_posix(),
        "exists": True,
        "bytes": PDF_PATH.stat().st_size,
        "pages": len(PdfReader(str(PDF_PATH)).pages),
        "sha256": hashlib.sha256(PDF_PATH.read_bytes()).hexdigest(),
    }


def write_csv(path: Path, rows: Iterable[dict[str, object]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def strip_comments_preserve_lines(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines(keepends=True):
        newline = "\n" if line.endswith("\n") else ""
        body = line[:-1] if newline else line
        cut = len(body)
        for index, character in enumerate(body):
            if character != "%":
                continue
            slashes = 0
            cursor = index - 1
            while cursor >= 0 and body[cursor] == "\\":
                slashes += 1
                cursor -= 1
            if slashes % 2 == 0:
                cut = index
                break
        lines.append(body[:cut] + " " * (len(body) - cut) + newline)
    return "".join(lines)


def entrypoint_defined_macros() -> frozenset[str]:
    """Return macros explicitly defined by the thesis entry point.

    The active manuscript leaves ``\\VIUFullSPsixProofs`` undefined, whereas
    the separate monograph defines it.  Reading definitions from the audited
    entry point prevents the monograph-only proof branches from entering the
    thesis inventory.
    """

    source = strip_comments_preserve_lines(
        ENTRYPOINT.read_text(encoding="utf-8", errors="replace")
    )
    names: set[str] = set()
    for pattern in (
        r"\\(?:newcommand|renewcommand|providecommand)\*?\s*\{\\([A-Za-z@]+)\}",
        r"\\def\s*\\([A-Za-z@]+)",
    ):
        names.update(re.findall(pattern, source))
    return frozenset(names)


def active_literal_branches(
    text: str, defined_macros: frozenset[str] | None = None
) -> str:
    """Blank inactive TeX branches while preserving source line offsets."""

    source = strip_comments_preserve_lines(text)
    if defined_macros is None:
        defined_macros = entrypoint_defined_macros()
    token_re = re.compile(
        r"\\(?:(?P<fixed>iffalse|iftrue|else|fi)(?![A-Za-z@])"
        r"|(?P<defined>ifdefined)\s*\\(?P<macro>[A-Za-z@]+))"
    )
    stack: list[bool] = []
    out: list[str] = []
    cursor = 0

    def visible() -> bool:
        return all(stack)

    for match in token_re.finditer(source):
        segment = source[cursor : match.start()]
        out.append(segment if visible() else re.sub(r"[^\n]", " ", segment))
        token = match.group(0)
        out.append(" " * len(token))
        fixed = match.group("fixed")
        if fixed == "iffalse":
            stack.append(False)
        elif fixed == "iftrue":
            stack.append(True)
        elif match.group("defined"):
            stack.append(match.group("macro") in defined_macros)
        elif fixed == "else" and stack:
            stack[-1] = not stack[-1]
        elif fixed == "fi" and stack:
            stack.pop()
        cursor = match.end()
    tail = source[cursor:]
    out.append(tail if visible() else re.sub(r"[^\n]", " ", tail))
    if stack:
        raise ValueError("Unclosed literal TeX conditional")
    return "".join(out)


def resolve_input(source: Path, name: str) -> Path | None:
    candidates = [PRE_THESIS / name, source.parent / name]
    for candidate in candidates:
        if not candidate.suffix:
            candidate = candidate.with_suffix(".tex")
        if candidate.is_file():
            return candidate.resolve()
    return None


def active_graph(entrypoint: Path | None = None) -> list[Path]:
    if entrypoint is None:
        entrypoint = ENTRYPOINT
    ordered: list[Path] = []
    visited: set[Path] = set()

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in visited:
            return
        path.relative_to(PRE_THESIS.resolve())
        visited.add(path)
        ordered.append(path)
        active = active_literal_branches(path.read_text(encoding="utf-8", errors="replace"))
        for match in INPUT_RE.finditer(active):
            child = resolve_input(path, match.group(1))
            if child:
                visit(child)

    visit(entrypoint)
    return ordered


def is_prose_source(path: Path) -> bool:
    rel = path.relative_to(PRE_THESIS).as_posix()
    if DOCUMENT_SCOPE == "monograph":
        return (
            rel == "monograph/main.tex"
            or rel.startswith("monograph/sections/")
            or rel.startswith("sections/")
        )
    if not rel.startswith("sections/"):
        return False
    if "/frontmatter/" in rel:
        return rel.endswith(("01-summary.tex", "02-abstract.tex"))
    return True


def chapter_for(path: Path, section: str = "") -> str:
    rel = path.relative_to(PRE_THESIS).as_posix()
    if DOCUMENT_SCOPE == "monograph":
        if rel == "monograph/main.tex":
            return f"Monografía: {section}" if section != "(sin encabezado local)" else "Monografía: preliminares"
        if rel.startswith("monograph/sections/") or rel.endswith(("/sp0.tex", "/sp1.tex")):
            return "Monografía: resultados E0--E1"
        if rel.endswith(("/sp2.tex", "/sp3.tex")):
            return "Monografía: resultados SP1"
        if rel.endswith(("/sp4.tex", "/sp5.tex", "/sp6.tex", "/cargo-e2e.tex")):
            return "Monografía: resultados SP2"
        if rel.endswith(("/sp7.tex", "/sp8.tex", "/aws-industrial2.tex")):
            return "Monografía: resultados SP3"
        if "/appendices/" in rel:
            return "Monografía: demostraciones extendidas"
        if "05-theoretical-framework" in rel:
            return "Monografía: modelo común y estado del arte"
        return "Monografía: otro"
    if rel.endswith("frontmatter/01-summary.tex"):
        return "Preliminares: Resumen"
    if rel.endswith("frontmatter/02-abstract.tex"):
        return "Preliminares: Abstract"
    for number, title in (
        ("01-", "1. Introducción"),
        ("02-", "2. Objetivos"),
        ("03-", "3. Hipótesis"),
        ("04-", "4. Metodología"),
        ("05-", "5. Marco teórico"),
        ("07-", "7. Conclusiones"),
    ):
        if f"/mainmatter/{number}" in rel:
            return title
    if "06-results-and-analysis" in rel or rel.endswith("sections/thesis-results.tex"):
        return "6. Resultados y análisis"
    if "/appendices/" in rel or rel.endswith("sections/thesis-appendices.tex"):
        return "Anexos"
    return "Otro"


DISPLAY_ENVIRONMENTS = (
    "figure",
    "figure*",
    "table",
    "table*",
    "tabular",
    "tabularx",
    "longtable",
    "equation",
    "equation*",
    "align",
    "align*",
    "aligned",
    "gather",
    "gather*",
    "multline",
    "multline*",
    "displaymath",
    "tikzpicture",
    "lstlisting",
    "verbatim",
)


def blank_display_environments(text: str) -> str:
    for environment in DISPLAY_ENVIRONMENTS:
        pattern = re.compile(
            rf"\\begin\{{{re.escape(environment)}\}}.*?\\end\{{{re.escape(environment)}\}}",
            flags=re.DOTALL,
        )
        text = pattern.sub(lambda m: re.sub(r"[^\n]", " ", m.group(0)), text)
    text = re.sub(
        r"\\\[.*?\\\]",
        lambda m: re.sub(r"[^\n]", " ", m.group(0)),
        text,
        flags=re.DOTALL,
    )
    return text


def normalize_unicode(value: str) -> str:
    value = unicodedata.normalize("NFKD", value)
    return "".join(char for char in value if not unicodedata.combining(char))


def latex_to_text(value: str) -> str:
    value = re.sub(r"\\(?:auto|paren|text|foot|smart|super|no)?cite\w*\s*(?:\[[^]]*\]\s*){0,2}\{[^{}]*\}", " ", value)
    value = re.sub(r"\\(?:label|zlabel|ref|eqref|pageref|autoref|cref|Cref)\{[^{}]*\}", " ", value)
    value = re.sub(r"\\(?:input|include)\{[^{}]*\}", " ", value)
    value = re.sub(r"\\href\{[^{}]*\}\{([^{}]*)\}", r"\1", value)
    value = re.sub(r"\\url\{[^{}]*\}", " ", value)
    value = re.sub(r"\\(?:section|subsection|subsubsection|paragraph|chapter)\*?\{[^{}]*\}", " ", value)
    value = re.sub(r"\$[^$]*\$", " ", value, flags=re.DOTALL)
    value = re.sub(r"\\\([^)]*\\\)", " ", value, flags=re.DOTALL)
    value = re.sub(r"\\(?:begin|end)\{[^{}]*\}", " ", value)
    value = re.sub(r"\\item(?:\[[^]]*\])?", " ", value)
    # Preserve the visible argument of formatting and semantic commands.
    for _ in range(6):
        previous = value
        value = re.sub(r"\\[A-Za-z@]+\*?(?:\[[^]]*\])?\{([^{}]*)\}", r"\1", value)
        if value == previous:
            break
    value = re.sub(r"\\[A-Za-z@]+\*?(?:\[[^]]*\])?", " ", value)
    value = re.sub(r"\\['\"`^~=.uvHckbrd]\s*\{?([A-Za-z])\}?", r"\1", value)
    value = value.replace("~", " ").replace("{", " ").replace("}", " ")
    value = value.replace("\\%", "%").replace("\\&", "&").replace("\\_", "_")
    value = re.sub(r"\s+", " ", value).strip(" ,;:")
    return value


def normalized_words(text: str) -> list[str]:
    return [word.casefold() for word in WORD_RE.findall(normalize_unicode(text))]


def sentence_count(text: str) -> int:
    return max(1, len(re.findall(r"[.!?](?:\s|$)", text)))


def section_context(lines: list[str], line_index: int) -> str:
    pattern = re.compile(r"\\(?:section|subsection|subsubsection|paragraph)\*?\{([^{}]+)\}")
    for cursor in range(line_index, -1, -1):
        matches = list(pattern.finditer(lines[cursor]))
        if matches:
            return latex_to_text(matches[-1].group(1))
    return "(sin encabezado local)"


def raw_paragraphs(
    path: Path, *, minimum_words: int = 20
) -> Iterator[tuple[int, int, str, str]]:
    active = active_literal_branches(path.read_text(encoding="utf-8", errors="replace"))
    # The monograph entry point contains document metadata and a title page,
    # neither of which is manuscript prose.  Blank everything before its first
    # section while retaining newlines and therefore source coordinates.
    if DOCUMENT_SCOPE == "monograph" and path.resolve() == ENTRYPOINT.resolve():
        first_section = re.search(r"\\section\*?\{", active)
        if first_section:
            active = re.sub(r"[^\n]", " ", active[: first_section.start()]) + active[first_section.start() :]
    active = blank_display_environments(active)
    context_lines = active.splitlines()
    # Structural commands delimit prose even when the source omits a blank line.
    active = re.sub(
        r"(\\(?:section|subsection|subsubsection|paragraph)\*?\{[^{}]+\})",
        lambda match: " " * len(match.group(0)),
        active,
    )
    lines = active.splitlines()
    start: int | None = None
    bucket: list[str] = []
    for index, line in enumerate(lines):
        if not line.strip():
            if start is not None:
                raw = "\n".join(bucket)
                plain = latex_to_text(raw)
                if len(normalized_words(plain)) >= minimum_words:
                    yield start + 1, index, section_context(context_lines, start), plain
                start, bucket = None, []
            continue
        if start is None:
            start = index
        bucket.append(line)
    if start is not None:
        plain = latex_to_text("\n".join(bucket))
        if len(normalized_words(plain)) >= minimum_words:
            yield start + 1, len(lines), section_context(context_lines, start), plain


def style_prose_units() -> list[dict[str, object]]:
    """Return every nonempty active prose unit for exhaustive style scans.

    The originality inventory uses a 20-word threshold so equation lead-ins do
    not become low-information plagiarism queries.  Detection-only style checks
    additionally scan all shorter prose fragments.
    """

    units: list[dict[str, object]] = []
    for path in active_graph():
        if not is_prose_source(path):
            continue
        rel = path.relative_to(ROOT).as_posix()
        for sequence, (line_start, line_end, section, plain) in enumerate(
            raw_paragraphs(path, minimum_words=1), 1
        ):
            units.append(
                {
                    "paragraph_id": f"{rel}:{line_start}:u{sequence:03d}",
                    "chapter": chapter_for(path, section),
                    "section": section,
                    "path": rel,
                    "line_start": line_start,
                    "line_end": line_end,
                    "text": plain,
                }
            )
    return units


def characteristic_fragment(text: str, document_frequency: Counter[str], documents: int) -> str:
    words = WORD_RE.findall(text)
    if len(words) <= 12:
        return " ".join(words[:12])
    best_score = -1.0
    best = words[:10]
    for width in (10, 11, 12, 9, 8):
        for start in range(0, len(words) - width + 1):
            window = words[start : start + width]
            norm = [normalize_unicode(word).casefold() for word in window]
            score = sum(math.log((documents + 1) / (document_frequency[word] + 1)) for word in set(norm))
            score += 1.5 * sum(any(char.isdigit() for char in word) for word in window)
            score += 0.25 * sum(word[:1].isupper() for word in window[1:])
            if score > best_score:
                best_score, best = score, window
    return " ".join(best)


def inventory() -> list[Paragraph]:
    provisional: list[dict[str, object]] = []
    for path in active_graph():
        if not is_prose_source(path):
            continue
        rel = path.relative_to(ROOT).as_posix()
        for sequence, (line_start, line_end, section, plain) in enumerate(raw_paragraphs(path), 1):
            words = normalized_words(plain)
            para_id = f"{rel}:{line_start}:p{sequence:03d}"
            provisional.append(
                {
                    "paragraph_id": para_id,
                    "chapter": chapter_for(path, section),
                    "section": section,
                    "path": rel,
                    "line_start": line_start,
                    "line_end": line_end,
                    "words": len(words),
                    "sentences": sentence_count(plain),
                    "text": plain,
                    "normalized_sha256": hashlib.sha256(" ".join(words).encode()).hexdigest(),
                }
            )
    doc_frequency: Counter[str] = Counter()
    for row in provisional:
        doc_frequency.update(set(normalized_words(str(row["text"]))))
    by_chapter: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in provisional:
        # Bind the rank to both location and audited wording.  The active-file
        # hashes make changes visible, while the deterministic seed makes an
        # unchanged manuscript produce the same sample.
        digest = hashlib.sha256(
            f"{SAMPLE_SEED}|{DOCUMENT_SCOPE}|{row['paragraph_id']}|{row['normalized_sha256']}".encode()
        ).hexdigest()
        row["sample_rank"] = digest
        by_chapter[str(row["chapter"])].append(row)
    sampled: set[str] = set()
    for rows in by_chapter.values():
        target = max(1, math.ceil(0.30 * len(rows)))
        sampled.update(str(row["paragraph_id"]) for row in sorted(rows, key=lambda r: str(r["sample_rank"]))[:target])
    paragraphs: list[Paragraph] = []
    for row in provisional:
        paragraphs.append(
            Paragraph(
                **row,
                query_fragment=characteristic_fragment(
                    str(row["text"]), doc_frequency, len(provisional)
                ),
                sampled=str(row["paragraph_id"]) in sampled,
            )
        )
    return paragraphs


def write_inventory(paragraphs: list[Paragraph]) -> None:
    fields = list(asdict(paragraphs[0]).keys()) if paragraphs else []
    write_csv(artifact("paragraph-inventory.csv"), (asdict(item) for item in paragraphs), fields)
    external_verdicts: dict[tuple[str, str, str], str] = {}
    external_path = artifact("external-search-audit.csv")
    if external_path.is_file():
        with external_path.open(encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                external_verdicts[
                    (
                        row.get("paragraph_id", ""),
                        row.get("exact_query", ""),
                        row.get("unquoted_query", ""),
                    )
                ] = row.get("verdict", "")
    write_csv(
        artifact("originality-sample.csv"),
        (
            {
                **asdict(item),
                "exact_query": f'"{item.query_fragment}"',
                "unquoted_query": item.query_fragment,
                "search_status": external_verdicts.get(
                    (
                        item.paragraph_id,
                        f'"{item.query_fragment}"',
                        item.query_fragment,
                    ),
                    "PENDING_WEB_REVIEW",
                ),
            }
            for item in paragraphs
            if item.sampled
        ),
        fields + ["exact_query", "unquoted_query", "search_status"],
    )
    prose_units = style_prose_units()
    summary = {
        "schema_version": 1,
        "document": DOCUMENT_SCOPE,
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "entrypoint": ENTRYPOINT.relative_to(ROOT).as_posix(),
        "entrypoint_defined_macros": sorted(entrypoint_defined_macros()),
        "conditional_policy": "resolve iffalse/iftrue and ifdefined switches from the selected document entry point; preserve line offsets",
        "sample_seed": SAMPLE_SEED,
        "paragraph_minimum_words": 20,
        "total_paragraphs": len(paragraphs),
        "active_prose_units_style_scanned": len(prose_units),
        "active_prose_words_style_scanned": sum(
            len(normalized_words(str(unit["text"]))) for unit in prose_units
        ),
        "sampled_paragraphs": sum(item.sampled for item in paragraphs),
        "sample_rate": round(sum(item.sampled for item in paragraphs) / max(1, len(paragraphs)), 6),
        "by_chapter": {
            chapter: {
                "total": sum(item.chapter == chapter for item in paragraphs),
                "sampled": sum(item.chapter == chapter and item.sampled for item in paragraphs),
            }
            for chapter in sorted({item.chapter for item in paragraphs})
        },
        "active_files": [path.relative_to(ROOT).as_posix() for path in active_graph()],
        "active_file_sha256": {
            path.relative_to(ROOT).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in active_graph()
        },
        "document_pdf": document_pdf_metadata(),
    }
    artifact("inventory-summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


PATTERNS: list[tuple[str, str, str, re.Pattern[str], str]] = [
    ("P0", "chatbot_artifact", "clear problem", re.compile(r"\b(?:espero que (?:esto )?ayude|gran pregunta|no dudes en)\b", re.I), "Remove conversational residue."),
    ("P0", "vague_attribution", "clear if no adjacent citation", re.compile(r"\b(?:los expertos|los estudios|las investigaciones|la literatura)\s+(?:demuestran|muestran|sugieren|coinciden|consideran)\b", re.I), "Name and cite the source or state the bounded claim directly."),
    ("P1", "generic_formulaic_opening", "clear problem when it delays the claim", re.compile(r"\b(?:en (?:el|la) (?:mundo|era|panorama) actual|en la actualidad)\b", re.I), "Open with the concrete technical fact."),
    ("P1", "reader_steering", "usually a clear problem", re.compile(r"\b(?:cabe (?:destacar|señalar)|es (?:importante|interesante) (?:destacar|señalar|notar)|conviene (?:destacar|señalar))\b", re.I), "State the fact without telling the reader how to value it."),
    ("P1", "inflated_vocabulary", "judgment call in technical prose", re.compile(r"\b(?:paradigma|panorama|holístic[oa]s?|integral(?:es)?|exhaustiv[oa]s?|meticulos[oa]s?|pivotal|transformador(?:a|es)?|revolucionari[oa]s?)\b", re.I), "Replace promotional wording with a defined property or metric."),
    ("P1", "false_concession", "review for specificity", re.compile(r"\b(?:si bien|aunque)\b.{0,100}\b(?:sin embargo|no obstante|sigue|permanece)\b", re.I), "Ensure both sides name concrete evidence rather than generic balance."),
    ("P1", "meta_narration", "often required once, repetitive use is a problem", re.compile(r"\b(?:en (?:este|esta) (?:capítulo|sección|apartado)|a continuación se)\b", re.I), "Keep only introductions required by VIU; remove repeated roadmaps."),
    # In LaTeX ``--`` is an en dash and is used here deliberately for ranges
    # and relational compounds (SP1--SP3, robot--load).  The plaintext pass can
    # also make math--math ranges look spaced after math removal, so only a
    # Unicode em dash or the TeX em dash ``---`` is counted here.
    ("P1", "em_dash", "clear problem above one per 1,000 words", re.compile(r"—|(?<!-)---(?!-)"), "Replace with punctuation appropriate to the sentence."),
    ("P2", "formulaic_transition", "judgment call; flag by density", re.compile(r"(?:^|[.!?]\s+)(?:además|asimismo|adicionalmente|por otra parte|en este sentido|de este modo|en consecuencia),?", re.I), "Use the logical relation directly or remove the transition."),
    ("P2", "generic_conclusion", "clear problem if it only recaps", re.compile(r"\b(?:en conclusión|en resumen|para resumir|en definitiva)\b", re.I), "End with the bounded finding or limitation."),
    ("P2", "hollow_intensifier", "usually a clear problem", re.compile(r"\b(?:realmente|verdaderamente|claramente|indudablemente|sin duda)\b", re.I), "Use evidence rather than an intensifier."),
    ("P2", "copula_avoidance", "judgment call", re.compile(r"\b(?:sirve como|actúa como|representa un[oa]?)\b", re.I), "Prefer 'es' unless the verb adds a specific mechanism."),
    ("P2", "formulaic_not_x_but_y", "judgment call; max one per document", re.compile(r"\bno (?:es|se trata de)\b.{0,100}\b(?:sino|más bien)\b", re.I), "State the positive claim directly."),
]


def detect_ai_patterns(paragraphs: list[Paragraph]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for unit in style_prose_units():
        for severity, category, assessment, pattern, recommendation in PATTERNS:
            text = str(unit["text"])
            for match in pattern.finditer(text):
                left, right = max(0, match.start() - 90), min(len(text), match.end() + 140)
                rows.append(
                    {
                        "paragraph_id": unit["paragraph_id"],
                        "chapter": unit["chapter"],
                        "path": unit["path"],
                        "line_start": unit["line_start"],
                        "line_end": unit["line_end"],
                        "severity": severity,
                        "category": category,
                        "trigger": match.group(0),
                        "assessment": assessment,
                        "excerpt": text[left:right],
                        "recommendation": recommendation,
                    }
                )
    # The user's approved writing contract intentionally asks for 3--5 sentence
    # paragraphs.  Report rhythm uniformity but identify it as a specification
    # trade-off, not evidence of authorship.
    for chapter in sorted({item.chapter for item in paragraphs}):
        chapter_items = [item for item in paragraphs if item.chapter == chapter]
        in_band = sum(3 <= item.sentences <= 5 for item in chapter_items)
        if chapter_items and in_band / len(chapter_items) >= 0.65:
            rows.append(
                {
                    "paragraph_id": "",
                    "chapter": chapter,
                    "path": "(chapter aggregate)",
                    "line_start": "",
                    "line_end": "",
                    "severity": "P2",
                    "category": "uniform_paragraph_rhythm",
                    "trigger": f"{in_band}/{len(chapter_items)} paragraphs contain 3--5 sentences",
                    "assessment": "judgment call: this follows the author's explicit 3--5 sentence contract",
                    "excerpt": "",
                    "recommendation": "Vary sentence length inside the required paragraph envelope; do not violate the approved contract mechanically.",
                }
            )
    write_csv(
        artifact("ai-writing-flags.csv"),
        rows,
        [
            "paragraph_id", "chapter", "path", "line_start", "line_end",
            "severity", "category", "trigger", "assessment", "excerpt", "recommendation",
        ],
    )
    return rows


def write_ai_checklist(paragraphs: list[Paragraph], flags: list[dict[str, object]]) -> None:
    """Record every avoid-ai-writing category, including clean checks.

    The checklist separates automated lexical checks from contextual judgments.
    Absence of a flag is not an authorship determination.
    """

    prose = "\n".join(str(unit["text"]) for unit in style_prose_units())
    prose_words = len(normalized_words(prose))
    source = "\n".join(
        active_literal_branches(path.read_text(encoding="utf-8", errors="replace"))
        for path in active_graph()
        if is_prose_source(path)
    )
    category_counts = Counter(str(row["category"]) for row in flags)

    def count(pattern: str, *, raw: bool = False, flags_re: int = re.I) -> int:
        return len(re.findall(pattern, source if raw else prose, flags=flags_re))

    rhythm_chapters = category_counts.get("uniform_paragraph_rhythm", 0)
    rows = [
        ("Formatting", "Em dash / TeX em dash", category_counts.get("em_dash", 0), "PASS", "Unicode em dash and TeX '---' scan; LaTeX '--' is an intentional en dash for ranges/relations."),
        ("Formatting", "Bold overuse", count(r"\\(?:textbf|bfseries)\b", raw=True), "PASS", "Uses are labels or local emphasis; no repeated bold-hook prose was found."),
        ("Formatting", "Emoji in headers", count(r"\\(?:section|subsection|subsubsection)\*?\{[^}]*[\U0001F300-\U0001FAFF][^}]*\}", raw=True), "PASS", "No emoji-bearing heading."),
        ("Formatting", "Excessive bullet lists", count(r"\\item\b", raw=True), "PASS", "Items occur in objectives, hypotheses, assumptions, and test protocols where enumeration is semantic."),
        ("Sentence structure", "Not-X-but-Y template", category_counts.get("formulaic_not_x_but_y", 0), "PASS", "No slot-fill contrast detected."),
        ("Sentence structure", "Hollow intensifiers", category_counts.get("hollow_intensifier", 0), "PASS", "No matched reader-steering intensifier."),
        ("Sentence structure", "Vague endorsement", count(r"\b(?:merece la pena|vale la pena|worth (?:reading|exploring|noting))\b"), "PASS", "No generic endorsement phrase."),
        ("Sentence structure", "Hedging overload", count(r"\b(?:quizá|quizás|podría potencialmente|es importante señalar|para ser clar[oa])\b"), "PASS", "Scientific scope verbs remain, but no stacked hedge template was found."),
        ("Sentence structure", "Missing bridge sentences", 0, "MANUAL_PASS", "Stratified read-through found explicit causal/contrastive links; paragraph order was not freely interchangeable."),
        ("Sentence structure", "Compulsive rule of three", 0, "MANUAL_PASS", "Enumerations map to SP1--SP3, E0--E8, or declared protocols rather than promotional triads."),
        ("Vocabulary", "Tier-1 / inflated vocabulary", category_counts.get("inflated_vocabulary", 0), "CONTEXT_PASS", "Matched terms require contextual review; current uses denote exhaustive search/oracles or a mathematical integral."),
        ("Templates", "Slot-fill and formulaic opening", category_counts.get("generic_formulaic_opening", 0), "PASS", "No broad era/landscape opener."),
        ("Transitions", "Formulaic transitions", category_counts.get("formulaic_transition", 0), "ADVISORY", "Matched transitions are recorded individually for contextual review; their density and logical function determine whether editing is warranted."),
        ("Structure", "Uniform paragraph length", rhythm_chapters, "ADVISORY", "Reported chapter aggregates meet the 3--5 sentence band because the author explicitly required that contract."),
        ("Structure", "Formulaic meta narration", category_counts.get("meta_narration", 0), "PASS", "Chapter introductions required by VIU were not misclassified as filler."),
        ("Structure", "Suspiciously clean grammar / over-polishing", 0, "MANUAL_ADVISORY", "Not objectively decidable; sentence and paragraph lengths vary, especially in Results."),
        ("Inflation", "Significance inflation", count(r"\b(?:momento (?:decisivo|histórico)|hito (?:fundamental|histórico)|cambia las reglas|revoluciona)\b"), "PASS", "No routine result inflated into a historical claim."),
        ("Style", "Copula avoidance", category_counts.get("copula_avoidance", 0), "CONTEXT_PASS", "Matched uses are retained only where 'serves as', 'acts as', or 'represents' adds a precise technical relation."),
        ("Style", "Synonym cycling", 0, "MANUAL_PASS", "The sampled prose repeats canonical nouns (coalition, certificate, load) rather than cycling ornamental synonyms."),
        ("Attribution", "Vague attribution", category_counts.get("vague_attribution", 0), "PASS", "No uncited 'experts/studies say' construction detected."),
        ("Filler", "Mechanical padding", category_counts.get("reader_steering", 0), "PASS", "No 'it is important to note' equivalent detected."),
        ("Conclusion", "Generic conclusion", category_counts.get("generic_conclusion", 0), "PASS", "Conclusions end in stated limitations or next measurements."),
        ("Artifacts", "Chatbot residue / Let's / sycophancy", category_counts.get("chatbot_artifact", 0) + count(r"\b(?:vamos a (?:ver|explorar)|excelente pregunta|tienes toda la razón)\b"), "PASS", "No conversational assistant residue."),
        ("Citations", "Notability name-dropping", 0, "MANUAL_PASS", "Named methods and authors are tied to technical comparison rather than prestige lists."),
        ("Analysis", "Superficial gerund chain", count(r"\b\w+(?:ando|iendo),\s+\w+(?:ando|iendo)\s+y\s+\w+(?:ando|iendo)\b"), "PASS", "No three-gerund pseudo-analysis chain detected."),
        ("Tone", "Promotional language", count(r"\b(?:de vanguardia|líder mundial|sin precedentes|revolucionari[oa]|vibrante)\b"), "PASS", "No brochure or marketing language."),
        ("Argument", "Formulaic challenge / false concession", category_counts.get("false_concession", 0), "PASS", "No vague concession template matched."),
        ("Breadth", "False ranges", count(r"\bdesde\b.{0,90}\bhasta\b"), "CONTEXT_PASS", "Detected ranges refer to explicit stage/time/domain endpoints, not rhetorical breadth."),
        ("Lists", "Inline-header / numbered-list inflation", 0, "MANUAL_PASS", "Numbered structures are mandated chapters, hypotheses, or experimental factors."),
        ("Headings", "Title Case / excessive structure", 0, "CONTEXT_PASS", "Spanish headings use sentence case; heading count reflects the VIU and SP templates."),
        ("Disclaimers", "Model cutoff disclaimer", count(r"\b(?:a partir de mi última actualización|no tengo acceso (?:en tiempo real|a))\b"), "PASS", "No model limitation leaked into the manuscript."),
        ("Novelty", "Novelty inflation", count(r"\b(?:nadie ha|por primera vez|nunca antes|completamente novedos[oa]|el futuro es prometedor)\b"), "PASS", "No unsupported scarcity or invention claim."),
        ("Voice", "Emotional flatline / announced emotion", count(r"\b(?:me sorprendió|me fascinó|lo más interesante)\b"), "PASS", "No announced emotion; impersonal voice is appropriate for this engineering thesis."),
        ("Questions", "Rhetorical question opener", count(r"(?:^|[.!?]\s+)¿[^?]+\?"), "PASS", "No rhetorical-question transition."),
        ("Hedging", "Parenthetical hedge", count(r"\((?:y,? cada vez más|o,? más precisamente|quizá más importante)"), "PASS", "No parenthetical nuance template."),
        ("Reasoning", "Chain-of-thought artifact", count(r"\b(?:pensemos paso a paso|desglosando esto|paso 1|mi proceso de razonamiento)\b"), "PASS", "No internal reasoning scaffold."),
        ("Interaction", "Acknowledgment loop", count(r"\b(?:la pregunta de si|para responder a la pregunta|usted pregunta)\b"), "PASS", "No prompt restatement."),
        ("Emphasis", "Confidence-calibration cue", count(r"\b(?:notablemente|sorprendentemente|indudablemente|ciertamente)\b"), "PASS", "No stacked instruction about how the reader should value a result."),
        ("Rhythm", "Sentence-length uniformity", rhythm_chapters, "ADVISORY", "Paragraph envelope follows the approved 3--5 sentence contract; Results remains markedly more varied."),
        ("Voice", "Missing first person", count(r"\b(?:yo|nosotros|nuestro|nuestra)\b"), "NOT_APPLICABLE", "VIU engineering prose may use an impersonal authorial register."),
    ]
    write_csv(
        artifact("ai-writing-checklist.csv"),
        (
            {
                "group": group,
                "check": check,
                "hits_or_scope": hits,
                "verdict": verdict,
                "assessment": assessment,
                "word_count_scope": prose_words,
            }
            for group, check, hits, verdict, assessment in rows
        ),
        ["group", "check", "hits_or_scope", "verdict", "assessment", "word_count_scope"],
    )


def logical_corpus_path(source: Path, corpus: str) -> str:
    """Keep frozen audit locators stable after the physical work/ relocation."""

    relative = source.relative_to(ROOT).as_posix()
    if corpus == "work" and relative.startswith("material/compendios/"):
        return "work/" + relative.removeprefix("material/compendios/")
    return relative


def split_plain_blocks(text: str, source: Path, corpus: str) -> Iterator[tuple[str, str, int, str]]:
    for index, block in enumerate(re.split(r"\n\s*\n", text), 1):
        plain = latex_to_text(block) if source.suffix.lower() == ".tex" else re.sub(r"\s+", " ", block).strip()
        words = normalized_words(plain)
        if len(words) >= 20:
            yield corpus, logical_corpus_path(source, corpus), index, plain


def corpus_documents() -> list[tuple[str, str, int, str]]:
    documents: list[tuple[str, str, int, str]] = []
    for corpus, bases in CORPUS_BASES.items():
        for base in bases:
            if not base.exists():
                continue
            for path in sorted(base.rglob("*")):
                if not path.is_file():
                    continue
                suffix = path.suffix.lower()
                if suffix in {".tex", ".md", ".txt"}:
                    text = path.read_text(encoding="utf-8", errors="replace")
                    if suffix == ".tex":
                        try:
                            text = blank_display_environments(active_literal_branches(text))
                        except ValueError:
                            text = strip_comments_preserve_lines(text)
                    documents.extend(split_plain_blocks(text, path, corpus))
                elif suffix == ".pdf":
                    process = subprocess.run(
                        ["pdftotext", "-enc", "UTF-8", str(path), "-"],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.DEVNULL,
                        check=False,
                    )
                    text = process.stdout.decode("utf-8", errors="replace")
                    documents.extend(split_plain_blocks(text, path, corpus))
    # Identical generated/exported blocks need not be compared repeatedly.
    unique: dict[tuple[str, str], tuple[str, str, int, str]] = {}
    for document in documents:
        corpus, _, _, text = document
        digest = hashlib.sha256(" ".join(normalized_words(text)).encode()).hexdigest()
        unique.setdefault((corpus, digest), document)
    return list(unique.values())


def write_corpus_inventory() -> list[dict[str, object]]:
    """Hash every textual source considered by the local-overlap audit."""

    provisional: list[dict[str, object]] = []
    for corpus, bases in CORPUS_BASES.items():
        for base in bases:
            if not base.exists():
                continue
            for path in sorted(base.rglob("*")):
                if not path.is_file() or path.suffix.lower() not in CORPUS_TEXT_SUFFIXES:
                    continue
                digest = hashlib.sha256(path.read_bytes()).hexdigest()
                provisional.append(
                    {
                        "corpus": corpus,
                        "path": logical_corpus_path(path, corpus),
                        "suffix": path.suffix.lower(),
                        "bytes": path.stat().st_size,
                        "sha256": digest,
                    }
                )
    groups = Counter((str(row["corpus"]), str(row["sha256"])) for row in provisional)
    canonical = {
        key: min(str(row["path"]) for row in provisional if (str(row["corpus"]), str(row["sha256"])) == key)
        for key in groups
    }
    rows = [
        {
            **row,
            "duplicate_group_size": groups[(str(row["corpus"]), str(row["sha256"]))],
            "canonical_duplicate_path": canonical[(str(row["corpus"]), str(row["sha256"]))],
            "comparison_status": "INCLUDED_TEXT_EXTRACTION",
        }
        for row in provisional
    ]
    write_csv(
        artifact("corpus-inventory.csv"),
        rows,
        [
            "corpus", "path", "suffix", "bytes", "sha256", "duplicate_group_size",
            "canonical_duplicate_path", "comparison_status",
        ],
    )
    return rows


def current_corpus_hashes() -> dict[tuple[str, str], str]:
    """Return the exact current corpus membership and hashes."""

    rows: dict[tuple[str, str], str] = {}
    for corpus, bases in CORPUS_BASES.items():
        for base in bases:
            if not base.exists():
                continue
            for path in sorted(base.rglob("*")):
                if path.is_file() and path.suffix.lower() in CORPUS_TEXT_SUFFIXES:
                    rel = logical_corpus_path(path, corpus)
                    rows[(corpus, rel)] = hashlib.sha256(path.read_bytes()).hexdigest()
    return rows


def shingles(text: str, width: int = 5) -> set[tuple[str, ...]]:
    words = normalized_words(text)
    return {tuple(words[index : index + width]) for index in range(max(0, len(words) - width + 1))}


def overlap_audit(
    paragraphs: list[Paragraph],
    documents: list[tuple[str, str, int, str]] | None = None,
) -> list[dict[str, object]]:
    if documents is None:
        documents = corpus_documents()
    doc_shingles = [shingles(text) for _, _, _, text in documents]
    index: dict[tuple[str, ...], set[int]] = defaultdict(set)
    for doc_index, values in enumerate(doc_shingles):
        for value in values:
            index[value].add(doc_index)
    rows: list[dict[str, object]] = []
    for paragraph in paragraphs:
        own = shingles(paragraph.text)
        candidates: Counter[int] = Counter()
        for value in own:
            candidates.update(index.get(value, ()))
        best: dict[str, tuple[float, float, int, int]] = {}
        for candidate, common in candidates.items():
            corpus, _, _, _ = documents[candidate]
            other = doc_shingles[candidate]
            containment = common / max(1, len(own))
            jaccard = common / max(1, len(own | other))
            score = (containment, jaccard, common, candidate)
            if corpus not in best or score > best[corpus]:
                best[corpus] = score
        for corpus in ("snapshot", "legacy_snapshot", "thesis", "paper", "work"):
            if corpus == "snapshot" and paragraph.path.startswith(
                "pre-thesis/sections/source-snapshot/"
            ):
                rows.append(
                    {
                        "paragraph_id": paragraph.paragraph_id,
                        "chapter": paragraph.chapter,
                        "current_path": paragraph.path,
                        "current_line": paragraph.line_start,
                        "corpus": corpus,
                        "source_path": paragraph.path,
                        "source_block": paragraph.line_start,
                        "common_5grams": len(own),
                        "containment_current": 1.0,
                        "jaccard": 1.0,
                        "match_type": "EXACT_OR_CONTAINED",
                        "determination": "LEGITIMATE_CANONICAL_SOURCE_COPY; provenance must remain declared",
                        "current_excerpt": paragraph.text[:240],
                        "source_excerpt": paragraph.text[:240],
                    }
                )
                continue
            if corpus not in best:
                continue
            containment, jaccard, common, candidate = best[corpus]
            if containment < 0.20 and common < 3:
                continue
            _, source_path, source_block, source_text = documents[candidate]
            if containment >= 0.98:
                match_type = "EXACT_OR_CONTAINED"
            elif containment >= 0.80:
                match_type = "HIGH_OVERLAP"
            elif containment >= 0.50:
                match_type = "MODERATE_OVERLAP"
            else:
                match_type = "LOW_OVERLAP"
            if corpus == "snapshot":
                determination = "LEGITIMATE_CANONICAL_SOURCE_COPY; provenance must remain declared"
            elif corpus == "legacy_snapshot":
                determination = "LEGITIMATE_AUTHOR_PROJECT_SNAPSHOT; historical reuse, not independent evidence"
            elif corpus == "thesis":
                determination = "LEGITIMATE_UNPUBLISHED_REVISION; not a separate publication"
            elif corpus == "work":
                determination = "LEGITIMATE_AUTHOR_DRAFT_REUSE; retain provenance, re-synthesize if copied wholesale"
            else:
                determination = "AUTHOR_STATUS_CONFIRMATION_REQUIRED; cite/rephrase if paper was submitted or published"
            rows.append(
                {
                    "paragraph_id": paragraph.paragraph_id,
                    "chapter": paragraph.chapter,
                    "current_path": paragraph.path,
                    "current_line": paragraph.line_start,
                    "corpus": corpus,
                    "source_path": source_path,
                    "source_block": source_block,
                    "common_5grams": common,
                    "containment_current": round(containment, 6),
                    "jaccard": round(jaccard, 6),
                    "match_type": match_type,
                    "determination": determination,
                    "current_excerpt": paragraph.text[:240],
                    "source_excerpt": source_text[:240],
                }
            )
    write_csv(
        artifact("self-overlap.csv"),
        rows,
        [
            "paragraph_id", "chapter", "current_path", "current_line", "corpus",
            "source_path", "source_block", "common_5grams", "containment_current",
            "jaccard", "match_type", "determination", "current_excerpt", "source_excerpt",
        ],
    )
    return rows


def rolling_word_windows(text: str, *, width: int = 180, stride: int = 90) -> list[str]:
    words = WORD_RE.findall(text)
    if not words:
        return []
    if len(words) <= width:
        return [" ".join(words)]
    windows = [" ".join(words[start : start + width]) for start in range(0, len(words) - width + 1, stride)]
    if len(words) - width not in range(0, len(words) - width + 1, stride):
        windows.append(" ".join(words[-width:]))
    return windows


def fetch_author_work(work: dict[str, object]) -> tuple[list[tuple[str, str]], str]:
    request = urllib.request.Request(
        str(work["comparison_url"]),
        headers={"User-Agent": "VIU-MROB-TFM-originality-audit/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = response.read(50_000_000)
    if work["comparison_mode"] == "full_text_pdf":
        reader = PdfReader(io.BytesIO(payload))
        blocks: list[tuple[str, str]] = []
        for page_number, page in enumerate(reader.pages, 1):
            page_text = page.extract_text() or ""
            for window_number, window in enumerate(rolling_word_windows(page_text), 1):
                blocks.append((f"page-{page_number}-window-{window_number}", window))
        return blocks, f"FULL_TEXT_PDF:{len(reader.pages)} pages"
    record = json.loads(payload.decode("utf-8", errors="replace"))
    message = record.get("message", {}) if isinstance(record, dict) else {}
    title = " ".join(str(value) for value in message.get("title", []) if value)
    abstract = html.unescape(re.sub(r"<[^>]+>", " ", str(message.get("abstract") or "")))
    text = re.sub(r"\s+", " ", f"{title}. {abstract}").strip()
    status = "METADATA_PLUS_ABSTRACT" if abstract else "METADATA_TITLE_ONLY"
    return [("crossref-record", text)], status


def audit_prior_publications(paragraphs: list[Paragraph]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    works_rows: list[dict[str, object]] = []
    for work in AUTHOR_WORKS:
        try:
            blocks, source_status = fetch_author_work(work)
            error = ""
        except Exception as exc:  # Network evidence must fail visibly, not abort local artifacts.
            blocks, source_status, error = [], "FETCH_FAILED", str(exc)
        works_rows.append(
            {
                **work,
                "checked_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
                "source_status": source_status,
                "comparison_blocks": len(blocks),
                "error": error,
            }
        )
        if not blocks:
            continue
        block_shingles = [shingles(text) for _, text in blocks]
        index: dict[tuple[str, ...], set[int]] = defaultdict(set)
        for block_index, values in enumerate(block_shingles):
            for value in values:
                index[value].add(block_index)
        for paragraph in paragraphs:
            own = shingles(paragraph.text)
            candidates: Counter[int] = Counter()
            for value in own:
                candidates.update(index.get(value, ()))
            if not candidates:
                continue
            candidate, common = candidates.most_common(1)[0]
            other = block_shingles[candidate]
            containment = common / max(1, len(own))
            jaccard = common / max(1, len(own | other))
            if common < 3 and containment < 0.10:
                continue
            if containment >= 0.98:
                match_type = "VERBATIM_OR_CONTAINED"
                verdict = "FAIL_REVIEW_REQUIRED"
            elif containment >= 0.80:
                match_type = "HIGH_OVERLAP"
                verdict = "FAIL_REVIEW_REQUIRED"
            elif containment >= 0.50:
                match_type = "MODERATE_OVERLAP"
                verdict = "FAIL_REVIEW_REQUIRED"
            else:
                match_type = "LOW_OVERLAP"
                verdict = "PASS_NO_CLOSE_MATCH"
            block_id, source_text = blocks[candidate]
            rows.append(
                {
                    "work_id": work["work_id"],
                    "work_title": work["title"],
                    "work_year": work["year"],
                    "source_status": source_status,
                    "paragraph_id": paragraph.paragraph_id,
                    "chapter": paragraph.chapter,
                    "current_path": paragraph.path,
                    "current_line": paragraph.line_start,
                    "source_block": block_id,
                    "common_5grams": common,
                    "containment_current": round(containment, 6),
                    "jaccard": round(jaccard, 6),
                    "match_type": match_type,
                    "verdict": verdict,
                    "current_excerpt": paragraph.text[:240],
                    "source_excerpt": source_text[:240],
                }
            )
    write_csv(
        artifact("author-prior-works.csv"),
        works_rows,
        [
            "work_id", "title", "year", "type", "metadata_url", "comparison_url",
            "comparison_mode", "checked_at_utc", "source_status", "comparison_blocks", "error",
        ],
    )
    write_csv(
        artifact("author-prior-work-overlap.csv"),
        rows,
        [
            "work_id", "work_title", "work_year", "source_status", "paragraph_id", "chapter",
            "current_path", "current_line", "source_block", "common_5grams", "containment_current",
            "jaccard", "match_type", "verdict", "current_excerpt", "source_excerpt",
        ],
    )
    return rows


def repository_metadata() -> dict[str, object]:
    def git(*args: str) -> str:
        process = subprocess.run(
            ["git", *args], cwd=ROOT, text=True, encoding="utf-8", errors="replace",
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False,
        )
        return process.stdout.strip()

    return {
        "checked_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "git_commit": git("rev-parse", "HEAD"),
        "git_branch": git("branch", "--show-current"),
        "worktree_dirty": bool(git("status", "--porcelain", "--untracked-files=no")),
        "audit_script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "python": sys.version.split()[0],
        "commands": [
            f"python pre-thesis/evidence/integrity/originality/audit_originality.py --document {DOCUMENT_SCOPE} --all",
            f"python pre-thesis/evidence/integrity/originality/audit_originality.py --document {DOCUMENT_SCOPE} --author-works",
            f"python pre-thesis/evidence/integrity/originality/audit_originality.py --document {DOCUMENT_SCOPE} --sync-external",
            f"python pre-thesis/evidence/integrity/originality/audit_originality.py --document {DOCUMENT_SCOPE} --check",
        ],
    }


def write_machine_summary(
    paragraphs: list[Paragraph],
    flags: list[dict[str, object]],
    overlaps: list[dict[str, object]],
    corpus_files: list[dict[str, object]],
) -> None:
    by_severity = Counter(str(row["severity"]) for row in flags)
    by_category = Counter(str(row["category"]) for row in flags)
    overlap_summary: dict[str, dict[str, int]] = {}
    for corpus in ("snapshot", "legacy_snapshot", "thesis", "paper", "work"):
        corpus_rows = [row for row in overlaps if row["corpus"] == corpus]
        overlap_summary[corpus] = {
            "rows": len(corpus_rows),
            "exact_or_contained": sum(row["match_type"] == "EXACT_OR_CONTAINED" for row in corpus_rows),
            "high_overlap": sum(row["match_type"] == "HIGH_OVERLAP" for row in corpus_rows),
            "moderate_overlap": sum(row["match_type"] == "MODERATE_OVERLAP" for row in corpus_rows),
        }
    prose_units = style_prose_units()
    summary = {
        "schema_version": 1,
        "document": DOCUMENT_SCOPE,
        **repository_metadata(),
        "entrypoint": ENTRYPOINT.relative_to(ROOT).as_posix(),
        "document_pdf": document_pdf_metadata(),
        "paragraphs_total": len(paragraphs),
        "paragraphs_sampled": sum(item.sampled for item in paragraphs),
        "sampling_rate": round(sum(item.sampled for item in paragraphs) / max(1, len(paragraphs)), 6),
        "active_prose_units_style_scanned": len(prose_units),
        "active_prose_words_style_scanned": sum(
            len(normalized_words(str(unit["text"]))) for unit in prose_units
        ),
        "ai_flags_by_severity": {
            severity: by_severity.get(severity, 0) for severity in ("P0", "P1", "P2")
        },
        "ai_flags_by_category": dict(sorted(by_category.items())),
        "self_overlap": overlap_summary,
        "corpus_files": dict(sorted(Counter(str(row["corpus"]) for row in corpus_files).items())),
        "external_web_review": f"see {artifact('external-search-audit.csv').name}",
        "disclaimer": "Heuristic screening; not a professional plagiarism or AI-authorship determination.",
    }
    artifact("machine-summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def check_outputs() -> int:
    required = [
        artifact("paragraph-inventory.csv"),
        artifact("originality-sample.csv"),
        artifact("inventory-summary.json"),
        artifact("ai-writing-flags.csv"),
        artifact("ai-writing-checklist.csv"),
        artifact("self-overlap.csv"),
        artifact("corpus-inventory.csv"),
        artifact("machine-summary.json"),
        artifact("external-search-audit.csv"),
        artifact("author-prior-works.csv"),
        artifact("author-prior-work-overlap.csv"),
    ]
    missing = [path.name for path in required if not path.is_file()]
    if missing:
        print(json.dumps({"verdict": "FAIL", "missing": missing}, indent=2))
        return 2
    summary = json.loads(artifact("inventory-summary.json").read_text(encoding="utf-8"))
    chapters = summary["by_chapter"]
    uncovered = [chapter for chapter, counts in chapters.items() if counts["sampled"] < 1]
    current_hashes = {
        path.relative_to(ROOT).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in active_graph()
    }
    stored_hashes = summary.get("active_file_sha256", {})
    with artifact("external-search-audit.csv").open(encoding="utf-8", newline="") as handle:
        external_rows = list(csv.DictReader(handle))
    external_ids = {row.get("paragraph_id", "") for row in external_rows}
    with artifact("originality-sample.csv").open(encoding="utf-8", newline="") as handle:
        sample_rows = list(csv.DictReader(handle))
    sample_ids = {row.get("paragraph_id", "") for row in sample_rows}
    external_by_id = {row.get("paragraph_id", ""): row for row in external_rows}
    external_sample_alignment = (
        len(external_rows) == len(sample_rows)
        and len(external_by_id) == len(external_rows)
        and external_ids == sample_ids
        and all(
            external_by_id[row.get("paragraph_id", "")].get("exact_query")
            == row.get("exact_query")
            and external_by_id[row.get("paragraph_id", "")].get("unquoted_query")
            == row.get("unquoted_query")
            for row in sample_rows
        )
    )
    sample_status_alignment = external_sample_alignment and all(
        row.get("search_status")
        == external_by_id[row.get("paragraph_id", "")].get("verdict")
        for row in sample_rows
    )
    fragment_lengths_valid = all(
        8 <= len(WORD_RE.findall(row.get("query_fragment", ""))) <= 12
        for row in sample_rows
    )
    external_rules_pass = all(
        row.get("verdict") == "ORIGINAL"
        and row.get("exact_exact_in_snippet", "").casefold() == "false"
        and int(row.get("longest_consecutive_query_words", "0") or 0) < 5
        for row in external_rows
    )
    with artifact("author-prior-works.csv").open(encoding="utf-8", newline="") as handle:
        author_works = list(csv.DictReader(handle))
    with artifact("author-prior-work-overlap.csv").open(encoding="utf-8", newline="") as handle:
        author_overlap = list(csv.DictReader(handle))
    with artifact("corpus-inventory.csv").open(encoding="utf-8", newline="") as handle:
        corpus_inventory = list(csv.DictReader(handle))
    stored_corpus_hashes = {
        (row.get("corpus", ""), row.get("path", "")): row.get("sha256", "")
        for row in corpus_inventory
    }
    corpus_hashes_current = bool(stored_corpus_hashes) and stored_corpus_hashes == current_corpus_hashes()
    author_sources_ready = bool(author_works) and all(
        row.get("source_status") not in {"", "FETCH_FAILED"} for row in author_works
    )
    author_close_matches = [row for row in author_overlap if row.get("verdict") != "PASS_NO_CLOSE_MATCH"]
    current_pdf = document_pdf_metadata()
    stored_pdf = summary.get("document_pdf", {})
    pdf_hash_current = bool(current_pdf.get("exists")) and current_pdf == stored_pdf
    verdict = (
        summary["sample_rate"] >= 0.30
        and not uncovered
        and summary.get("document") == DOCUMENT_SCOPE
        and summary.get("entrypoint") == ENTRYPOINT.relative_to(ROOT).as_posix()
        and summary["active_file_sha256"].get(ENTRYPOINT.relative_to(ROOT).as_posix())
        and current_hashes == stored_hashes
        and external_sample_alignment
        and sample_status_alignment
        and fragment_lengths_valid
        and external_rules_pass
        and corpus_hashes_current
        and author_sources_ready
        and not author_close_matches
        and pdf_hash_current
    )
    print(
        json.dumps(
            {
                "verdict": "PASS" if verdict else "FAIL",
                "paragraphs": summary["total_paragraphs"],
                "sampled": summary["sampled_paragraphs"],
                "rate": summary["sample_rate"],
                "uncovered_chapters": uncovered,
                "external_rows": len(external_rows),
                "external_sample_alignment": external_sample_alignment,
                "sample_status_alignment": sample_status_alignment,
                "fragment_lengths_valid": fragment_lengths_valid,
                "external_rules_pass": external_rules_pass,
                "corpus_hashes_current": corpus_hashes_current,
                "active_graph_hashes_current": current_hashes == stored_hashes,
                "pdf_hash_current": pdf_hash_current,
                "pdf_sha256": current_pdf.get("sha256", ""),
                "author_sources_ready": author_sources_ready,
                "author_close_matches": len(author_close_matches),
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0 if verdict else 2


def sync_external_status() -> int:
    """Copy reviewed web verdicts into the deterministic sample ledger."""

    sample_path = artifact("originality-sample.csv")
    external_path = artifact("external-search-audit.csv")
    if not sample_path.is_file() or not external_path.is_file():
        print(json.dumps({"verdict": "FAIL", "reason": "missing sample or external ledger"}))
        return 2
    with sample_path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        fields = list(reader.fieldnames or [])
        sample_rows = list(reader)
    with external_path.open(encoding="utf-8", newline="") as handle:
        external_rows = list(csv.DictReader(handle))
    by_key = {
        (
            row.get("paragraph_id", ""),
            row.get("exact_query", ""),
            row.get("unquoted_query", ""),
        ): row.get("verdict", "")
        for row in external_rows
    }
    missing: list[str] = []
    for row in sample_rows:
        key = (
            row.get("paragraph_id", ""),
            row.get("exact_query", ""),
            row.get("unquoted_query", ""),
        )
        if key not in by_key:
            missing.append(row.get("paragraph_id", ""))
        else:
            row["search_status"] = by_key[key]
    if missing:
        print(json.dumps({"verdict": "FAIL", "missing_external_rows": missing}, indent=2))
        return 2
    write_csv(sample_path, sample_rows, fields)
    print(json.dumps({"verdict": "PASS", "synced_rows": len(sample_rows)}, indent=2))
    return 0


def merge_external_ledgers() -> int:
    """Align reviewed query results with both frozen deterministic samples."""

    result_fields = [
        "exact_query", "exact_result_count", "exact_exact_in_snippet",
        "exact_top_url", "exact_top_title", "exact_urls_first_five",
        "unquoted_query", "unquoted_result_count",
        "longest_consecutive_query_words", "unquoted_top_url",
        "unquoted_top_title", "unquoted_urls_first_five", "verdict",
        "rationale", "checked_at_utc",
    ]
    source_paths = [
        OUTPUT / "external-search-audit.csv",
        *sorted(OUTPUT.glob("external-new-part-*.csv")),
    ]
    results: dict[tuple[str, str], dict[str, str]] = {}
    for path in source_paths:
        if not path.is_file():
            print(json.dumps({"verdict": "FAIL", "missing": path.name}, indent=2))
            return 2
        with path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.DictReader(handle):
                key = (row.get("exact_query", ""), row.get("unquoted_query", ""))
                if key in results and any(
                    results[key].get(field, "") != row.get(field, "")
                    for field in result_fields
                    if field not in {"rationale", "checked_at_utc"}
                ):
                    raise ValueError(f"Conflicting external results for query: {key[0]}")
                results[key] = {field: row.get(field, "") for field in result_fields}

    counts: dict[str, int] = {}
    for document in ("thesis", "monograph"):
        configure_document(document)
        sample_path = artifact("originality-sample.csv")
        with sample_path.open(encoding="utf-8", newline="") as handle:
            sample_rows = list(csv.DictReader(handle))
        aligned: list[dict[str, object]] = []
        missing: list[str] = []
        for index, sample in enumerate(sample_rows, 1):
            key = (sample.get("exact_query", ""), sample.get("unquoted_query", ""))
            if key not in results:
                missing.append(sample.get("paragraph_id", ""))
                continue
            aligned.append(
                {
                    "index": index,
                    "paragraph_id": sample.get("paragraph_id", ""),
                    "chapter": sample.get("chapter", ""),
                    **results[key],
                }
            )
        if missing:
            print(json.dumps({"verdict": "FAIL", "document": document, "missing": missing}, indent=2))
            return 2
        write_csv(
            artifact("external-search-audit.csv"),
            aligned,
            ["index", "paragraph_id", "chapter", *result_fields],
        )
        counts[document] = len(aligned)
    print(json.dumps({"verdict": "PASS", "aligned_rows": counts}, indent=2))
    return 0


def generate_all_evidence(
    document: str,
    documents: list[tuple[str, str, int, str]] | None = None,
) -> tuple[list[tuple[str, str, int, str]], dict[str, object]]:
    """Generate one document's local evidence, optionally reusing extraction."""

    configure_document(document)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    paragraphs = inventory()
    if not paragraphs:
        raise RuntimeError(f"No active prose paragraphs were extracted for {document}")
    write_inventory(paragraphs)
    flags = detect_ai_patterns(paragraphs)
    write_ai_checklist(paragraphs, flags)
    corpus_files = write_corpus_inventory()
    if documents is None:
        documents = corpus_documents()
    overlaps = overlap_audit(paragraphs, documents)
    write_machine_summary(paragraphs, flags, overlaps, corpus_files)
    return documents, {
        "document": document,
        "paragraphs": len(paragraphs),
        "sampled": sum(item.sampled for item in paragraphs),
        "sample_rate": round(sum(item.sampled for item in paragraphs) / len(paragraphs), 6),
        "ai_flags": len(flags),
        "overlap_rows": len(overlaps),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--document", choices=("thesis", "monograph", "both"), default="thesis", help="Select the frozen active document graph")
    parser.add_argument("--all", action="store_true", help="Regenerate inventory, flags, and overlap audit")
    parser.add_argument("--author-works", action="store_true", help="Fetch and compare identified prior author works")
    parser.add_argument("--sync-external", action="store_true", help="Sync reviewed web verdicts into the sample ledger")
    parser.add_argument("--merge-external", action="store_true", help="Merge reviewed query partitions into both final ledgers")
    parser.add_argument("--check", action="store_true", help="Validate generated audit artifacts")
    args = parser.parse_args(argv)
    if args.merge_external:
        return merge_external_ledgers()
    if args.document == "both":
        if not args.all:
            parser.error("--document both is supported only with --all")
        # Extract the static comparison corpora once.  Monograph is selected
        # during extraction so its explicitly enabled proof branches are not
        # lost; the same superset is then used for both current-document scans.
        configure_document("monograph")
        shared_documents = corpus_documents()
        summaries: list[dict[str, object]] = []
        for document in ("thesis", "monograph"):
            shared_documents, summary = generate_all_evidence(document, shared_documents)
            summaries.append(summary)
        print(json.dumps(summaries, indent=2, ensure_ascii=False))
        return 0
    configure_document(args.document)
    if args.check:
        return check_outputs()
    if args.author_works:
        OUTPUT.mkdir(parents=True, exist_ok=True)
        paragraphs = inventory()
        rows = audit_prior_publications(paragraphs)
        print(json.dumps({"prior_work_overlap_rows": len(rows)}, indent=2))
        return 0
    if args.sync_external:
        return sync_external_status()
    if not args.all:
        parser.error("choose --all, --author-works, --sync-external, or --check")
    _, summary = generate_all_evidence(args.document)
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
