"""Atomic quota-potential recruitment used by the SP1.N4 campaign."""

from .dpop_exact import DPOPResult, solve_dpop_exact_small

from .continuous import (
    POPULATION_METHODS,
    AtomicClosureResult,
    PopulationResult,
    VGNESolution,
    atomic_closure,
    population_direction,
    population_potential_and_fitness,
    run_distributed_population_game,
    run_distributed_vgne,
    run_population_game,
    solve_central_vgne,
    vgnekkt_residuals,
)
from .stochastic import (
    DynamicEpisodeResult,
    RecruitmentEvent,
    canonical_event_schedule,
    run_event_triggered_policy,
    run_perfect_foresight_oracle,
)

from .geo_qpg import (
    METHODS,
    LEGACY_METHODS,
    METHOD_LABELS,
    CoordinationOrderResult,
    MoveProposal,
    QuotaRegister,
    RunResult,
    TransactionCoordinator,
    build_proposal,
    build_transition_proposal,
    connected_triples,
    distributed_mis_indices,
    marginal_changes,
    minimum_improving_coalition_order,
    proposals_conflict,
    run_geo_qpg,
)

__all__ = [
    "METHODS",
    "LEGACY_METHODS",
    "METHOD_LABELS",
    "POPULATION_METHODS",
    "AtomicClosureResult",
    "CoordinationOrderResult",
    "MoveProposal",
    "PopulationResult",
    "DPOPResult",
    "DynamicEpisodeResult",
    "QuotaRegister",
    "RecruitmentEvent",
    "RunResult",
    "TransactionCoordinator",
    "VGNESolution",
    "atomic_closure",
    "build_proposal",
    "build_transition_proposal",
    "canonical_event_schedule",
    "connected_triples",
    "distributed_mis_indices",
    "marginal_changes",
    "minimum_improving_coalition_order",
    "population_direction",
    "population_potential_and_fitness",
    "proposals_conflict",
    "run_geo_qpg",
    "run_distributed_vgne",
    "run_distributed_population_game",
    "run_event_triggered_policy",
    "run_population_game",
    "run_perfect_foresight_oracle",
    "solve_central_vgne",
    "solve_dpop_exact_small",
    "vgnekkt_residuals",
]
